/*
	Copyright (c) 2012-2013,   To get sources and documentation, please visit:

		http://dms.gw.com.cn
*/

//>>built
require({cache:{"news/marketAttention/util":function(){define(["dojo/date/locale"],function(){return{cfgInfo:{single_list_page_size:50,search_menuid:"",search_parameter:{}},getPre3Month:function(){var c=new Date,g=c.getFullYear(),f=c.getMonth()+1,b=c.getDate(),h=new Date(c.getTime()-31104E6),e=h.getFullYear(),j=h.getMonth()+1,h=h.getDate();pre3=new Date(c.getTime()-31104E6);pre3_year=pre3.getFullYear();pre3_month=pre3.getMonth()+1;pre3_date=pre3.getDate();return{bdate:[e,10>j?"0"+j:j,10>h?"0"+h:h,
"000000"].join(""),b3date:[pre3_year,10>pre3_month?"0"+pre3_month:pre3_month,10>pre3_date?"0"+pre3_date:pre3_date,"000000"].join(""),edate:[g,10>f?"0"+f:f,10>b?"0"+b:b,"235959"].join("")}},isToday:function(c){var g=new Date,f=g.getFullYear().toString(),b=(g.getMonth()+1).toString(),g=g.getDate().toString();10>b&&(f+="0");f+=b;10>g&&(f+="0");return c<f+(g+"000000")?!1:!0},formatFullDate:function(c){return this._checkDate(c)?(c=this._getDateArray(c),c[1]+"\u5e74"+c[2]+"\u6708"+c[3]+"\u65e5 "+c[4]+":"+
c[5]):""},formatDate:function(c){return this._checkDate(c)?(c=this._getDateArray(c),c[2]+"/"+c[3]):""},formatTime:function(c){return this._checkDate(c)?(c=this._getDateArray(c),c[4]+":"+c[5]):""},_getDateArray:function(c){return/(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(c)},_checkDate:function(c){return"string"==typeof c?!0:!1}}})},"news/marketAttention/marketNewsList":function(){require({cache:{"url:news/marketAttention/templates/newsList.html":'<ul class="con_list" data-dojo-attach-point="newsList" data-dojo-attach-event="onclick:_listItemClick"></ul>',
"url:news/marketAttention/templates/listItemDtl_top.html":'<li style="height:32px;" class="ecllip">\r\n\t<a href="a.html#<%=C1%>" target="news_iframe" class="font_blue_ex font_20" data-author="<%=C8%>" data-time="<%=time%>" data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>\r\n</li>',"url:news/marketAttention/templates/listItemDtl_left.html":'<li>\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="font_gray font_14" data-author="<%=C8%>" data-time="<%=Ltime%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>&nbsp;|<a href="a.html#<%=C1R%>" target="news_iframe"   class="font_gray font_14" data-author="<%=C8R%>" data-time="<%=Rtime%>"  data-news-file="<%=C4R%>" data-news-id="<%=C1R%>"><%=C3R%></a>\r\n</li>',
"url:news/marketAttention/templates/listItemDtl_right.html":'<li class="list_style">\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="<%=C19L%>" data-author="<%=C8%>" data-time="<%=Ltime%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>&nbsp;|<a href="a.html#<%=C1R%>" target="news_iframe"   class="<%=C19R%>" data-author="<%=C8R%>" data-time="<%=Rtime%>"  data-news-file="<%=C4R%>" data-news-id="<%=C1R%>"><%=C3R%></a>\r\n</li>',"url:news/marketAttention/templates/listItemDtl_left_single.html":'<li>\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="font_gray font_14" data-author="<%=C8%>" data-time="<%=time%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>\r\n</li>',
"url:news/marketAttention/templates/listItemDtl_right_single.html":'<li class="list_style">\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="<%=C19%>" data-author="<%=C8%>" data-time="<%=time%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>\r\n</li>'}});define("news/marketAttention/marketNewsList","./util,dojo/_base/declare,dojo/_base/lang,dojo/dom,dijit/_WidgetBase,dijit/_TemplatedMixin,dojo/text!./templates/newsList.html,dojo/text!./templates/listItemDtl_top.html,dojo/text!./templates/listItemDtl_left.html,dojo/text!./templates/listItemDtl_right.html,dojo/text!./templates/listItemDtl_left_single.html,dojo/text!./templates/listItemDtl_right_single.html,dojo/aspect,./MicroTemplating,dojo/dom-construct,dojo/on,./newsStore,dojo/query".split(","),
function(c,g,f,b,h,e,j,t,o,n,q,r,u,k,l,s,w,p){return g("demos.news.newsPane",[h,e],{templateString:j,options:{},store:null,detailPane:"",detailTitle:"",detailInfo:"",list_no_query:!1,postCreate:function(){u.after(this.store,"convert",f.hitch(this,this.onStoreMsgArrived));!this.list_no_query&&this.store.query();this.inherited(arguments);this.detailPane=b.byId(this.detailPane||"xin_wen_detail");this.detailTitle=b.byId(this.detailTitle||"xin_wen_title");this.detailInfo=b.byId(this.detailInfo||"xin_wen_info")},
startup:function(){this.inherited(arguments)},onStoreMsgArrived:function(b){this.updateNewsList(b);return b},updateNewsList:function(b){var e=p(".text_title_onthis a"),e=0<e.length&&e[0].dataset.newsId,d={};if(5>=b.length){for(i=0;i<5-b.length;i++)b.push({});b.forEach(f.hitch(this,function(a,b){var e=!1;a&&(e=!0);a.C1=a.C1||a.C2;a.C2=a.C2||"";a.C3=a.C3||"";a.C4=a.C4||"";a.C8=a.C8||"";a.C16=a.C16||"";var m=a.C16;m?(a.C16=!0==c.isToday(a.C16)?c.formatTime(m):c.formatDate(m),a.time=c.formatFullDate(m)):
a.time="";if(0==b)this.newsList.appendChild(l.toDom(k(t,a)));else if(1==b%2)d.C1=a.C1,d.C2=a.C2,d.C3=a.C3,d.C4=a.C4,d.C8=a.C8,d.C16=a.C16,d.Ltime=a.time,(d.LFlag=e)&&(d.tmp=a);else if(0==b%2)d.C1R=a.C1,d.C2R=a.C2,d.C3R=a.C3,d.C4R=a.C4,d.C8R=a.C8,d.C16R=a.C16,d.Rtime=a.time,d.RFlag=e,d.C3&&d.C3R?this.newsList.appendChild(l.toDom(k(o,d))):d.C3?this.newsList.appendChild(l.toDom(k(q,d.tmp))):d.C3R&&this.newsList.appendChild(l.toDom(k(q,a))),d={}}))}else if(5<b.length&&16>=b.length){for(i=0;i<16-b.length;i++)b.push({});
b.forEach(f.hitch(this,function(a,b){var e=!1;a&&(e=!0);a.C1=a.C1||a.C2;a.C2=a.C2||"";a.C3=a.C3||"";a.C4=a.C4||"";a.C8=a.C8||"";a.C16=a.C16||"";a.C19=a.C19||"";var m=a.C16;m?(a.C16=!0==c.isToday(a.C16)?c.formatTime(m):c.formatDate(m),a.time=c.formatFullDate(m)):a.time="";a.C19=0<a.C19?"font_red_ex font_14":"font_gray font_14";if(0==b%2)d.C1=a.C1,d.C2=a.C2||"",d.C3=a.C3||"",d.C4=a.C4||"",d.C8=a.C8||"",d.C16=a.C16||"",d.Ltime=a.time,d.C19L=a.C19||"",e&&(d.tmp=a);else if(1==b%2)d.C1R=a.C1,d.C2R=a.C2||
"",d.C3R=a.C3||"",d.C4R=a.C4||"",d.C8R=a.C8||"",d.C16R=a.C16||"",d.Rtime=a.time,d.C19R=a.C19||"",d.C3&&d.C3R?this.newsList.appendChild(l.toDom(k(n,d))):d.C3?this.newsList.appendChild(l.toDom(k(r,d.tmp))):d.C3R&&this.newsList.appendChild(l.toDom(k(r,a))),d={}}))}e&&p("[data-news-id$='"+e+"']").closest("li").addClass("text_title_onthis");this.display_first&&(b=p("ul.con_list li a")[0])&&s.emit(b,"click",{bubbles:!0,cancelable:!0})},_listItemClick:function(c){var c=c.target,e=c.dataset,d=e.author,a=
e.time;if(d||a){var v=window.reader.read(e.newsFile);p("a.onthis_link").removeClass("onthis_link");p(c).closest("li a").addClass("onthis_link");this.detailPane.innerHTML="";this.detailTitle.innerHTML="";this.detailInfo.innerHTML="";d=e.author;a=e.time;if(b.byId("detail-pane-wrap"))b.byId("xin_wen_title").className="text_title font_gray_6 font_16",b.byId("text_share_pane").className="text_share";this.detailTitle.innerHTML=c.innerHTML;this.detailInfo&&(this.detailInfo.innerHTML=a+"<span class='sp-span'></span>\u6765\u6e90\uff1a"+
d);v.then(f.hitch(this,function(a){this.detailPane.innerHTML=a}))}},clearList:function(){this.domNode.innerHTML=""},destroy:function(){this.store&&this.store.close&&this.store.close();this.inherited(arguments)}})})},"url:news/marketAttention/templates/newsList.html":'<ul class="con_list" data-dojo-attach-point="newsList" data-dojo-attach-event="onclick:_listItemClick"></ul>',"url:news/marketAttention/templates/listItemDtl_top.html":'<li style="height:32px;" class="ecllip">\r\n\t<a href="a.html#<%=C1%>" target="news_iframe" class="font_blue_ex font_20" data-author="<%=C8%>" data-time="<%=time%>" data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>\r\n</li>',
"url:news/marketAttention/templates/listItemDtl_left.html":'<li>\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="font_gray font_14" data-author="<%=C8%>" data-time="<%=Ltime%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>&nbsp;|<a href="a.html#<%=C1R%>" target="news_iframe"   class="font_gray font_14" data-author="<%=C8R%>" data-time="<%=Rtime%>"  data-news-file="<%=C4R%>" data-news-id="<%=C1R%>"><%=C3R%></a>\r\n</li>',"url:news/marketAttention/templates/listItemDtl_right.html":'<li class="list_style">\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="<%=C19L%>" data-author="<%=C8%>" data-time="<%=Ltime%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>&nbsp;|<a href="a.html#<%=C1R%>" target="news_iframe"   class="<%=C19R%>" data-author="<%=C8R%>" data-time="<%=Rtime%>"  data-news-file="<%=C4R%>" data-news-id="<%=C1R%>"><%=C3R%></a>\r\n</li>',
"url:news/marketAttention/templates/listItemDtl_left_single.html":'<li>\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="font_gray font_14" data-author="<%=C8%>" data-time="<%=time%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>\r\n</li>',"url:news/marketAttention/templates/listItemDtl_right_single.html":'<li class="list_style">\r\n\t<a href="a.html#<%=C1%>" target="news_iframe"   class="<%=C19%>" data-author="<%=C8%>" data-time="<%=time%>"  data-news-file="<%=C4%>" data-news-id="<%=C1%>"><%=C3%></a>\r\n</li>',
"news/marketAttention/MicroTemplating":function(){define("news/marketAttention/MicroTemplating",[],function(){var c={};return function f(b,h){var e=!/\W/.test(b)?c[b]=c[b]||f(document.getElementById(b).innerHTML):new Function("obj","var p=[],print=function(){p.push.apply(p,arguments);};with(obj){p.push('"+b.replace(/[\r\t\n]/g," ").split("<%").join("\t").replace(/((^|%>)[^\t]*)'/g,"$1\r").replace(/\t=(.*?)%>/g,"',$1,'").split("\t").join("');").split("%>").join("p.push('").split("\r").join("\\'")+
"');}return p.join('');");return h?e(h):e}})},"news/marketAttention/newsStore":function(){define("news/marketAttention/newsStore",["dojo/_base/lang","dojo/_base/declare","dojox/store/WebSocket"],function(c,g,f){return g("news.zongheping.Store",[f],{constructor:function(b){g.safeMixin(this,b);this.inherited(arguments)},socketCfg:{},total_nums:0,parameter:{},parameter2:"",current_item_cnt:0,idProperty:"id",getProperty:function(b){return this[b]},setProperty:function(b,f){1==arguments.length&&c.isObject(b)?
c.mixin(this,b):2==arguments.length&&(this[b]=f)},query:function(b,f){if("100000"==this.parameter.menuid){for(var e=this.parameter2.split(";"),j=[],g=0;g<e.length;g++)j[g]=(window.external.base64encode||btoa)(e[g]);this.socketCfg.parameter=j.join(",")}else this.socketCfg.parameter=(window.external.base64encode||btoa)(JSON.stringify(this.parameter));[].push.call(arguments,this.socketCfg);e=this.inherited(arguments);1==this.socketCfg.response_times&&e.then(c.hitch(this,function(){this.cancel(this.req_seq)}));
e.total=e.then(function(b){return b?b.total_num:-1});return e},progress:function(b){return this.convert(b)},convert:function(b){var b=b.result,c,e,f=[],g=this,o=this.parameter;2==b.head.length&&"title"==b.head[0]&&"tablelist"==b.head[1]?(c=b.datas[0][1].head,e=b.datas[0][1].datas):(c=b.head,e=b.datas);e.forEach(function(b){var e={};c.forEach(function(c,f){e[c]=b[f]});g.put(e);f.push(e)});if(b.datas[1])try{var n=b.datas[1][1].datas[0];f.total_num=!n||-1==n[0]||0==n[0]?0:n[0]}catch(q){}this.current_item_cnt=
o.skip+f.length;return f}})})}}});
define("news/marketAttention/src","./util,dijit/registry,dojo/io-query,dojo/dom,dojo/_base/lang,dojo/on,./marketNewsList,dojox/store/MultiResultStore,./newsStore,dojox/websocket/WebsocketFileReader,./MicroTemplating,dojo/aspect,dojo/dom-geometry,dojo/dom-style,dojo/dom-construct,dojo/query,dojo/NodeList-traverse,dojo/NodeList-manipulate,dojo/domReady!".split(","),function(c,g,f,b,h,e,j,t,o,n,q,r,u,k,l,s){return function(){function c(){b.byId("bg").style.display="none";b.byId("tc").style.display="none";
b.byId("xin_wen_detail").innerHTML=""}function f(){var a=document,c=a.getElementsByClassName("list_pages_box")[0],d=b.byId("tc_index_text");if(c)c.style.height=a.body.offsetHeight-52+"px",a.body.style.overflowY="hidden";if(d)c=getComputedStyle(b.byId("tc")).height,a=/\%/.test(c)?a.body.offsetHeight*parseInt(c)/100:c,d.style.height=a-42+"px"}function g(){var a=b.byId("list_box_set0"),c=b.byId("list_box_set1");if(a&&c){var d=getComputedStyle(a).height,e=getComputedStyle(c).height,d=Math.floor(parseInt(d)/
25),e=Math.floor(parseInt(e)/25);0==d||0==e||(k.set(a,"height",25*d+"px"),k.set(c,"height",25*e+"px"))}}var l={service:"rpc",so:"jso-ui-zhpnews.jar","function":"gw.sh.func.SearchByEqualsRequest",paraencode:"base64",response_times:1,cache_timeout:10,response_mode:1,request_timeout:10},d=window.reader=new n;(function(){var b={focus1:{code:"00000003000T0000",fids:"C1,C2,C3,C4,C8,C16",dcategory:"1-19",sort:"C16:-1",skip:"0",amount:"5"},focus2:{code:"00000003000T0001",fids:"C1,C2,C3,C4,C8,C16",dcategory:"1-19",
sort:"C16:-1",skip:"0",amount:"5"},focus3:{code:"00000003000T0002",fids:"C1,C2,C3,C4,C8,C16,C19",dcategory:"1-19",sort:"C16:-1",skip:"0",amount:"16"}};["focus1","focus2","focus3"].forEach(function(c,d){var e=new o({socketCfg:l,parameter:b[c]});0==d&&(a=e);new j({store:e,id:"list_box_set"+d,detailPane:"xin_wen_detail"},"home-"+c)})})();var a;r.after(a,"convert",function(a){if(a){var a=a[0],c=b.byId("xin_wen_title");c.innerHTML="";c.innerHTML=a.C3;c.dataset.newsFile=a.C4;var e=a.time,f=a.C8;c.src="a.html/"+
a.C1;b.byId("xin_wen_info").innerHTML=e+"<span class='sp-span'></span> \u6765\u6e90\uff1a"+f;if(b.byId("detail-pane-wrap"))b.byId("xin_wen_detail").className="text_title font_gray_6 font_16",b.byId("text_share_pane").className="text_share";d.read(a.C4).then(h.hitch(this,function(a){b.byId("xin_wen_detail").innerHTML="";b.byId("xin_wen_detail").innerHTML=a}));return a}});e(document.body,"keydown",function(a){27==a.keyCode&&c()});e(document.body,"click",function(a){a=a.target;s(a).closest(".up_down");
var d=s(a);d.length&&d[0].dataset.newsFile?(b.byId("tc_focus_text"),b.byId("hideButDiv")):(a.classList.contains("close")||"bg"==a.id)&&c();if(a.dataset.fontSize)b.byId("xin_wen_detail").style.fontSize=a.dataset.fontSize+"px"});g();f();e(window,"resize",g);e(window,"resize",f);e(window,"load",g);e(window,"load",f)}});