/*
	Copyright (c) 2012-2013,   To get sources and documentation, please visit:

		http://dms.gw.com.cn
*/

//>>built
require({cache:{"dojo/router":function(){define(["./router/RouterBase"],function(e){return new e({})})},"dojo/router/RouterBase":function(){define(["dojo/_base/declare","dojo/hash","dojo/topic"],function(e,k,l){function m(a,d,f){var b,h,c;b=this.callbackQueue;c=h=!1;a={stopImmediatePropagation:function(){h=!0},preventDefault:function(){c=!0},oldPath:d,newPath:f,params:a};for(d=0,f=b.length;d<f;++d)if(!h)b[d](a);return!c}var j;j=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^\s\s*/,
"").replace(/\s\s*$/,"")};return e(null,{_routes:null,_routeIndex:null,_started:!1,_currentPath:"",idMatch:/:(\w[\w\d]*)/g,idReplacement:"([^\\/]+)",globMatch:/\*(\w[\w\d]*)/,globReplacement:"(.+)",constructor:function(a){this._routes=[];this._routeIndex={};for(var d in a)a.hasOwnProperty(d)&&(this[d]=a[d])},register:function(a,d){return this._registerRoute(a,d)},registerBefore:function(a,d){return this._registerRoute(a,d,!0)},go:function(a,d){var f,a=j(a);(f=this._handlePathChange(a))&&k(a,d);return f},
startup:function(){if(!this._started){var a=this;this._started=!0;this._handlePathChange(k());l.subscribe("/dojo/hashchange",function(){a._handlePathChange.apply(a,arguments)})}},_handlePathChange:function(a){var d,f,b,h,c,n,g,i,e=this._routes,o=this._currentPath;if(!this._started||a===o)return f;f=!0;for(d=0,b=e.length;d<b;++d)if(c=e[d],n=c.route.exec(a)){if(c.parameterNames){g=c.parameterNames;i={};for(f=0,h=g.length;f<h;++f)i[g[f]]=n[f+1]}else i=n.slice(1);f=c.fire(i,o,a)}if(f)this._currentPath=
a;return f},_convertRouteToRegExp:function(a){a=a.replace(this.idMatch,this.idReplacement);a=a.replace(this.globMatch,this.globReplacement);return RegExp("^"+a+"$")},_getParameterNames:function(a){var d=this.idMatch,f=this.globMatch,b=[],h;for(d.lastIndex=0;null!==(h=d.exec(a));)b.push(h[1]);null!==(h=f.exec(a))&&b.push(h[1]);return 0<b.length?b:null},_indexRoutes:function(){var a,d,f,b,h=this._routes;b=this._routeIndex={};for(a=0,d=h.length;a<d;++a)f=h[a],b[f.route]=a},_registerRoute:function(a,
d,f){var b,h,c,e,g,i=this,j=this._routes,o=this._routeIndex;b=this._routeIndex[a];(h="undefined"!==typeof b)&&(c=j[b]);c||(c={route:a,callbackQueue:[],fire:m});e=c.callbackQueue;if("string"==typeof a)c.parameterNames=this._getParameterNames(a),c.route=this._convertRouteToRegExp(a);f?e.unshift(d):e.push(d);if(!h)b=j.length,o[a]=b,j.push(c);g=!1;return{remove:function(){var a,p;if(!g){for(a=0,p=e.length;a<p;++a)e[a]===d&&e.splice(a,1);0===e.length&&(j.splice(b,1),i._indexRoutes());g=!0}},register:function(b,
p){return i.register(a,b,p)}}}})})},"dojo/hash":function(){define("./_base/kernel,require,./_base/config,./_base/connect,./_base/lang,./ready,./sniff".split(","),function(e,k,l,m,j,a){function d(a,b){var d=a.indexOf(b);return 0<=d?a.substring(d+1):""}function f(){return d(location.href,"#")}function b(){m.publish("/dojo/hashchange",[f()])}function h(){f()!==g&&(g=f(),b())}function c(a){if(i)if(i.isTransitioning())setTimeout(j.hitch(null,c,a),o);else{var b=i.iframe.location.href,d=b.indexOf("?");i.iframe.location.replace(b.substring(0,
d)+"?"+a)}else location.replace("#"+a),!t&&h()}function n(){function a(){g=f();h=s?g:d(r.href,"?");c=!1;i=null}var p=document.createElement("iframe"),u=l.dojoBlankHtmlUrl||k.toUrl("./resources/blank.html");l.useXDomain&&!l.dojoBlankHtmlUrl&&console.warn("dojo.hash: When using cross-domain Dojo builds, please save dojo/resources/blank.html to your domain and set djConfig.dojoBlankHtmlUrl to the path on your domain to blank.html");p.id="dojo-hash-iframe";p.src=u+"?"+f();p.style.display="none";document.body.appendChild(p);
this.iframe=e.global["dojo-hash-iframe"];var h,c,i,m,s,r=this.iframe.location;this.isTransitioning=function(){return c};this.pollLocation=function(){if(!s)try{var e=d(r.href,"?");if(document.title!=m)m=this.iframe.document.title=document.title}catch(l){s=!0,console.error("dojo.hash: Error adding history entry. Server unreachable.")}var q=f();if(c&&g===q)if(s||e===i)a(),b();else{setTimeout(j.hitch(this,this.pollLocation),0);return}else if(!(g===q&&(s||h===e))){if(g!==q){g=q;c=!0;i=q;p.src=u+"?"+i;
s=!1;setTimeout(j.hitch(this,this.pollLocation),0);return}if(!s)location.href="#"+r.search.substring(1),a(),b()}setTimeout(j.hitch(this,this.pollLocation),o)};a();setTimeout(j.hitch(this,this.pollLocation),o)}e.hash=function(a,b){if(!arguments.length)return f();"#"==a.charAt(0)&&(a=a.substring(1));b?c(a):location.href="#"+a;return a};var g,i,t,o=l.hashPollFrequency||100;a(function(){"onhashchange"in e.global?t=m.connect(e.global,"onhashchange",b):document.addEventListener?(g=f(),setInterval(h,o)):
document.attachEvent&&(i=new n)});return e.hash})},"commodity/specialTopic/public/js/_publicParam":function(){define(["dojo/_base/declare"],function(e){return e("commodity.specialTopic.public.js._publicParam",null,{constructor:function(){this.url="http://10.15.107.157:8080/specialTopic/";this.indexUrl=/^http:\/\/10.15.107.157/}})})},"commodity/specialTopic/public/view/dialog":function(){define("dojo/_base/declare,dijit/_WidgetBase,dijit/_TemplatedMixin,dijit/_WidgetsInTemplateMixin,dijit/layout/_ContentPaneResizeMixin,dojo/dom,dijit/registry,dojo/text!./dialog.html".split(","),
function(e,k,l,m,j,a,d,f){return e("commodity.specialTopic.public.view.dialog",[k,l,m,j],{templateString:f,postMixInProperties:function(){},postCreate:function(){},showDialog:function(a){this.tipInfo.innerHTML=a;this.dialogConfirm.show()}})})},"url:commodity/specialTopic/public/view/dialog.html":'<div data-dojo-attach-point="containerNode" class="spacer">\r\n\t<div data-dojo-id="dialogConfirm" data-dojo-attach-point="dialogConfirm" data-dojo-type="dijit/Dialog"  data-dojo-props="title:\'\u63d0\u793a\u4fe1\u606f\'" style="display:none;width:400px;">\r\n\t\t<div class="vbox" style="height: 100px">\r\n\t\t\t<div data-dojo-attach-point="tipInfo" class="spacerx" style="text-align: center; line-height:50px;"></div>\r\n\t\t\t<div class="spacerx" style="text-align: center; line-height:50px;">\r\n\t\t\t\t<button data-dojo-type="dijit/form/Button" type="button" onclick="dialogConfirm.onCancel()">\u5173\u95ed</button>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>'}});
define("commodity/detailGrid/src","dijit/_WidgetBase,dojo/parser,dojo/store/Memory,dojo/request,dojox/slickgrid/slickgrid,dojo/dom,dojo/on,dojo/router,dijit/registry,dojo/dom-attr,commodity/specialTopic/public/js/_publicParam,dojo/request/script,commodity/specialTopic/public/view/dialog".split(","),function(e,k,l,m,j,a,d,f,b,h,c,n,g){var i=new c;return function(){function d(a,f,e){var c,h=new l({data:[]});columns=[{id:"date",name:"\u65f6\u95f4",field:"date",width:120,sortable:!0}];for(var g=param.desc.split(","),
o=param.id.split(","),r=0;r<g.length;r++){var k={};k.id="price"+r;k.field="price"+(r+1);k.name=g[r];k.width=110;columns.push(k)}options=8<g.length?{}:{forceFitColumns:!0};b.remove("tableData");c=new j({store:h,columns:columns,options:options},"tableData");c.startup();c.on("click",function(a,b){for(var d=0;d<g.length;d++)if(b.cell==d+1){var f=encodeURIComponent("url=comm/cdb&desc="+g[d]+"&from="+n+"&to="+q+"&unit="+param.unit+"&period="+param.period+"&id="+o[d]+"&pdesc="+param.pdesc);window.location.href=
"../trendMagnify/index.html?params="+f}});var h=i.url+param.url,n,q;e?(n=a,q=f):(n=param.from,q=param.to);m(h,{jsonp:"callback",query:"commTag="+param.id+"&startDate="+n+"&endDate="+q+"&period="+param.period}).then(function(a){c.set("store",new l({data:a}));c.refresh(a)},function(){})}function f(a){var c;"y"==a?(a=b.byId("yFrom").get("value")+"",c=b.byId("yTo").get("value")+""):(a=b.byId("dmFrom").get("displayedValue"),c=b.byId("dmTo").get("displayedValue"));if(""!=a&&""!=c){a=a.replace(RegExp("-",
"g"),"");c=c.replace(RegExp("-","g"),"");if(a>c)return(new g).showDialog("\u5f00\u59cb\u65f6\u95f4\u5e94\u5c0f\u4e8e\u7ed3\u675f\u65f6\u95f4"),!1;d(a,c,!0)}}var e=(new c).indexUrl;m.register(e,n);k.parse().then(function(){b.byId("dmFrom").on("change",function(){f("dm")});b.byId("dmTo").on("change",function(){f("dm")});b.byId("yFrom").on("change",function(){f("y")});b.byId("yTo").on("change",function(){f("y")});for(var c=(new Date).getFullYear(),e=c;1970<=e;e--){var g=e+"";b.byId("yFrom").addOption({label:g,
value:g});b.byId("yTo").addOption({label:g,value:g})}e=param.from+"";g=param.to+"";4<e.length&&(e=e.substring(0,4)+"-"+e.substring(4,6)+"-"+e.substring(6),g=g.substring(0,4)+"-"+g.substring(4,6)+"-"+g.substring(6));var i=param.period,c={m:{pattern:"yyyy-MM",start:c+"-01",end:c+"-12"},d:{pattern:"yyyy-MM-dd",start:c+"-01-01",end:c+"-12-31"}};"m"==i||"d"==i?(b.byId("dmFrom").constraints.datePattern=c[i].pattern,b.byId("dmTo").constraints.datePattern=c[i].pattern,h.set("dmFrom","value",e),h.set("dmTo",
"value",g),a.byId("dayMonth").style.display="block",a.byId("year").style.display="none"):(a.byId("dayMonth").style.display="none",a.byId("year").style.display="block",b.byId("yFrom").set("value",e),b.byId("yTo").set("value",g));e=e.replace(RegExp("-","g"),"");g=g.replace(RegExp("-","g"),"");a.byId("titleName").innerHTML=param.titleNm;a.byId("unit").innerHTML=param.unit;a.byId("period").innerHTML=param.pdesc;d(e,g,!1)})}});