/*
	Copyright (c) 2012-2013,   To get sources and documentation, please visit:

		http://dms.gw.com.cn
*/

//>>built
require({cache:{"dojox/customfig/themes/blackTheme":function(){define("dojox/customfig/themes/blackTheme",["dojo/_base/declare"],function(k){return k("dojox.customfig.themes.blackTheme",null,{com_de_opt:{label:"#FFFFFF",font:"12px Arial normal",stroke:"#C00000",background:"#000000",backgroundGrid:{type:"solid",color:"#C00000",height:25,lineHeight:1},xAxisLabel:{color:"#FFFFFF",background:"#FFFFFF"},yAxisLabel:{color:"#FFFFFF",background:"#FFFFFF"},xLabelsInterval:30,fixedNum:0,prepareDistance:0},
sharingPlans:{timetrendFilledColors:["#131313","#0073ff"],timetrendFillAlpha:0.7,timetrend:["#F59F56","red","yellow"],baseValueStyle:{color:"#FFFF52",background:"#FFFFFF"},yUpLabel:{color:"#FF0000",background:"#FFFFFF"},yDownLabel:{color:"#1FA42C",background:"#FFFFFF"}},kline:{candleStyle:[{upStyle:{candle:{type:"stroke",color:"#CC4642"}},downStyle:{candle:{type:"fill",color:"#00ff00"}}},{upStyle:{candle:{type:"stroke",color:"#5F9EA0"}},downStyle:{candle:{type:"fill",color:"#5F9EA0"}}},{upStyle:{candle:{type:"stroke",
color:"#C67413"}},downStyle:{candle:{type:"fill",color:"#C67413"}}},{upStyle:{candle:{type:"stroke",color:"#C67488"}},downStyle:{candle:{type:"fill",color:"#C67488"}}},{upStyle:{candle:{type:"stroke",color:"#C93413"}},downStyle:{candle:{type:"fill",color:"#C93413"}}}],maximumArrow:{color:"#c8c8c8"},minimumArrow:{color:"#c8c8c8"},yAxisUpLabel:{color:"#6f6060"},yAxisLowLabel:{color:"#30f060"}},ma:{ma:["green","red","blue"]},edx:{edx:{color:"#ff9516",yTxtColor:"#ff9516",txtColor:"#ffffff",txtBgColor:"#ff9516"}},
kdj:{kdj:["green","red","blue"]},vol:{volumnStyle:{upColor:"#ff0000",downColor:"#00ff00",color:"yellow"}},macd:{macdStyle:{diff:{color:"#9B9B9B"},dea:{color:"#BC6111"},macd:{upcolor:"#ff0000",downcolor:"#00ff00"}}},crosshair:{tooltip:{content:{background:"#000000",width:"auto",height:"auto",border:"#FFFFFF solid 1px","text-align":"center",position:"absolute",opacity:0.7,"z-index":2,"line-height":1.6,padding:"4px","font-size":"12px",color:"#FFFFFF"},time:{"font-weight":"normal",color:"#ffc13b"}},vLine:{width:"1px",
background:"#6B6B6B",position:"absolute","z-index":2},hLine:{height:"1px",background:"#6B6B6B",position:"absolute","z-index":2},vLabel:{border:"1px solid #C00000",color:"#C0C0C0","text-align":"center","z-index":2,position:"absolute",background:"#000080","margin-left":"3px"},hLabel:{border:"1px solid #C00000",color:"#C0C0C0","text-align":"center","z-index":2,position:"absolute",width:"auto",background:"#000080"}}})})},"bond/currencyMarket/public/ContextMenu":function(){define("dojo/on,dojo/mouse,dojo/keys,dojo/_base/declare,dojox/customfig/actions/CustomfigAction,dojo/_base/lang,dojo/_base/array,dojo/dom,dojo/dom-geometry,dojox/customfig/utils".split(","),
function(k,c,h,f,e,a,b){return f("bond.bondMarket.public.ContextMenu",e,{constructor:function(b,a){this.plot=b;this.addMenu(a.domId);this.klinekline=a.klineKline;this._handles=[];this.connect();this.plot.canvas.tabIndex=1;this.intervalSelection=a.intervalSelection;this.dayLine=a.dayLine},curcode:"",_disconnectHandles:function(){b.forEach(this._handles,function(b){b.remove()});this._handles=[]},addMenu:function(b){var c=this;require(["dijit/Menu","dijit/MenuItem","dijit/MenuSeparator","dijit/PopupMenuItem"],
function(e,g,d,p){var d=new e({targetNodeIds:[b]}),h=new e({parentMenu:d});h.addChild(new g({label:"\u65e5\u7ebf",onClick:a.hitch(c,c.switchTimeType,1,"\u65e5\u7ebf")}));d.addChild(new p({label:"\u65f6\u95f4\u9891\u5ea6",popup:h}));e=new e({parentMenu:d});e.addChild(new g({label:"\u6700\u8fd1\u4e00\u4e2a\u6708",onClick:a.hitch(c,c.switchInterval,"1M","\u6700\u8fd1\u4e00\u4e2a\u6708")}));e.addChild(new g({label:"\u6700\u8fd1\u4e09\u4e2a\u6708",onClick:a.hitch(c,c.switchInterval,"3M","\u6700\u8fd1\u4e09\u4e2a\u6708")}));
e.addChild(new g({label:"\u6700\u8fd16\u4e2a\u6708",onClick:a.hitch(c,c.switchInterval,"6M","\u6700\u8fd16\u4e2a\u6708")}));e.addChild(new g({label:"\u5e74\u521d\u81f3\u4eca",onClick:a.hitch(c,c.switchInterval,"0M","\u5e74\u521d\u81f3\u4eca")}));e.addChild(new g({label:"\u6700\u8fd11\u5e74",onClick:a.hitch(c,c.switchInterval,"1Y","\u6700\u8fd11\u5e74")}));e.addChild(new g({label:"\u6700\u8fd12\u5e74",onClick:a.hitch(c,c.switchInterval,"2Y","\u6700\u8fd12\u5e74")}));e.addChild(new g({label:"\u6700\u8fd13\u5e74",
onClick:a.hitch(c,c.switchInterval,"3Y","\u6700\u8fd13\u5e74")}));e.addChild(new g({label:"\u4e0a\u5e02\u81f3\u4eca",onClick:a.hitch(c,c.switchInterval,"maxY","\u4e0a\u5e02\u81f3\u4eca")}));d.addChild(new p({label:"\u533a\u95f4\u9009\u62e9",popup:e}));d.addChild(new g({label:"\u590d\u5236\u6570\u636e",parentMenu:d,onClick:a.hitch(c,c.reSaveData)}));d.startup()})},switchTimeType:function(b,c){this.dayLine.set("value",c)},switchInterval:function(b,c){this.intervalSelection.set("value",c)},reSaveData:function(){this.plot.saveAsExcel()}})})},
"bond/currencyMarket/public/marketGrid":function(){define("dojo/_base/declare,dojo/json,dojo/parser,dojox/slickgrid/formatters,bond/currencyMarket/public/bondMarketFormatter,bond/currencyMarket/public/util,dojox/store/GridWSStore,dojox/store/WebSocket,dojox/slickgrid/slickgrid,dojox/slickgrid/quotegrid,dojo/_base/array,dojo/aspect,dojo/_base/lang".split(","),function(k,c,h,f,e,a,b,i,n,r,g,d,p){var j=new e;return k([],{columns:"",options:"",field:"",dataType:"",gridId:"",bondCode:"",jsoUrl:"",constructor:function(d){p.mixin(this,
d);"getBondNews"===this.dataType?this.getBondNews():"repo"===this.dataType&&this.getRepoDivisionData()},getRepoDivisionData:function(){var d=new b({idProperty:"time"});d.formatter="container_grid02"==this.gridId?j.division:j.divisionA;this.createSlickgrid(d,{service:"did",did:this.did,where:"obj="+bondCode.bondCode,response_times:-1})},getBondNews:function(){a.getBeforeDate(150).replace("-","").replace("-","");a.DateToFullDateTimeString(new Date).replace("-","").replace("-","");var d=new b,c={service:"rpc",
so:"jso-ui-zhpnews.jar","function":"gw.sh.func.SearchNewsFromSolrRequest",paraencode:"base64",parameter:btoa('{"fids":"C1,C2,C3,C4,C16,C31,CC98,CC99,C8","dcategory":"1","sort":"C16:-1","skip":0,"amount":50,"menuid":"000001007"}'),response_times:1,cache_timeout:0,response_mode:0,request_timeout:-1};this.createSlickgrid(d,c)},createSlickgrid:function(b,c){var a=new n({store:b,columns:this.columns,options:this.options},this.gridId);if("getBondNews"===this.dataType)a.queryLimit=c;else if(whetherShowData)a.queryLimit=
c;if("repo"===this.dataType){d.after(b,"put",function(){a.updateRowCount();a.scrollTo(a.getCanvasHeight());a.viewportHasVScroll||a.refresh()});var p=d.after(a,"refresh",function(){p.remove();a.scrollTo(a.getCanvasHeight())})}"getBondNews"===this.dataType&&(d.after(b,"put",function(){a.refresh()}),a.on("dblclick",function(d,s){var l=a.getDataItem(s.row),l="dzh://navigate?'root://news/details/index.html#"+l.C1;window.location=l+"#DZHPOPUP(256,132,854,504)#"}));a.startup()}})})},"bond/currencyMarket/public/bondMarketFormatter":function(){define(["dojo/_base/declare",
"dojo/json","dojox/store/WebSocket","bond/currencyMarket/public/util"],function(k,c,h,f){var e="",a="",b=0,i=0,n=function(d){for(var b in d)d[b]=r(b,d[b]);d.BTime=d.time+"--"+i;i+=i;if(d.time){var c=d.time.toString();b=c.substring(8,10)+":"+c.substring(10,12);c=":"+c.substring(12,14);d.time=b+c}return d},r=function(d,b){return d in{"new":"",matuyld:"",updn:"",open:"",lastclose:"",high:"",low:"",pro_pri:"",pnratio:"",pri_rev:"",buyprice1:"",sellprice5:"",volratio:"",avgprice:"",price:""}?g(b,4)+"":
d in{volume:"",nowvol:"",amount:"",industry:"",inner:"",outter:"",tickcount:"",allvalue:"",floatvalue:"",wantdiff:"",time:""}?Math.round(b):d in{updnratio:"",exchange:"",updnspeed:"",hilowratio:"",wantratio:""}?g(100*b,2)+"":d in{clearPrice:"",dirtyPrice:"",accruedInterest:"",terToMaturity:"",yield:"",durationMod:"",convexity:"",dutation:"",convexityDis:"",convexityInt:"",dataSourcesType:"",updnclean:"",updnratioclean:"",priceD:"",yieldD:"",repoPrice:""}?g(b,4)+"":b},g=function(d,b){for(var c=b,a=
1;0<b;a*=10,b--);a=Math.round(d*a)/a+"";if(0<a.indexOf(".")){var e=a.substring(a.indexOf(".")+1).length;if(e<c)for(var g=0;g<c-e;g++)a+="0"}else{a+=".";for(g=0;g<c;g++)a+="0"}return a};return k([],{historyClose:function(d){var d=d[0],b;for(b in d)d[b]=r(b,d[b]);if(d.time&&0!=d.time){b=new Date(parseFloat(d.time)+"000"-288E5);var a;a=""+((10>b.getHours()?"0":"")+b.getHours()+":");a+=(10>b.getMinutes()?"0":"")+b.getMinutes()+":";a+=(10>b.getSeconds()?"0":"")+b.getSeconds();d.time=a;a=""+(b.getFullYear()+
"-");a+=(10>b.getMonth()?"0":"")+b.getMonth()+"-";a+=b.getDate()}d.hDate=a;d.buyprice&&d.sellprice&&(d.margin=d.buyprice-d.sellprice);return d},countDiffr:function(d){d=d[0];d.time=d.buytime;return d},division:function(d){d=d[0];d=n(d,e);0<d.time.indexOf(":")&&(e=d.time);return d},divisionA:function(d){d=d[0];d=n(d,a);0<d.time.indexOf(":")&&(a=d.time);return d},historyChases:function(d){var d=d[0],b;for(b in d)"null"===d[b]&&(d[b]="0"),d[b]=r(b,d[b]);return d},relatedToBond:function(d){var d=d[0],
b;for(b in d)d[b]=r(b,d[b]);if(d["new"]&&"0.00"===d["new"])return null;d.obj&&(d.co=d.obj);return d},bondNews:function(d){d=d[0];d.C16>=b&&(b=d.C16);d.newsKey=d.C1+"-"+d.C2;var a=f.getOneMonthAgoDate("1"),a=a.replace("-","").replace("-","")+"000000",c="";d.C16>a?c=d.C16.substr(8,2)+":"+d.C16.substr(10,2)+":"+d.C16.substr(12,2):d.C16<a&&(c=d.C16.substr(0,4)+"-"+d.C16.substr(4,2)+"-"+d.C16.substr(6,2));d.C16=c;return d},realTimeMarket:function(d){var d=d[0],b=d.newclean-d.lastcloseclean,b=r("updnclean",
b);d.updn=b;return d},basicInformation:function(d){var d=d[0],b;for(b in d)d[b]=r(b,d[b]);return d},repoRealTimeMarket:function(b){var b=b[0],a=parseFloat(b["new"])-parseFloat(b.lastclose),a=r("updnclean",a);b.updn=a;a=100*((parseFloat(b["new"])-parseFloat(b.lastclose))/parseFloat(b.lastclose));a=r("updnratioclean",a);b.updnratio=a+"%";return b}})})},"bond/currencyMarket/public/util":function(){define(["dojo/date/locale"],function(){var k=function(c,h){for(var f=h,e=1;0<h;e*=10,h--);e=Math.round(c*
e)/e+"";if(0<e.indexOf(".")){var a=e.substring(e.indexOf(".")+1).length;if(a<f)for(var b=0;b<f-a;b++)e+="0"}else if(0!=f){e+=".";for(b=0;b<f;b++)e+="0"}return e};return{getSelectDay:function(c,h){var f=new Date;f.setDate(f.getDate()+(c||0));var e=f.getFullYear(),a=f.getMonth()+1,f=f.getDate();10>a&&(a="0"+a);10>f&&(f="0"+f);var b=e+"-"+a+"-"+f;2==arguments.length&&(b=2==h?e+""+a+f+"000000":b);return b},getKineStarTime:function(c){var h,f,e=Array.prototype.slice,a=Array.prototype.splice,b=e.call(c);
h=Number(c.slice(4,6));c=Number(c.slice(0,4));f=Math.floor(0.5);h-=6;1>h&&(h=12+h,f++);c-=f;10>h&&(h="0"+h);c&&(strs=e.call(""+c),a.call(b,0,4),b=strs.concat(b));h&&b.splice(4,2,""+h);return b.join("")},getOneMonthAgoDate:function(c){var h=new Date,f=h.getFullYear(),e=h.getMonth()+1,h=h.getDate(),a=1<e?e-1:12,b=12==a?f-1:f,i=0,i=4===a||6===a||9===a||11===a?31>h?h:30:3===e?29>h?h:28:h;9>=e&&(e="0"+e);10>h&&(h="0"+h);9>=a&&(a="0"+a);10>i&&(i="0"+i);var n="";"1"==c?n=f+"-"+e+"-"+h:"0"==c?n=b+"-"+a+"-"+
i:"2"==c?n=""+f+e+h:"3"==c&&(n=""+b+a+i);return n},formatFullDate:function(c){return this._checkDate(c)?(c=this._getDateArray(c),c[1]+"\u5e74"+c[2]+"\u6708"+c[3]+"\u65e5 "+c[4]+":"+c[5]):""},formatDate:function(c){return this._checkDate(c)?(c=this._getDateArray(c),c[2]+"/"+c[3]):""},formatTime:function(c){return this._checkDate(c)?(c=this._getDateArray(c),c[4]+":"+c[5]+":"+c[6]):""},_getDateArray:function(c){return/(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(c)},_checkDate:function(c){return"string"==
typeof c?!0:!1},getOneMonthDate:function(){var c=new Date,h=c.getFullYear(),f=c.getMonth(),c=c.getDate();(new Date(h,f,c,9,30)).getTime()},getBeforeDate:function(c){return this.DateToFullDateTimeString(new Date((new Date).getTime()-864E5*c))},DateToFullDateTimeString:function(c){var h=c.getFullYear(),f=c.getMonth()+1,e=c.getDate();c.getHours();c.getMinutes();c.getSeconds();9>f&&(f="0"+(f+1));10>e&&(e="0"+e);return h+"-"+f+"-"+e},handleRawData:function(c,h){return c in{amount:""}?k(h,4)+"":c in{vol:""}?
k(h,2)+"":h}}})},"bond/currencyMarket/public/bankRepoLabel":function(){define("dojo/_base/declare,dojo/on,dijit/form/Button,dojo/json,dojo/parser,bond/currencyMarket/public/bondMarketFormatter,dijit/_WidgetBase,dijit/_TemplatedMixin,dijit/_WidgetsInTemplateMixin,dijit/layout/_ContentPaneResizeMixin,dojo/text!./../template/bankRepo.html,dojo/text!./../template/bankRepoLV.html,dojo/text!./../template/bondTiTLe.html,dojo/text!./../template/repoTitle.html,dojox/store/WebSocket,dojox/store/GridWSStore,dojo/_base/array,dojo/aspect,dojo/_base/lang,dojo/string,dojo/dom,bond/currencyMarket/public/util".split(","),
function(k,c,h,f,e,a,b,i,n,r,g,d,p,j,w,o,x,v,t,s,l,A){var B=new a;return k([],{bondCode:"",constructor:function(b){t.mixin(this,b);this.getTitleInfo();this.getRepoData()},getRepoData:function(){var b=this,l=o({}),d={service:"did",where:"obj="+bondCode.bondCode,response_times:-1};if("95"==subMarket.marketType)d.did="100005";else if("96"==subMarket.marketType)d.did="100006";else if("97"==subMarket.marketType)d.did="100004";else if("92"==subMarket.marketType)d.did="100009";l.on("afterconvert",function(l){l=
l.data;l=B.repoRealTimeMarket(l);b.setRealTimeMarket(l)});whetherShowData?l.query(d).then(function(l){(0>l.res_type||0==l.length)&&b.setRealTimeMarket()}):b.setRealTimeMarket()},getTitleInfo:function(){var b=this;if(""==bondShortName.bondName){var l=o({}),d={service:"rpc",so:"javadataproxy.jar","function":"gw/UIMain",paraencode:"base64",parameter:"Z2V0,"+btoa("/bond/market/loadRepoInfo?obj="+bondCode.bondCode),response_times:1,response_mode:0};l.query(d).then(function(l){if(l&&l.res_type&&0>l.res_type)b.setTitleColor();
else if(b.setTitleColor(l[0]),0<l.length)bondShortName.bondName=l[0].shortName})}else b.setTitleColor({shortName:bondShortName.bondName})},setRealTimeMarket:function(b){var a={"new":"-",updn:"-",vol:"-",updnratio:"-",amount:"-",avg:"-",open:"-",high:"-",low:"-",lastclose:"-"};if(b){t.mixin(a,b);if("-"!=a["new"]&&parseFloat(a["new"])>parseFloat(a.lastclose))a["new"]='<span style="color:#FF3D2D;">'+a["new"]+"</span>",a.updn='<span style="color:#FF3D2D;">\u25b2'+a.updn+"</span>",a.updnratio='<span style="color:#FF3D2D;">'+
a.updnratio+"</span>";else if("-"!=a["new"]&&parseFloat(a["new"])<parseFloat(a.lastclose))a["new"]='<span style="color:#1ED81F;">'+a["new"]+"</span>",a.updn='<span style="color:#1ED81F;">\u25bc'+a.updn+"</span>",a.updnratio='<span style="color:#1ED81F;">'+a.updnratio+"</span>";"-"!=a["new"]&&parseFloat(a.open)>parseFloat(a.lastclose)?a.open='<span style="color:#FF3D2D;">'+a.open+"</span>":"-"!=a["new"]&&parseFloat(a.open)<parseFloat(a.lastclose)&&(a.open='<span style="color:#1ED81F;">'+a.open+"</span>");
"-"!=a["new"]&&parseFloat(a.high)>parseFloat(a.lastclose)?a.high='<span style="color:#FF3D2D;">'+a.high+"</span>":"-"!=a["new"]&&parseFloat(a.high)<parseFloat(a.lastclose)&&(a.high='<span style="color:#1ED81F;">'+a.high+"</span>");"-"!=a["new"]&&parseFloat(a.low)>parseFloat(a.lastclose)?a.low='<span style="color:#FF3D2D;">'+a.low+"</span>":"-"!=a["new"]&&parseFloat(a.low)<parseFloat(a.lastclose)&&(a.low='<span style="color:#1ED81F;">'+a.low+"</span>");"-"!=a["new"]&&parseFloat(a.avg)>parseFloat(a.lastclose)?
a.avg='<span style="color:#FF3D2D;">'+a.avg+"</span>":"-"!=a["new"]&&parseFloat(a.avg)<parseFloat(a.lastclose)&&(a.avg='<span style="color:#1ED81F;">'+a.avg+"</span>")}a.vol="0"==a.vol||"-"==a.vol?"-":A.handleRawData("vol",a.vol/1E4);a.amount="0"==a.amount||"-"==a.amount?"-":A.handleRawData("vol",a.amount/1E4);b="92"==subMarket.marketType?d:g;"analysis"==this.repoType?l.byId("analysisBank_repo").innerHTML=s.substitute(b,a):l.byId("bank_repo").innerHTML=s.substitute(b,a)},setTitleColor:function(a){var b=
"-",d="-",c=subMarket.marketType;if(a)b=bondCode.bondCode.split(".")[0].replace("IB",""),d=a.shortName;a={bondCode:b,bondName:d};"analysis"==this.repoType?l.byId("analysisBank_Title").innerHTML=s.substitute(p,a):l.byId("bank_Title").innerHTML=s.substitute(p,a);a="analysis"==this.repoType?l.byId("analysisBank_repo_title"):l.byId("bank_repo_title");if("95"===c)a.innerHTML=s.substitute(j,{repoTitle:"\u94f6\u884c\u95f4\u8d28\u62bc\u5f0f\u56de\u8d2d"});else if("96"===c)a.innerHTML=s.substitute(j,{repoTitle:"\u94f6\u884c\u95f4\u4e70\u65ad\u5f0f\u56de\u8d2d"});
else if("97"===c)a.innerHTML=s.substitute(j,{repoTitle:"\u94f6\u884c\u95f4\u540c\u4e1a\u62c6\u501f"});else if("92"===c)a.innerHTML=s.substitute(j,{repoTitle:"\u4eba\u6c11\u5e01\u5229\u7387\u4e92\u6362"})}})})},"url:bond/currencyMarket/template/bankRepo.html":"<tr>\r\n    <td>\u6700\u65b0\u4ef7</td><td>${new}</td><td>\u6da8\u8dcc</td><td>${updn}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u5f00\u76d8\u4ef7</td><td >${open}</td>\r\n    <td>\u6da8\u8dcc\u5e45</td><td >${updnratio}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u6700\u4f4e\u4ef7</td><td>${low}</td> <td>\u6700\u9ad8\u4ef7</td><td>${high}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u52a0\u6743\u4ef7</td><td >${avg}</td>\r\n    <td>\u6628\u6536\u76d8</td><td >${lastclose}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u6210\u4ea4\u91cf(\u4e07\u5143)</td><td>${vol}</td>\r\n</tr>\r\n\r\n\r\n",
"url:bond/currencyMarket/template/bankRepoLV.html":"<tr>\r\n    <td>\u6700\u65b0\u4ef7</td><td>${new}</td><td>\u6da8\u8dcc</td><td>${updn}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u5f00\u76d8\u4ef7</td><td >${open}</td>\r\n    <td>\u6da8\u8dcc\u5e45</td><td >${updnratio}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u6700\u4f4e\u4ef7</td><td>${low}</td> <td>\u6700\u9ad8\u4ef7</td><td>${high}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u52a0\u6743\u4ef7</td><td >${avg}</td>\r\n    <td>\u6628\u6536\u76d8</td><td >${lastclose}</td>\r\n</tr>\r\n<tr>\r\n    <td>\u6210\u4ea4\u989d(\u4e07\u5143)</td><td >${amount}</td>\r\n</tr>\r\n\r\n\r\n",
"url:bond/currencyMarket/template/bondTiTLe.html":'\r\n<span class="color_blu" >\u25b6</span>\r\n<span class="color_blu backgroud_sp"> ${bondCode} &nbsp;&nbsp;</span>\r\n<span >${bondName}&nbsp;&nbsp;</span>\r\n\r\n\r\n\r\n',"url:bond/currencyMarket/template/repoTitle.html":'<div class="chart_title" >${repoTitle}</div>',"bond/currencyMarket/public/colorStyleFormatter":function(){define(["dojo/_base/declare","dojo/json","dojox/slickgrid/formatters","dojox/store/GridWSStore","dojo/_base/lang"],function(k){var c=
0;return k([],{constructor:function(h){c=h},unsignedplusMinusColor:function(c,f,e){return null==e?"--":'<div class="'+(0==e?"":0<e?"font-red":"font-green")+'">'+Math.abs(e)+"</div>"},resetpricecolorandstyle:function(h,f,e,a,b,i){if(null==e)return"--";f="";h=f=0<h?i.getDataItem(h-1)["new"]:c;return['<div class="',0==b["new"]?"":+b["new"]>+c?"font-red":+b["new"]<+c?"font-green":"font-white",'">',e,h>e?'<span class="font-green">\u2193</span>':h<e?'<span class="font-red">\u2191</span>':"&nbsp;&nbsp;",
"</div>"].join("")},reSetYieldColor:function(h,f,e,a,b){return['<div class="',0==b["new"]?"":+b["new"]>+c?"font-red":+b["new"]<+c?"font-green":"font-white",'">',e,"</div>"].join("")},reSetTimeSecond:function(c,f,e){return 0==e.indexOf(":")?'<div style="color:#ABABAB;font-size: 6px">&nbsp;&nbsp;&nbsp;&nbsp;'+e+"</div>":'<div style="color:#ABABAB;">'+e+"</div>"}})})},"platform/charts/view/Crosshair":function(){define("../../../dojo/_base/declare,dijit/_WidgetBase,dijit/_TemplatedMixin,dojo/_base/lang,dojo/_base/connect,dojox/customfig/utils,dojo/dom-style,dojo/dom-construct,dojo/dom-geometry,dojo/dom,dojo/cssScale".split(","),
function(k,c,h,f,e,a,b,i,n,r,g){var d=function(a,b,d,c){var e;if(a[d])return(e=a[d][b])?e=c?a[d][b-1]?a[d][b-1]:0:e:(b=c?a[d].length-2:a[d].length-1,e=a[d][b]),e},p=function(a){for(var b=0,d=0,c=a.length;d<c;d++)b+=+a[d];return b},j=function(a,b,d,c){var e=0,c=c||0;b++;a[d]&&(e=b>a[d].length?p(a[d].slice(c))/a[d].slice(c).length:p(a[d].slice(c,b))/(b-c));return e},w=function(b){return{"\u65f6\u3000\u95f4":{field:"time",fn:function(b,c,s){return(b=d(b,c,s))?a.millisecond2Date("%H:%M",b):"--"}},"\u4ef7\u3000\u683c":{field:"price",
fn:function(a,c,e){return(a=d(a,c,e))?(+a).toFixed(b):"--"}},"\u5747\u3000\u4ef7":{field:"price",fn:function(a,d,c,e){return j(a,d,c,e).toFixed(b)}},"\u6da8\u3000\u8dcc":{field:"price",fn:function(a,c,e){c=d(a,c,e);a=d(a,0,"lastclose");return c&&a?(c-a).toFixed(b):0}},"\u5e45\u3000\u5ea6":{field:"price",fn:function(a,b,c){b=d(a,b,c);a=d(a,0,"lastclose");return(b&&a?(100*(b/a-1)).toFixed(2):0)+"%"}},"\u6210\u4ea4\u91cf":{field:"volume",fn:function(a,b,c){var s=d(a,b,c),a=d(a,b,c,!0);return s&&a?s-
a:0}}}},o=function(a){return{"\u65f6\u3000\u95f4":{field:"time",fn:function(a,b,c){return(a=d(a,b,c))?a:"--"}},"\u5f00\u76d8\u4ef7":{field:"open",fn:function(b,c,e){return(b=d(b,c,e))?(+b).toFixed(a):"--"}},"\u6700\u9ad8\u4ef7":{field:"high",fn:function(b,c,e){return(b=d(b,c,e))?(+b).toFixed(a):"--"}},"\u6700\u4f4e\u4ef7":{field:"low",fn:function(b,c,e){return(b=d(b,c,e))?(+b).toFixed(a):"--"}},"\u6536\u76d8\u4ef7":{field:"close",fn:function(b,c,e){return(b=d(b,c,e))?(+b).toFixed(a):"--"}},"\u5747\u3000\u4ef7":{field:"close",
fn:function(b,d,c,e){return j(b,d,c,e).toFixed(a)}},"\u6da8\u3000\u8dcc":{field:"close",fn:function(b,c,e){var g=d(b,c,e),b=0>c-1?d(b,c,"open"):d(b,c,e,!0);return Number(g)&&b?(g-b).toFixed(a):0}},"\u6210\u4ea4\u91cf":{field:"volume",fn:function(a,b,c,e){a=Number(d(a,b,c));return 1E4<a&&1E8>a?(a/1E4).toFixed(e)+"\u4e07":1E8<a?(a/1E8).toFixed(e||2)+"\u4ebf":isNaN(a)?"--":a.toFixed(e)}},"\u6210\u4ea4\u989d":{field:"amount",fn:function(b,c,e){var b=d(b,c,e),g;g=parseInt(b);b=""+g;1E4<(1E8>g)&&(b=(g/
1E4).toFixed(a)+"\u4e07");1E8<g&&(b=(g/1E8).toFixed(a)+"\u4ebf");return b}}}},x={time:"\u65f6\u3000\u95f4",open:"\u5f00\u76d8\u4ef7",high:"\u6700\u9ad8\u4ef7",low:"\u6700\u4f4e\u4ef7",close:"\u6536\u76d8\u4ef7",average:"\u5747\u3000\u4ef7",updown:"\u6da8\u3000\u8dcc",volume:"\u6210\u4ea4\u91cf",amount:"\u6210\u4ea4\u989d",price:"\u4ef7\u3000\u683c"},v=k(null,{tipKeyValue:null,tooltipTemplateString:"<span>{1}</span>:<span>{2}</span><br>",defaultOptions:{fixNum:3},constructor:function(a,b,d){this.mLabel=
a;this.plot=b;a=f.mixin(this.defaultOptions,d?d.options:{});this.tipKeyValue=this.plot.csizeRate?o(a.fixNum):w(a.fixNum);if(d.keys){for(var a=this.tipKeyValue,d=d.keys,c=0,e=d.length,g={};c<e;c++)b=d[c],(b=x[b])&&(g[b]=a[b]);this.tipKeyValue=g}},isShow:!1,behave:function(a){var d=this.plot,c=d.kwArgs.margins,e=d.offsets,i=c.t+e.t,c=c.l+e.l,h=d.plotHeight-e.t-e.b,e=d.plotWidth-e.l-e.r,q=d.main,f=d.mainIndicators,p=d.indicators,m,j,u,y;m=n.position(r.byId(d.domNode),!1);d=Math.round(a.pageX-m.x);a=
Math.round(a.pageY-m.y);if(a>=i&&a<=i+h&&d>=c&&d<=c+e){if(this.toggle()){b.set(this.mLabel,{top:g.scale(i,"y")+"px"});if(q&&(i=q.yStart,h=i+q.height,a>=i&&a<=h&&(this.setToolTip(q,d),i=n.getMarginBox(this.mLabel,!1),this.setTooltipPos(d,c,e,i.w),f)))for(var z in f)if(m=f[z],i=m.yStart,xStart=m.xStart,h=i+m.height,u=m.options.prepareDistance,j=m.csize,y=m.cwidth,j=Math.ceil((d-xStart-u-j)/y),a>=i&&a<=h){this.setToolTip(m,d);i=n.getMarginBox(this.mLabel,!1);this.setTooltipPos(d,c,e,i.w);j=m.getStart()?
m.getStart()+j:j;m.renderTxt&&m.renderTxt(j);return}if(!q&&f)for(z in f)if(q=f[z],i=q.yStart,h=i+q.height,a>=i&&a<=h){this.setToolTip(q,d);i=n.getMarginBox(this.mLabel,!1);this.setTooltipPos(d,c,e,i.w);return}if(p)for(z in p)if(q=p[z],i=q.yStart,xStart=q.xStart,h=i+q.height,u=q.options.prepareDistance,j=q.csize,y=q.cwidth,j=Math.ceil((d-xStart-u-j)/y),a>=i&&a<=h){this.setToolTip(q,d);i=n.getMarginBox(this.mLabel,!1);this.setTooltipPos(d,c,e,i.w);j=q.getStart()?q.getStart()+j:j;q.renderTxt&&q.renderTxt(j);
break}}}else b.set(this.mLabel,{display:"none"})},setToolTip:function(b,d){var c=b.xStart,e=b.cwidth,g=b.csize;a.array2toarray1(b.xLabels);var i=this.plot,h=i.getData(),f=b.options.prepareDistance,n=this.tooltipTemplateString,c=i.main.csizeRate?Math.ceil((d-c-f-g)/e)+i.main.getStart():Math.ceil((d-c-f-g)/e),e=[],f=this.plot.theme.crosshair.tooltip,r;for(r in this.tipKeyValue){b=this.tipKeyValue[r];g=n.replace(/\{1\}/g,r);if(/\u5747\u4ef7/g.test(r))var j=i.main.getStart?i.main.getStart():0,g=g.replace(/\{2\}/g,
b.fn(h,c,b.field,j));else g=g.replace(/\{2\}/g,b.fn(h,c,b.field)),/\u65f6\u95f4/g.test(r)&&(g='<span style="color:'+f.time.color+";font-weight:"+f.time["font-weight"]+'">'+g+"</span>");e.push(g)}this.mLabel.innerHTML=e.join("")},setTooltipPos:function(a,d,c,e){a<=d+c/2?b.set(this.mLabel,{left:g.scale(d+c-e,"x")+"px"}):b.set(this.mLabel,{left:g.scale(d,"x")+"px"});b.set(this.mLabel,{right:"auto"})},toggle:function(){b.set(this.mLabel,{"-webkit-transform-origin":"left top","-webkit-transform":"scale("+
1/g.getScaleX()+","+1/g.getScaleY()+")"});if(this.isShow)return b.set(this.mLabel,{display:""}),!0;b.set(this.mLabel,{display:"none"});return!1}}),t=k(null,{constructor:function(a,b,d,c,e){this.vLine=a;this.hLine=b;this.vLabel=d;this.hLabel=c;this.plot=e},isShow:!1,toggle:function(){b.set(this.hLabel,{display:""});b.set(this.vLabel,{display:""});b.set(this.hLabel,{"-webkit-transform-origin":"left top","-webkit-transform":"scale("+1/g.getScaleX()+","+1/g.getScaleY()+")"});b.set(this.vLabel,{"-webkit-transform-origin":"left top",
"-webkit-transform":"scale("+1/g.getScaleX()+","+1/g.getScaleY()+")"});b.set(this.hLine,{"-webkit-transform-origin":"left top","-webkit-transform":"scale("+1/g.getScaleX()+","+1/g.getScaleY()+")"});b.set(this.vLine,{"-webkit-transform-origin":"left top","-webkit-transform":"scale("+1/g.getScaleX()+","+1/g.getScaleY()+")"});if(this.isShow)return b.set(this.hLine,{display:""}),b.set(this.vLine,{display:""}),!0;b.set(this.hLine,{display:"none"});b.set(this.vLine,{display:"none"});return!1},behave:function(a){var d=
this.plot,c=d.kwArgs.margins,e=d.offsets,i=c.t+e.t,c=c.l+e.l,h=d.plotHeight-e.t-e.b,e=d.plotWidth-e.l-e.r,f=d.main,j=d.mainIndicators,p=d.indicators,m,k,u;u=n.position(r.byId(d.domNode),!0);d=Math.round(a.pageX-u.x);a=Math.round(a.pageY-u.y);if(a>=i&&a<=i+h&&d>=c&&d<=c+e){this.toggle()&&(b.set(this.hLine,{width:e+"px",left:g.scale(c,"x")+"px",top:g.scale(a,"y")+"px"}),b.set(this.vLine,{height:h+"px",top:g.scale(i,"y")+"px",left:g.scale(d,"x")+"px"}));if(f&&(m=f.yStart,u=m+f.height,k=f.yAxisScale,
a>=m&&a<=u))f.baseValue?(k=f.baseValue[0],m=k*f.ymin,k*=f.ymax,k=f.height/(k-m)):m=f.ymin,this.setXLabel(f,d),this.setYLabel(m,u,k,a,f.options.bottomSpacing||0,f.options.fixedNum);if(!f&&j)for(var y in j)f=j[y],m=f.yStart,u=m+f.height,a>=m&&a<=u&&(this.setXLabel(f,d),this.setYLabel(f.ymin,u,f.yAxisScale,a,f.options.bottomSpacing||0,f.options.fixedNum));if(p)for(y in p)f=p[y],m=f.yStart,u=m+f.height,a>=m&&a<=u&&(this.setXLabel(f,d),this.setYLabel(f.ymin,u,f.yAxisScale,a,f.options.bottomSpacing||0,
f.options.fixedNum));j=n.position(this.hLabel);y=n.position(this.vLabel);e=d-c<j.w/2?c:e-(d-c)<j.w/2?c+e-j:d-j.w/2;b.set(this.hLabel,{top:g.scale(i+h+2,"y")+"px",left:g.scale(e,"x")+"px"});b.set(this.vLabel,{left:"-3px",top:g.scale(a-y.h/2,"y")+"px",width:c+"px"})}else b.set(this.hLine,{display:"none"}),b.set(this.vLine,{display:"none"}),b.set(this.hLabel,{display:"none"}),b.set(this.vLabel,{display:"none"})},setXLabel:function(b,d){var c=b.xStart,e=b.cwidth,g=b.csize,f=a.array2toarray1(b.xLabels);
prepareDistance=b.options.prepareDistance;xline=Math.ceil((d-c-prepareDistance-g)/e);c=f[xline]||f[xline-1];"undefined"==typeof c&&(c="--/--");this.hLabel.children[0].innerHTML=c},setYLabel:function(a,b,d,c,e,g){this.vLabel.children[0].innerHTML=((b-c-e)/d+a).toFixed(g)}});return k("dojox.customfig.actions.Crosshair",[c,h],{templateString:"<div><div data-dojo-attach-point='mLabel' style='display:none;'></div><div data-dojo-attach-point='vLabel' style='display:none;'><strong data-dojo-attach-point='vLabelVal'></strong><div style ='width: 5px; height: 5px; border-top: #587eb5 2px solid; border-left: #587eb5 2px solid; position: absolute;  top: 5px; right: -4px; -webkit-transform: rotate(145deg) skew(1deg, 1deg);border-radius: 2px;'></div></div><div data-dojo-attach-point='hLabel' style='display:none;'><strong data-dojo-attach-point='hLabelVal'></strong><div style ='width: 5px; height: 5px; border-top: #587eb5 2px solid; border-left: #587eb5 2px solid; position: absolute; top: -5px; left: 45%; -webkit-transform: rotate(45deg) skew(0deg, 0deg);border-radius: 2px;'></div></div><div data-dojo-attach-point='vLine' style='display:none;'></div><div data-dojo-attach-point='hLine' style='display:none;'></div>",
plot:null,lineLabel:null,toolTip:null,constructor:function(a){this.kwArgs=a;this.plot=a.plot;this.tipKey=a.tipKey||{}},postCreate:function(){var a=this.kwArgs,d=this.plot.theme,a=this.style={tooltip:a.style?f.mixin({},d.crosshair.tooltip,a.style.tooltip):d.crosshair.tooltip,hLine:a.style?f.mixin({},d.crosshair.hLine,a.style.hLine):d.crosshair.hLine,vLine:a.style?f.mixin({},d.crosshair.vLine,a.style.vLine):d.crosshair.vLine,hLabel:a.style?f.mixin({},d.crosshair.hLabel,a.style.hLabel):d.crosshair.hLabel,
vLabel:a.style?f.mixin({},d.crosshair.vLabel,a.style.vLabel):d.crosshair.vLabel};b.set(this.mLabel,a.tooltip.content);b.set(this.hLabel,a.hLabel);b.set(this.vLabel,a.vLabel);b.set(this.hLine,a.hLine);b.set(this.vLine,a.vLine);this.lineLabel=new t(this.vLine,this.hLine,this.vLabel,this.hLabel,this.plot);this.toolTip=new v(this.mLabel,this.plot,this.tipKey);i.place(this.domNode,this.plot.domNode,"first");e.connect(this.plot.domNode,"click",this,this.click);e.connect(this.plot.domNode,"mousemove",this,
this.mouseMove)},click:function(a){var b=this.plot,d=b.kwArgs.margins,c=b.offsets,e=d.t+c.t,d=d.l+c.l,g=b.plotHeight-c.t-c.b,c=b.plotWidth-c.l-c.r,f;f=n.position(r.byId(b.domNode),!1);b=Math.round(a.pageX-f.x);a=Math.round(a.pageY-f.y);if(a>=e&&a<=e+g&&b>=d&&b<=d+c)this.toolTip.isShow=!this.toolTip.isShow,this.lineLabel.isShow=!this.lineLabel.isShow},mouseMove:function(a){this.toolTip.behave(a);this.lineLabel.behave(a)}})})},"platform/charts/view/utils":function(){define(["dojo/aspect","dojox/customfig/utils",
"dojox/customfig/mains/Kline","dojox/canvasDashedLine"],function(k,c,h,f){var e={lines:[],init:function(){this.render();requestAnimationFrame(arguments.callee.bind(this));return this},render:function(){if(this.lines.length)this.data=this.ctx.getImageData(0,0,this.canvas.width,this.canvas.height),this.lines.forEach(function(a){this.drawBL.apply(this,a)},this),this.ctx.putImageData(this.data,0,0),this.data=void 0,this.lines.length=0},colorToRGB:function(a){return(a=/^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec({aqua:"#00ffff",
black:"#000000",blue:"#0000ff",fuchsia:"#ff00ff",gray:"#808080",green:"#008000",lime:"#00ff00",maroon:"#800000",navy:"#000080",olive:"#808000",purple:"#800080",red:"#ff0000",silver:"#c0c0c0",teal:"#008080",white:"#ffffff",yellow:"#ffff00"}[a]||a))?[parseInt(a[1],16),parseInt(a[2],16),parseInt(a[3],16)]:[0,0,0]},setPixel:function(a,b,c){a=4*(b*this.canvas.width+a);b=this.data.data;b[a]=c[0];b[a+1]=c[1];b[a+2]=c[2]},drawBL:function(a,b,c,e,f){if(a!==c||b!==e)for(var g=Math.abs(c-a),d=Math.abs(e-b),
h=a<c?1:-1,j=b<e?1:-1,k=g-d;!(a==c&&b==e);){this.setPixel(a,b,f);var o=2*k;o>-d&&(k-=d,a+=h);o<g&&(k+=g,b+=j)}},drawLine:function(a,b,c,e,f,g){if(!this.canvas)this.canvas=document.querySelector("canvas"),this.ctx=a,k.around(a,"measureText",function(a){return function(b){var c=a.call(this,b);if(b&&b.length)switch(!0){case /^\d\d:\d\d$/.test(b):return{width:c.width+20};case /^\d{4}\/\d\d\/\d\d$/.test(b):return{width:c.width+10}}return c}});g&&!isNaN(b)&&!isNaN(c)&&!isNaN(e)&&!isNaN(f)&&0<=b&&0<=e&&
this.lines.push([Math.round(b),Math.round(c),Math.round(e),Math.round(f),this.colorToRGB(g)])},drawDashes:function(a,b,c,e,h,g){b=Math.round(b)+(Math.round(b)<b?0.5:-0.5);c=Math.round(c)+(Math.round(c)<c?0.5:-0.5);e=Math.round(e)+(Math.round(e)<e?0.5:-0.5);h=Math.round(h)+(Math.round(h)<h?0.5:-0.5);"#600000"===g&&(b===e?c<h?(c+=1.5,h++):(c++,h+=1.5):c===h&&(b<e?(b++,e--):(b--,e++)));f.drawDashedPolyLine(a,[[b,c],[e,h]],{pattern:"-**-",color:g,scale:2})},drawRect:function(a,b,c,e,f,g){e=Math.round(b+
e);f=Math.round(c+f);b=Math.round(b);c=Math.round(c);e-=b;f-=c;50>e&&!(e%2)&&e++;g?(g=a.fillStyle,a.fillStyle=a.strokeStyle,a.fillRect(b,c,e,1),a.fillRect(b+e-1,c,1,f),a.fillRect(b,c+f,e,1),a.fillRect(b,c,1,f),a.fillStyle=g):a.fillRect(b,c,e,f)},drawText:function(a,b,c,e,f){"top"===f.textBaseline&&(arguments[3]=e+5);return arguments}}.init();c.drawline=e.drawLine.bind(e);c.drawDashes=e.drawDashes.bind(e);c.drawRect=e.drawRect.bind(e);c.from5StrToHM=function(a,b){b=(new Date(+new Date((new Date(new Date-
6E4*(new Date).getTimezoneOffset())).toJSON().slice(0,10))+1E3*b)).toJSON().slice(11,16);return"%h%m"===a?b.replace(":",""):b};k.before(c,"clearCanvas",e.render.bind(e));k.before(c,"drawText",e.drawText.bind(e));h.prototype.drawCandle=function(a,b,e,f,h,g){var d=this.ctx,k=this.options,j=this.ymin,w=this.yStart+this.height-k.bottomSpacing,o=k.prepareDistance,x=this.yAxisScale,v=this.cwidth,t=this.csize,s=this.xStart,l=k.candleStyle,k=w-(a-j)*x,b=w-(b-j)*x,e=w-(e-j)*x,j=w-(f-j)*x;f>a?(a=k-j,j===k&&
(a=1),h=l[h].upStyle.candle.color,d.strokeStyle=h,1<t?(g=o+g*v+s,t=Math.floor(t)+Math.floor(t)%2,o=Math.round(g)+Math.floor(t/2),c.drawRect(d,g,j,t,a,!0),c.drawline(d,o,b,o,j,h,1),c.drawline(d,o,k,o,e,h,1)):(g=o+g*v+s+t/2,c.drawline(d,g,b,g,e,h,1))):(a=j-k,j===k&&(a=1),h=l[h].downStyle.candle.color,d.fillStyle=h,1<t?(g=o+g*v+s,t=Math.floor(t)+(Math.floor(t)%2?0:1),o=Math.round(g)+Math.floor(t/2),c.drawRect(d,g,k,t,a,!1),c.drawline(d,o,b,o,j,h,1),c.drawline(d,o,k,o,e,h,1)):(g=o+g*v+s+t/2,c.drawline(d,
g,b,g,e,h,1)))};return c})},"bond/currencyMarket/public/ContextMenuTrend":function(){define("dojo/on,dojo/mouse,dojo/keys,dojo/_base/declare,dojox/customfig/actions/CustomfigAction,dojo/_base/lang,dojo/_base/array,dojo/dom,dojo/dom-geometry,dojox/customfig/utils".split(","),function(k,c,h,f,e,a,b){return f("bond.bondMarket.public.ContextMenu",e,{constructor:function(a,b){this.plot=a;this.addMenu(b.domId);this.minSharingPlans=b.minSharingPlans;this._handles=[];this.connect();this.plot.canvas.tabIndex=
1},curcode:"",_disconnectHandles:function(){b.forEach(this._handles,function(a){a.remove()});this._handles=[]},addMenu:function(b){var c=this;require(["dijit/Menu","dijit/MenuItem","dijit/MenuSeparator","dijit/PopupMenuItem"],function(e,f){var d=new e({targetNodeIds:[b]});d.addChild(new f({label:"\u590d\u5236\u6570\u636e",parentMenu:d,onClick:a.hitch(c,c.reSaveData)}));d.startup()})},reSaveData:function(){this.plot.saveAsExcel()}})})}}});
define("bond/currencyMarket/src","dojo/aspect,dojo/parser,dojo/on,dijit/form/ComboBox,dijit/form/Button,dojo/store/Memory,dojox/customfig/themes/blackTheme,dojox/customfig/widget/DIDKline,dojox/customfig/actions/MouseAndKey,bond/currencyMarket/public/ContextMenu,dijit/layout/TabContainer,dijit/layout/ContentPane,bond/currencyMarket/public/marketGrid,bond/currencyMarket/public/bankRepoLabel,dojox/store/WebSocket,bond/currencyMarket/public/colorStyleFormatter,platform/charts/view/Crosshair,platform/charts/view/utils,bond/currencyMarket/public/util,bond/currencyMarket/public/ContextMenuTrend,dojox/customfig/widget/DIDSharingPlans,dojox/store/GridWSStore,dojo/_base/lang".split(","),function(k,
c,h,f,e,a,b,i,n,r,g,d,p,j,w,o,x,v,t,s,l,A,B){var C;function D(b,c){if(isKline){var d=new a({data:[{name:"\u65e5\u7ebf",id:"day"}]}),g=new f({id:"periodLine",name:"state",value:"\u65e5\u7ebf",store:d,searchAttr:"name",style:"width:10%","class":"font_trl"},"periodLine");g.on("change",function(){var a="";"\u65e5\u7ebf"==g.value?a="1d":"\u5468\u7ebf"==g.value?a="1w":"\u6708\u7ebf"==g.value?a="1M":"\u5b63"==g.value?a="1q":"\u5e74"==g.value&&(a="1y");whetherShowData&&(b.setTimeScale({value:a,txt:this.get("value")}),
b.render())});d=new a({data:[{name:"\u6700\u8fd1\u4e00\u4e2a\u6708",id:"oneM"},{name:"\u6700\u8fd1\u4e09\u4e2a\u6708",id:"threeM"},{name:"\u6700\u8fd16\u4e2a\u6708",id:"sixM"},{name:"\u5e74\u521d\u81f3\u4eca",id:"yearToDate"},{name:"\u6700\u8fd11\u5e74",id:"oneY"},{name:"\u6700\u8fd12\u5e74",id:"twoY"},{name:"\u6700\u8fd13\u5e74",id:"threeY"},{name:"\u4e0a\u5e02\u81f3\u4eca",id:"listedSoFar"}]});d=new f({id:"intervalSelection",name:"state",value:"\u6700\u8fd16\u4e2a\u6708",store:d,searchAttr:"name",
style:"width:12%","class":"font_trl"},"intervalSelection");d.on("change",function(){var a=this.get("value"),c="";"\u6700\u8fd1\u4e00\u4e2a\u6708"==a?c="1M":"\u6700\u8fd1\u4e09\u4e2a\u6708"==a?c="3M":"\u6700\u8fd16\u4e2a\u6708"==a?c="6M":"\u5e74\u521d\u81f3\u4eca"==a?c="0M":"\u6700\u8fd11\u5e74"==a?c="1Y":"\u6700\u8fd12\u5e74"==a?c="2Y":"\u6700\u8fd13\u5e74"==a?c="3Y":"\u4e0a\u5e02\u81f3\u4eca"==a&&(c="maxY");"0"==c.slice(0,-1)&&(c=(new Date).getMonth()+1,c+="M");var a=v.millisecond2Date("%Y%m%d%H%M%S",
Math.round(Date.now()/1E3),!1,!1,!0),d;var e=Number(c.slice(0,-1)),f,g,h=Array.prototype.slice,i=Array.prototype.splice,j=h.call(a);/maxY/i.test(c)?d="19700101000000":(/m/i.test(c)&&(d=Number(a.slice(4,6)),f=Number(a.slice(0,4)),g=Math.floor(e/12),d-=e%12,1>d&&(d=12+d,g++),f-=g,10>d&&(d="0"+d)),/y/i.test(c)&&(f=Number(j.slice(0,4).join(""))-e),f&&(strs=h.call(""+f),i.call(j,0,4),j=strs.concat(j)),d&&j.splice(4,2,""+d),d=j.join(""));whetherShowData&&(b.setCount(0),b.setStartTime(d),b.setEndTime(a),
b.render())})}new e({label:"\u590d\u5236\u6570\u636e",className:"button_Style",onClick:function(){(isKline?b.plot:c.plot).saveAsExcel()}},"copyData");isKline?(new x({plot:b.plot,style:{},tipKey:{options:{fixNum:4},keys:"time,open,high,low,close,updown,volume".split(",")}}),new n(b.plot),new r(b.plot,{domId:"figure_box",klineKline:b,intervalSelection:d,dayLine:g})):(new x({plot:c.plot,style:{},tipKey:{options:{fixNum:4},keys:["time","price","updown"]}}),new s(c.plot,{domId:"figure_box",minSharingPlans:c}));
dijit.byId("kline").resize()}function q(a){var c={obj:"obj",time:function(a,b,c,d){return 1*v.str2millisecond(b[c[d]])},price:"new",volume:"vol"},d,e,f=subMarket.marketType;if("95"==f)d=100201,e=100005,c.volume="vol";else if("96"==f)d=100202,e=100006,c.volume="vol";else if("97"==f)d=100200,e=100004,c.volume="vol";else if("92"==f)d=100203,e=100009,c.volume="amount";f=function(a){a.com_de_opt.font="12px simsun";a.ma.ma=["white","yellow","fuchsia"];a.vol.volumnStyle.upColor="#FF5454";a.vol.volumnStyle.downColor=
"#54FFFF";a.crosshair.tooltip.content.background="rgba(0,0,0,.7)";delete a.crosshair.tooltip.content["text-align"];delete a.crosshair.tooltip.content.opacity;return a}(new b);f.sharingPlans.timetrend=["#ffffff","red","yellow"];a=new l({codes:[{name:bondCode.bondCode,type:"lastclose",codeName:a}],baseDid:e,plot:{margins:{l:2,t:2,r:4,b:2},offsets:{l:50,t:20,r:60,b:20},noscale:!0},theme:f,queryObj:c,sharingPlans:{options:{timetrendFilled:!1,fixedNum:2,rateNum:1.0E-4,rateNumOffset:0.1,baseValueStyle:{color:"red"}}},
indicators:[{type:"Vol",params:{args:[],options:{topSpacing:0,closed:!1,closedStyle:{w:7,h:7,color:"red"}}}}],mainIndicators:[{type:"Ma",params:{args:[5],options:{mainIndicatorType:1}}}]},"figure_box");if(whetherShowData)a.did=d;a.startup();a.plot.indicators.vol.txt="";a.plot.indicators.vol.yAxis=function(){var a=this.ctx,b=this.options,c=this.xStart,d=c+this.width,e=this.yStart,f=this.height,g=e+f,h=this.yAxisScale,j=this.ymin,i=this.yLabels;if(!i||!i.length)for(var f=v.ygrid(j,this.ymax,Math.floor((f-
b.topSpacing)/b.backgroundGrid.height)),k=0,u=f.length;k<u;k++)Math.pow(10,b.precision.num),i=g-(f[k]-j)*h,i===e||i===g||("dashed"==b.backgroundGrid.type?v.drawDashes(a,c,i,d,i,b.backgroundGrid.color,1):v.drawline(a,c,i,d,i,b.backgroundGrid.color))};a.delMainIndicator("ma");d=new b;a.setTheme(d);D("",a)}function E(){var a={obj:"obj",time:function(a,b,c,d,e){return v.millisecond2Date(arguments.callee.that.timeStyle,v.str2millisecond(b[c[d]]))},timeStamp:function(a,b,c){return v.str2millisecond(b[c.time])},
open:"open",high:"high",low:"low",close:"close",volume:"vol"},c={volume:"amount"},d,e=subMarket.marketType;"95"==e?d=100105:"96"==e?d=100106:"97"==e?d=100104:"92"==e&&(d=100109,B.mixin(a,c));c=v.millisecond2Date("%Y%m%d%H%M%S",Math.round(Date.now()/1E3),!1,!1,!0);c=t.getKineStarTime(c);a=new i({codes:[bondCode.bondCode],timeScale:{value:"1d",txt:"\u65e5\u7ebf"},plot:{margins:{l:2,t:2,r:4,b:2},offsets:{l:70,t:20,r:30,b:20},noscale:!0},theme:function(a){a.com_de_opt.font="12px simsun";a.kline.candleStyle=
[{upStyle:{candle:{type:"stroke",color:"#FF5454"}},downStyle:{candle:{type:"fill",color:"#54FFFF"}}},{upStyle:{candle:{type:"stroke",color:"#FF5454"}},downStyle:{candle:{type:"fill",color:"#54FFFF"}}},{upStyle:{candle:{type:"stroke",color:"#FF5454"}},downStyle:{candle:{type:"fill",color:"#54FFFF"}}},{upStyle:{candle:{type:"stroke",color:"#FF5454"}},downStyle:{candle:{type:"fill",color:"#54FFFF"}}},{upStyle:{candle:{type:"stroke",color:"#FF5454"}},downStyle:{candle:{type:"fill",color:"#54FFFF"}}}];
a.ma.ma=["white","yellow","fuchsia"];a.vol.volumnStyle.upColor="#FF5454";a.vol.volumnStyle.downColor="#54FFFF";a.crosshair.tooltip.content.background="rgba(0,0,0,.7)";delete a.crosshair.tooltip.content["text-align"];delete a.crosshair.tooltip.content.opacity;return a}(new b),queryObj:a,Kline:{startTime:c,options:{klineType:1,fixedNum:2,showCounts:10,topSpacing:30,bottomSpacing:30,isHighLowShowed:!0,isDrawName:!1,backgroundGrid:{type:"dashed",color:"#600000",height:40,lineHeight:0.4}}},indicators:[{type:"Vol",
params:{args:[],options:{topSpacing:0,closed:!1,precision:{num:4,txt:"x10000"},backgroundGrid:{type:"dashed",color:"#600000",height:25,lineHeight:0.4}}}}],mainIndicators:[{type:"Ma",params:{args:[5,10],options:{fixedNum:3,mainIndicatorType:1}}}]},"figure_box");if(whetherShowData)a.did=d;a.startup();a.plot.indicators.vol.txt="";d=new b;a.setTheme(d);a.render();D(a)}function F(){var a=new g({tabPosition:"bottom",selectedchild:"cp1",tabStrip:!0,style:"height: 100%; width: 100%;",className:"spacer table_border_trl"},
"repoNews"),b=new d({title:"\u65b0\u95fb",content:'<div id="bondNews" style="width: 100%;height: 100%" ></div>'});a.addChild(b);a.startup();new p({columns:[{id:"C16",name:"\u65f6\u95f4",field:"C16",width:1,formatter:C,sortable:!0,headerCssClass:"font-center",cssClass:"font-center font-gray"},{id:"C3",name:"\u6807\u9898",field:"C3",width:3,headerCssClass:"font-center",cssClass:"font-left font-gray"},{id:"C8",name:"\u6765\u6e90",field:"C8",width:2,headerCssClass:"font-center",cssClass:"font-left font-gray"}],
options:{enableCellNavigation:!0,enableColumnReorder:!1,forceFitColumns:!0,rowHeight:20},dataType:"getBondNews",gridId:"bondNews"})}function m(){var a=new g({tabPosition:"bottom",selectedchild:"td",tabStrip:!0,style:"height: 100%; width: 100%;",className:"spacer table_border_trl"},"repoDevision"),b=new d({title:"\u5206\u65f6\u6210\u4ea4",content:'<div id="devision" style="width: 100%;height: 100%" ></div>'});a.addChild(b);a.startup();G()}function G(){var a=0,b={service:"did",where:"obj="+bondCode.bondCode,
response_times:1},c={field:"time,price",dataType:"repo",gridId:"devision",bondCode:bondCode.bondCode};if(95==subMarket.marketType)b.did="100005",c.did="100205";else if(96==subMarket.marketType)b.did="100006",c.did="100206";else if(97==subMarket.marketType)b.did="100004",c.did="100204";else if(92==subMarket.marketType)b.did="100009",c.did="100209";(new w).query(b).then(function(b){b[0]&&b[0].result&&b[0].result.datas&&b[0].result.datas.length&&(a=b[0].result.datas[0][9]);b=new o(a);c.columns=[{id:"time",
name:"\u65f6\u95f4",field:"time",width:5,formatter:b.reSetTimeSecond,headerCssClass:"font-center",cssClass:"font-center font-white"},{id:"new",name:"\u4ef7\u683c",field:"new",width:5,formatter:b.resetpricecolorandstyle,sortable:!0,headerCssClass:"font-center",cssClass:"font-center font-green"}];c.options={enableCellNavigation:!0,enableColumnReorder:!1,forceFitColumns:!0,rowHeight:20};new p(c)})}k.before(w.prototype,"query",function(a,b){var c=arguments.callee.map||{},d=this.constructor.prototype.declaredClass;
this.fixVol=/^100[01]0[45]$/.test(a.did);if(!(d in c))c[d]=!0,arguments.callee.map=c,k.before(this.constructor.prototype,"convert",function(a){if(this.fixVol&&a.result&&a.result.head){var b=a.result.head,a=a.result.datas,c={data:b.indexOf("data")};if(-1<c.data&&a[0]instanceof Array)b=a[0][c.data].head,a=a[0][c.data].datas;c.vol=b.indexOf("vol");c.time=b.indexOf("time");-1<c.vol&&a.forEach(function(a){2.0141215E19<=a[this.time]&&(a[this.vol]=1E8*a[this.vol]+"")},c)}})});C=void 0;C=function(a,b,c){a=
null;a=new Date;return a=c&&10<c.length?a.getDate()==c.slice(6,8)&&a.getMonth()==Number(c.slice(4,6))-1&&a.getFullYear()==c.slice(0,4)?c.slice(8,10)+":"+c.slice(10,12)+":"+c.slice(12,14):c.slice(0,4)+"-"+c.slice(4,6)+"-"+c.slice(6,8):c};return function(){c.parse();h(document.body,"dblclick",function(a){var b;dojo.query(a.target).closest(".slickgrid")&&dojo.query(a.target).closest(".slickgrid")[0]&&dojo.query(a.target).closest(".slickgrid")[0].id&&(b=dojo.query(a.target).closest(".slickgrid")[0].id);
if("bondNews"!=b&&goToUrl&&""!=goToUrl.gotourl)window.location.href=goToUrl.gotourl});var a;a=setInterval(function(){var b=new Date,c=b.getHours(),b=b.getMinutes();if(6==c&&30==b)window.location=window.location,clearInterval(a)},6E4);new j({repoType:"analysis"});new d({content:'<div id="figure_box" style="width: 100%;height: 100%" ></div>',resize:function(){this.inherited("resize",arguments)}},"kline");isKline?E():q("");F();m()}});