//>>built
define("stock/MicroStrategy/resources/linkPage/microSelectionUtil","dijit/registry,dojo/_base/config,dojo/date/locale,dojox/store/GridSOStore,dojox/slickgrid/slickgrid,dojo/io-query,dojox/slickgrid/formatters,dojox/store/MultiResultStore,dojo/store/Memory,dojo/number".split(","),function(r,g,s,n,k,l,p,q,o,m){var h={addOrDelAttention:function(a,b,d){h.sendOptRequest(a,b,d)},sendOptRequest:function(a,b,d){var f=new k({store:new n,queryLimit:{}},""),a={userId:a,microId:b,optTyp:d,randNum:Math.random()};
f.renderQuery({service:"rpc",so:"javadataproxy.jar","function":"gw/UIMain",paraencode:"base64",parameter:"Z2V0,"+btoa(g.dzhURL+"/MicroStrategyBG/micro/changeAttentionWithRandNum?"+l.objectToQuery(a)),response_times:1,response_mode:0}).then(function(){})},addVotes:function(a,b,d,f,j){var i=new k({store:new n,queryLimit:{}},""),a={userId:a,microId:b,randNum:Math.random()};i.renderQuery({service:"rpc",so:"javadataproxy.jar","function":"gw/UIMain",paraencode:"base64",parameter:"Z2V0,"+btoa(g.dzhURL+"/MicroStrategyBG/microChoose/microVotes?"+
l.objectToQuery(a)),response_times:1,response_mode:0}).then(function(a){j(a.getItem(0),d,f)})},setUserInfo:function(a){dojo.byId("TextBox_0").innerHTML=a.name;dojo.byId("TextBox_1").innerHTML=a.typ;dojo.byId("TextBox_2").innerHTML=a.org;dojo.byId("TextBox_3").innerHTML=a.qualifiedId},getInstance:function(a){var b=[];if(a.length&&0<a.length)for(var d=0;d<a.length;d++)b.push(this.getObj(a[d]));return b},getObj:function(a){var b={};b.attFlag=a.attFlag;b.buildMan=a.buildMan;b.code=a.code;b.id=a.id;b.increaseRate=
a.increaseRate;b.latsWeekVotes=a.latsWeekVotes;b.name=a.name;b.thisWeekVotes=a.thisWeekVotes;b.totalIncomeRate=a.totalIncomeRate;b.voteFlag=a.voteFlag;if(a.stkList&&a.stkList.length&&0<a.stkList.length)for(var d=[],f=0;f<a.stkList.length;f++){var j=a.stkList[f],i={};i.microId=j.microId;i.stkId=j.stkId;i.weigth=j.weigth;d.push(i)}return b}};h.startup=function(){function a(a,b,e){e=m.format(e,{pattern:",###.00"});return 0>e?"<div class='font-green'><b>"+e+"</b></div>":0<e?"<div class='font-red'><b>+"+
e+"</b></div>":"<div class='font-gray'><b>"+e+"</b></div>"}var b=[{id:"number",name:"\u5e8f\u53f7",formatter:p.index,width:28,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"code",name:"\u7b56\u7565\u4ee3\u7801",field:"code",width:70,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"name",name:"\u7b56\u7565\u540d\u79f0",field:"name",width:150,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"gains",name:"\u6628\u65e5\u6da8\u5e45\uff08%\uff09",
field:"increaseRate",formatter:a,width:85,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"CumulativeGain",name:"\u7d2f\u8ba1\u6536\u76ca\uff08%\uff09",field:"totalIncomeRate",formatter:a,width:85,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"LastVote",name:"\u4e0a\u5468\u6295\u7968",field:"latsWeekVotes",formatter:function(a,b,e){return m.format(e,{pattern:"###"})},width:70,headerCssClass:"font-center title_1",cssClass:"font-center",
resizable:!1},{id:"NowVote",name:"\u672c\u5468\u6295\u7968",field:"thisWeekVotes",formatter:function(a,b,e,d,c){return"<div id='"+c.code+"_thisWeek'>"+m.format(e,{pattern:"###"})+"</div>"},width:70,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"start2",name:"\u5173\u6ce8\u72b6\u6001",field:"attFlag",formatter:function(a,b,e,d,c){return 1==c.attFlag?'<button class="button focus focus001" id="'+c.code+'_att" microCode="'+c.code+'" style="height:20px; padding-left:15px;">\u5df2\u5173\u6ce8</button>':
'<button class="button focus" id="'+c.code+'_att" microCode="'+c.code+'" style="height:20px; padding-left:15px;">\u672a\u5173\u6ce8</button>'},width:80,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"start2",name:"\u6295\u7968\u72b6\u6001",field:"voteFlag",formatter:function(a,b,e,d,c){return 1==c.voteFlag?'<button class="button hand focus002" id="'+c.code+'_vote"  microCode="'+c.code+'" thisVotesDiv="'+c.code+'_thisWeek" style="height:20px;width:50px; padding-left:20px; color:red;">'+
c.userVotes+"</button>":'<button class="button hand" id="'+c.code+'_vote"  microCode="'+c.code+'" thisVotesDiv="'+c.code+'_thisWeek" style="height:20px;width:50px; padding-left:20px; color:red;">+1</button>'},width:80,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1},{id:"start2",name:"\u521b\u5efa\u4eba",field:"buildMan",width:80,headerCssClass:"font-center title_1",cssClass:"font-center",resizable:!1}],d={rowHeight:30},f={userId:g.dzhUserId,randNum:Math.random()};(new k({store:new q,
queryLimit:{}},"")).renderQuery({service:"rpc",so:"javadataproxy.jar","function":"gw/UIMain",paraencode:"base64",parameter:"Z2V0,"+btoa(g.dzhURL+"/MicroStrategyBG/microChoose/getTop20?"+l.objectToQuery(f)),response_times:1,response_mode:0}).then(function(a){var f=30*a[1].items.length+28+"px";dojo.query("#tableMicro").style("height",f);a[0]&&a[0].items[0]&&h.setUserInfo(a[0].items[0]);a=a[1]&&a[1].items?new o({data:a[1].items}):new o({});(new k({store:a,columns:b,options:d},"Grid_MicroStrategy")).startup();
dojo.query(".focus").connect("click",function(){var a=this.getAttribute("microCode"),b="";"\u672a\u5173\u6ce8"==dojo.byId(this.id).innerHTML?(b="1",dojo.byId(this.id).innerHTML="\u5df2\u5173\u6ce8",dojo.addClass(dojo.byId(this.id),"focus001")):(b="0",dojo.byId(this.id).innerHTML="\u672a\u5173\u6ce8",dojo.removeClass(dojo.byId(this.id),"focus001"));h.addOrDelAttention(g.dzhUserId,a,b)});dojo.query(".hand").connect("onclick",function(){var a=this.id,b=this.getAttribute("microCode"),c=this.getAttribute("thisVotesDiv");
h.addVotes(g.dzhUserId,b,a,c,function(a,b,c){a&&a.length&&2<=a.length?(dojo.byId(c).innerHTML=a[0],dojo.byId(b).innerHTML="+"+a[1],dojo.addClass(dojo.byId(b),"focus002")):alert("\u6bcf\u5929\u6700\u591a\u53ea\u80fd\u62955\u7968\u4e14\u4e0d\u80fd\u5bf9\u540c\u4e00\u7b56\u7565\u91cd\u590d\u6295\u7968!")})})})};return h});