/*
	Copyright (c) 2004-2011, The Dojo Foundation All Rights Reserved.
	Available via Academic Free License >= 2.1 OR the modified BSD license.
	see: http://dojotoolkit.org/license for details
*/

/*
	This is an optimized version of Dojo, built for deployment and not for
	development. To get sources and documentation, please visit:

		http://dojotoolkit.org
*/

//>>built
require({cache:{"dojox/kline/DataService":function(){define("dojox/kline/DataService",["dojo/_base/declare","dojo/_base/lang","dojo/_base/array","dojo/DeferredList","dojo/aspect"],function(E,b,k,l,d){return E("dojox.kline.DataService",null,{store:null,options:{obj:null,field:null,k_period:"1d",k_split:0,times:"",count:null,his_data:0},queryObj:{service:"quote",type:"klineex",response_times:1,response_mode:0},OverlapsObj:[],constructor:function(d,k){if(!k.obj)throw Error("obj must be provided! ");
this.store=d;this.options=b.mixin({},this.options,k);this.queryObj=b.mixin({},this.queryObj)},paramsConfig:function(){this.options.service&&(this.queryObj.service=this.options.service);this.options.type&&(this.queryObj.type=this.options.type);this.options.field&&(this.queryObj.field=this.options.field.join(","));this.options.k_period&&(this.queryObj.k_period=this.options.k_period);this.options.k_split&&(this.queryObj.k_split=this.options.k_split);this.options.count?(this.queryObj.start=-1*this.options.count,
this.queryObj.count=0):(delete this.queryObj.start,delete this.queryObj.count)},singleFetch:function(d){this.paramsConfig();var b=[],a="";this.options.times&&(a+=this.options.times.join(""));for(var g=0;g<this.options.obj.length;g++)b.push(this.options.obj[g].code);this.queryObj.where="obj="+b.join(",")+a;this.store.query(this.queryObj).then(function(a){a&&a[0]&&a[0].result&&a[0].result.datas&&d(a[0].result.datas)})},unReg:function(){var d=this.req_seq;store=this.store;store.cancel(d)},cycleFetch:function(b,
o){var a=this,g="";this.req_seq=0;this.paramsConfig();this.options.times&&(g+=this.options.times.join(""));var p=[],r=[];k.forEach(this.options.obj,function(a){r.push(a.code)});a.queryObj.where="obj="+r.join(",")+g;a.queryObj.response_times=1;g=a.store.query(a.queryObj);g instanceof Array||p.push(g);p.length?(new l(p)).then(function(g){g[0]&&g[0][1][0].result.datas.length&&k.forEach(g[0][1][0].result.datas,function(g){g&&g[1]&&(g[1].datas[0].unshift(g[0]),b(g[1],a.options.obj,a.options.k_period))});
if(!a.options.his_data)g=a.store,a.queryObj.response_times=-1,a.queryObj.start=-1,a.queryObj.count=1,g.query(a.queryObj),a.handler&&a.handler.remove(),g=d.after(g,"put",function(g,f){if((f=f[0])&&f.result&&f.result.datas&&1==f.result.datas.length){var p,d,r;p=f.result.datas[0][1].head;d=f.result.datas[0][1].datas[0];r=f.result.datas[0][0];p.unshift("obj");d.unshift(r);o({head:p,datas:[d]},a.options.obj,f.req_seq);a.req_seq=f.req_seq}}),a.handler=g}):this.store.data&&this.store.data.length&&k.forEach(this.store.data,
function(g){b(g,a.options.obj,a.options.k_period)})},toggleQuan:function(){this.options.k_split?this.options.k_split=0:this.options.k_split=1},changeTimeScale:function(d){this.options.k_period=d},changeObj:function(d){if(d instanceof Array)this.options.obj=d,this.OverlapsObj=d.slice(1)},changeTimeRange:function(d){this.options.times=d},addOverlapsObj:function(d){if(this.options.obj){for(var b=0,a=this.options.obj.length;b<a;b++)if(this.options.obj[b].code==d.code)return;for(b=0;b<this.OverlapsObj.length;b++)if(this.OverlapsObj[b].code==
d.code)return;this.OverlapsObj.push(d);this.options.obj.push(d)}},delOverlapsObj:function(){1<this.options.obj.length&&(this.OverlapsObj.pop(),this.options.obj.pop())},delAllOverlapsObj:function(){this.OverlapsObj=[];this.options.obj.length=1}})})},"dojox/kline/KlineUtil":function(){define(["dojo/_base/lang","dojo/_base/declare","../canvasDashedLine"],function(E,b,k){function l(a){return d.test(a)?a+0.5:a}var d=/^-?[1-9]\d*$/,n=[],o={"%Y-%m-%d %H:%M":function(a){a=new Date(a);return a.getFullYear()+
"-"+(100+a.getMonth()+1).toString().substring(1)+"-"+(100+a.getDate()).toString().substring(1)+" "+(100+a.getHours()).toString().substring(1)+":"+(100+a.getMinutes()).toString().substring(1)},"%H:%M":function(a){a=new Date(a);return(100+a.getHours()).toString().substring(1)+":"+(100+a.getMinutes()).toString().substring(1)},"%Y/%m/%d":function(a){a=new Date(a);return a.getFullYear()+"/"+(100+a.getMonth()+1).toString().substring(1)+"/"+(100+a.getDate()).toString().substring(1)}};return b("dojox.kline.KlineUtil",
[],{constructor:function(a){this.options=a},checkSameValueInArrs:function(a,g){var p=[],d={},b;b=g.join(" ");for(var k in a)-1!=b.indexOf(a[k])&&(p.push({mainIndex:k,value:a[k]}),d[a[k]]=p.length-1);for(var f in g)b=d[g[f]],void 0!=b&&(p[b].overlapsIndex=f);return p},isInArray:function(a,g,p){var d=typeof a;if("string"==d||"number"==d)for(var b in g)if(p){if(g[b][p]==a)return b}else if(g[b]==a)return b;return null},clearAll:function(a,g){var p=this.options;a.drawImage(g,0,0);a.clearRect(0,0,p.width,
p.height);a.fillStyle=p.plotCss.background;a.fillRect(0,0,p.width,p.height)},clear:function(a,g,p,d,b){var k=this.options;a.clearRect(g,p,d,b);a.fillStyle=k.plotCss.background;a.fillRect(g,p,d,b)},getCanvas:function(a,g,p){c=document.createElement("canvas");c.id=a;c.width=g;c.height=p;return c},getXaxisPos:function(a){var g=this.options,a=g.current.prepareDistance?a-g.leftOffset-Math.round(g.chartParams.cwidth/2)-g.current.prepareDistance:a-g.leftOffset-Math.round(g.chartParams.cwidth/2),a=Math.round(a/
g.chartParams.cwidth)+g.current.begin;return a<g.current.end&&a>=g.current.begin?a:null},getXaxisPosData:function(a){var g=this.options,p=this.getXaxisPos(a);if(null==p)return null;if(4==g.chartParams.type||5==g.chartParams.type){a=this.millisecond2Date("%H:%M",g.current.totalXaxis[p]);return a in g.current.trendTimeTsDataMapping?(n=[],n=[g.current.totalXaxis[p],g.current.trendTimeTsDataMapping[a].ohlc,g.current.trendTimeTsDataMapping[a].vol],[g.current.totalXaxis[p],g.current.trendTimeTsDataMapping[a].ohlc,
g.current.trendTimeTsDataMapping[a].vol]):n}return[g.current.ts[p],g.current.ohlc[p],g.current.vol[p]]},getXaxisPosIndi:function(a){var g=this.options,p=[],a=this.getXaxisPos(a);if(null==a)return null;if(g.current.indicators&&g.current.indicators.length)for(var d=0;d<g.current.indicators.length;d++)"vol"!=g.current.indicators[d].type&&p.push(g.current.indicators[d].data[a]);else p=null;return p},getXaxisPosMa:function(a){var g=this.options,p=[],d=[],a=this.getXaxisPos(a);if(null==a)return null;if("ma"in
g.current.overlays){d=g.current.overlays.ma;for(g=0;g<d.data.length;g++)p.push({prop:d.data[g].prop,data:d.data[g].data[a]?d.data[g].data[a]:d.data[g].data[d.data[g].data.length-1]})}else p=null;return p},drawRect:function(a,g,p,d,b,k){k?(g=l(g),p=l(p),a.strokeRect(g,p,d,b)):a.fillRect(g,p,d,b)},drawline:function(a,g,p,d,b,k,f){var q=a.lineWidth;a.lineWidth=f||1;a.strokeStyle=k||"#111111";a.beginPath();g=l(g);d=l(d);p=l(p);b=l(b);a.moveTo(g,p);a.lineTo(d,b);a.stroke();a.closePath();a.lineWidth=q},
drawLineWithArrow:function(a,g,p,d,b,k,f,q){var o=a.lineWidth;a.lineWidth=f||1;a.strokeStyle=k||"#111111";a.beginPath();g=l(g);d=l(d);p=l(p);b=l(b);a.moveTo(g,p);a.lineTo(d,b);"left"==q?(a.moveTo(g,p),a.lineTo(g+10,p-5),a.moveTo(g,p+0.5),a.lineTo(g+10,p+5)):(a.moveTo(d,b+0.5),a.lineTo(d-10,b-5),a.moveTo(d,b+0.5),a.lineTo(d-10,b+5));a.stroke();a.closePath();a.lineWidth=o},drawText:function(a,g,d,b,k){var l=this.options,f=l.plotCss,f=k.color||f.label,q=k.padding||2,o=k.align||"start",n=k.textBaseline||
"bottom";a.font=k.font||"10pt Arial bold";a.textAlign=o;a.textBaseline=n;var k=d+2*q+a.measureText(g).width,h=15;"top"==n&&(h*=-1);"right"==o&&(k*=-1);a.fillStyle=l.plotCss.background;a.fillRect(d+q-1,b-h,k,15);a.fillStyle=f;a.fillText(g,d+q,b);return k},drawDashes:function(a,g,d,b,o,n){g=l(g);b=l(b);d=l(d);o=l(o);k.drawDashedPolyLine(a,[[g,d],[b,o]],{color:n})},minmax2d:function(a){var g=-Infinity,d=Infinity,b;for(b in a)for(j in a[b])a[b][j]>=g&&(g=a[b][j]),a[b][j]<d&&(d=a[b][j]);return[d,g]},minmax1d:function(a){var g=
-Infinity,d=Infinity,b;for(b in a)a[b]>=g&&(g=a[b]),a[b]<d&&(d=a[b]);return[d,g]},removeArrByIndex:function(a,g){if(isNaN(g)||g>a.length)return!1;for(var d=0,b=0;d<a.length;d++)a[d]!=a[g]&&(a[b++]=a[d]);a.length-=1},ElemPageOffsetX:function(a){var g=0;do g+=a.offsetLeft;while(a=a.offsetParent);return g},ElemPageOffsetY:function(a){var g=0;do g+=a.offsetTop;while(a=a.offsetParent);return g},canvasOffsetX:function(a,g){var d=0;do d+=g.offsetLeft;while(g=g.offsetParent);return a-d},canvasOffsetY:function(a,
g){var d=0;do d+=g.offsetTop;while(g=g.offsetParent);return a-d},from5StrToHM:function(a,g){var d=Math.floor(g/3600),d=(100+d).toString().substring(1);24<=d&&(d=(100+(d-24)).toString().substring(1));var b=(100+Math.floor(g%3600/60)).toString().substring(1);if("%h:%m"==a)return d+":"+b;if("%h%m"==a)return d+""+b},fromHMTo5Str:function(a){a=a.split(":");if(1<a.length)return 3600*a[0]+60*a[1]},date2Millisecond:function(a){var g;g=(new Date(a)).getTime();if(!isNaN(g))return g;a=a.replace(/-/g," ");g=
(new Date(a)).getTime();if(!isNaN(g)||1E5<(g=parseInt(a)))return g},millisecondChange:function(a,g){var d=this.options,a=a+"",b=(new Date).getTimezoneOffset()/60;g&&(b=0);if(10==a.length)a*=1E3;else if(5==a.length||6==a.length)a=d.current.date?1E3*a+(new Date(d.current.date)).setHours(0,0,0,0):1E3*a+(new Date).setHours(0,0,0,0),b=0;return 1*a+36E5*b},millisecond2Date:function(a,g,d,b){function k(h,i){if(2==i)return(100+h).toString().substring(1);if(3==i)return(1E3+h).toString().substring(1);h=h.toString().replace(/^([0-9])$/,
"0$1");3===i&&(h=h.toString().replace(/^([0-9]{2})$/,"0$1"));return h}var l=this.options,g=this.millisecondChange(g,b);if(o[a])return o[a](g);if(!(void 0!==g&&null!==g)||isNaN(g))return"Invalid date";var a=function(){var h=arguments,i,a,g=h.length;for(i=0;i<g;i++)if(a=h[i],"undefined"!==typeof a&&null!==a)return a}(a,"%Y-%m-%d %H:%M:%S"),b=new Date(g),f,q=b.getHours(),n=b.getDay(),u=b.getDate(),h=b.getMonth(),i=b.getFullYear(),v=l.dateParams.months,g={a:l.dateParams.weekdays[n],d:k(u),e:u,b:v[h].substr(0,
3),B:v[h],m:k(h+1),y:i.toString().substr(2,2),Y:i,H:k(q),I:k(q%12||12),l:q%12||12,M:k(b.getMinutes()),P:12>q?"AM":"PM",p:12>q?"am":"pm",S:k(b.getSeconds()),L:k(g%1E3,3)};for(f in g)a=a.replace("%"+f,g[f]);return d?a.substr(0,1).toUpperCase()+a.substr(1):a}})})},"dojox/canvasDashedLine":function(){define("dojox/canvasDashedLine",[],function(){var E=function(){};E.prototype={defaultLineStyle:{pattern:"***--***--",color:"#5f5d5b",width:1,scale:8,join:"bevel",cap:"butt"},prepareLineStyle:function(b){if(null==
b)return this.defaultLineStyle;if(void 0==b.pattern||null==b.pattern)b.pattern=this.defaultLineStyle.pattern;if(void 0==b.scale||null==b.scale)b.scale=this.defaultLineStyle.scale;if(void 0==b.color||null==b.color)b.color=this.defaultLineStyle.color;if(void 0==b.width||null==b.width)b.width=this.defaultLineStyle.width;if(void 0==b.cap||null==b.cap)b.cap=this.defaultLineStyle.cap;if(void 0==b.join||null==b.join)b.join=this.defaultLineStyle.join;return b},distance:function(b,k){return Math.sqrt(Math.pow(k[0]-
b[0],2)+Math.pow(k[1]-b[1],2))},firstPattern:function(b,k){if(1<=k)return b;for(var l=0,d=[],n=0,o=b.length;n<o;n++)l+b[n].length>k&&(0==d.length?d.push({type:b[n].type,length:b[n].length-(k-l)}):d.push(b[n])),l+=b[n].length;return d},strToPattern:function(b){for(var b=b.split(""),k=null,l=[],d=0,n=b.length;d<n;d++){var o=b[d];o==k?l[l.length-1].length++:"*"==o?l.push({type:"line",length:1}):l.push({type:"space",length:1});k=b[d]}d=0;for(n=l.length;d<n;d++)l[d].length/=b.length;return l},drawPolyLine:function(b,
k,l){b.save();b.strokeStyle=l.color;b.lineWidth=l.width;b.lineCap=l.cap;b.lineJoin=l.join;b.beginPath();b.moveTo(k[0][0],k[0][1]);for(var l=0,d=k.length;l<d;l++)b.lineTo(k[l][0],k[l][1]);b.stroke();b.restore()},dashedLine:function(b,k,l,d){void 0==d&&(d=0);var n=this.strToPattern(l.pattern),o=this.distance(b,k),a=(k[0]-b[0])/o,o=(k[1]-b[1])/o,g=b[0],b=b[1],p=0,r=null,C=!1,s,f=[];a:for(;;){r=0==p?d:0;0==p?(s=this.firstPattern(n,d),0==s.length&&(s=n)):s=n;for(var q=0,K=s.length;q<K;q++){var u=a*s[q].length*
l.scale,h=o*s[q].length*l.scale;if(1E4<p||0<a&&g+u>=k[0]||0==o&&0<a&&g+u>=k[0]||0>a&&g+u<=k[0]||0==o&&0>a&&g+u<=k[0]||0<o&&b+h>=k[1]||0==a&&0<o&&b+h>=k[1]||0>o&&b+h<=k[1]||0==a&&0>o&&b+h<=k[1])C=!0;C&&(u=k[0]-g,h=k[1]-b,d=r+this.distance([g,b],k)/l.scale);"line"==s[q].type&&f.push([[g,b],[g+u,b+h]]);if(C)break a;g+=u;b+=h;r+=s[q].length;p++}}return{startPosition:d,lines:f}},drawLineFragments:function(b,k,l){for(var d in k)this.drawPolyLine(b,k[d],l)},connectAdjacentLines:function(b,k){var l=b[b.length-
1].length;b[b.length-1][l-1][0]==k[0][0][0]&&b[b.length-1][l-1][1]==k[0][0][1]&&(b[b.length-1].push(k[0][1]),k.shift())},dashedPolyLine:function(b,k){for(var l=0,d=[],n=null,o=0,a=b.length-1;o<a;o++)if(n=this.dashedLine(b[o],b[o+1],k,l),l=n.startPosition,0<n.lines.length){0<d.length&&this.connectAdjacentLines(d,n.lines);for(var g=0,p=n.lines.length;g<p;g++)d.push(n.lines[g])}return d},drawDashedPolyLine:function(b,k,l){l=this.prepareLineStyle(l);k=this.dashedPolyLine(k,l);this.drawLineFragments(b,
k,l)}};return new E})},"dojox/kline/KlineDataHandle":function(){define(["dojo/_base/lang","dojo/_base/declare"],function(E,b){return b("dojox.kline.KlineDataHandle",[],{constructor:function(b,l){this.options=b;this.tickerUtil=l},transformData4Acube:function(b,l){var d=this.options,n=this.tickerUtil,o={};if(l.length){if(b&&b.head&&b.head.length)for(var a=0;a<b.head.length;a++)o[b.head[a]]=a;var g=[],p=[],r=[],C=!1;if(b&&b.datas&&b.datas.length)for(var s=b.datas[0].shift(),a=0;a<b.datas.length;a++)g[a]=
n.date2Millisecond(b.datas[a][o[d.titlesParaphrase.time]]),p[a]=[parseFloat(b.datas[a][o[d.titlesParaphrase.open]]),parseFloat(b.datas[a][o[d.titlesParaphrase.high]]),parseFloat(b.datas[a][o[d.titlesParaphrase.low]]),parseFloat(b.datas[a][o[d.titlesParaphrase.close]])],r[a]=parseFloat(b.datas[a][o[d.titlesParaphrase.volume]]);if(s==l[0].code){if(d.current?(d.current.code=l[0].code,d.current.label=l[0].code,d.current.timeScale=d.chartParams.timeScale,d.current.ts=g,d.current.ohlc=p,d.current.vol=r,
d.current.overlays=d.current.overlays,d.current.indicators=d.current.indicators):d.current={code:l[0].code,label:l[0].code,timeScale:d.chartParams.timeScale,ts:g,ohlc:p,vol:r,overlays:{},indicators:[]},0==d.chartParams.overlapsType)d.chartParams.overlapsType=1}else if(-1!=JSON.stringify(l).indexOf(s))if(0==d.overlaps.length)d.overlaps.push({code:s,label:s,timeScale:d.chartParams.timeScale,ts:g,ohlc:p,vol:r});else{for(a=0;a<d.overlaps.length;a++)if(d.overlaps[a].code==s){d.overlaps[a]={code:s,label:s,
timeScale:d.chartParams.timeScale,ts:g,ohlc:p,vol:r};C=!0;break}C||d.overlaps.push({code:s,label:s,timeScale:d.chartParams.timeScale,ts:g,ohlc:p,vol:r})}}},transformRealData4Acube:function(b,l){var d=this.options,n=this.tickerUtil,o={},a={},g,p,r;if(b&&b.head&&b.head.length)for(var C=0;C<b.head.length;C++)a[b.head[C]]=C;if(b&&b.datas&&b.datas.length)for(C=0;C<b.datas.length;C++){var s=b.datas[C];r=s[a[d.titlesParaphrase.obj]];if(l[0].code==r)if(g=d.current.ts[d.current.ts.length-1],p=n.millisecond2Date("%Y-%m-%d %H:%M",
parseInt(s[a[d.titlesParaphrase.time]])),g=n.millisecond2Date("%Y-%m-%d %H:%M",g),g==p)d.current.ohlc[d.current.ohlc.length-1][0]=parseFloat(s[a[d.titlesParaphrase.open]]),d.current.ohlc[d.current.ohlc.length-1][1]=parseFloat(s[a[d.titlesParaphrase.high]]),d.current.ohlc[d.current.ohlc.length-1][3]=parseFloat(s[a[d.titlesParaphrase.close]]),d.current.ohlc[d.current.ohlc.length-1][2]=parseFloat(s[a[d.titlesParaphrase.low]]),d.current.vol[d.current.vol.length-1]=parseFloat(s[a[d.titlesParaphrase.volume]]),
d.current.ts[d.current.ts.length-1]=s[a[d.titlesParaphrase.time]],o.main={shift:0};else{if(g<p)d.current.ohlc.push([parseFloat(s[a[d.titlesParaphrase.open]]),parseFloat(s[a[d.titlesParaphrase.high]]),parseFloat(s[a[d.titlesParaphrase.low]]),parseFloat(s[a[d.titlesParaphrase.close]])]),d.current.vol.push(s[a[d.titlesParaphrase.volume]]),d.current.ts.push(s[a[d.titlesParaphrase.time]]),o.main={shift:-1}}else for(var f=0;f<d.overlaps.length;f++)if(d.overlaps[f].code==r)if(g=d.overlaps[f].ts[d.overlaps[f].ts.length-
1],p=n.millisecond2Date("%Y-%m-%d %H:%M",parseInt(s[a[d.titlesParaphrase.time]])),g=n.millisecond2Date("%Y-%m-%d %H:%M",g),g==p)d.overlaps[f].ohlc[d.overlaps[f].ohlc.length-1][0]=parseFloat(s[a[d.titlesParaphrase.open]]),d.overlaps[f].ohlc[d.overlaps[f].ohlc.length-1][1]=parseFloat(s[a[d.titlesParaphrase.high]]),d.overlaps[f].ohlc[d.overlaps[f].ohlc.length-1][3]=parseFloat(s[a[d.titlesParaphrase.close]]),d.overlaps[f].ohlc[d.overlaps[f].ohlc.length-1][2]=parseFloat(s[a[d.titlesParaphrase.low]]),d.overlaps[f].vol[d.overlaps[f].vol.length-
1]=parseFloat(s[a[d.titlesParaphrase.volume]]),d.overlaps[f].ts[d.overlaps[f].ts.length-1]=s[a[d.titlesParaphrase.time]],o.overlaps={shift:0};else if(g<p)d.overlaps[f].ohlc.push([parseFloat(s[a[d.titlesParaphrase.open]]),parseFloat(s[a[d.titlesParaphrase.high]]),parseFloat(s[a[d.titlesParaphrase.low]]),parseFloat(s[a[d.titlesParaphrase.close]])]),d.overlaps[f].vol.push(s[a[d.titlesParaphrase.volume]]),d.overlaps[f].ts.push(s[a[d.titlesParaphrase.time]]),o.overlaps={shift:-1}}return o},transformGeneralData:function(b){for(var l=
this.options,d=this.tickerUtil,n=0;n<b.length;n++){var o={},a=b[n];if(a&&a.head&&a.head.length){for(n=0;n<a.head.length;n++)o[a.head[n]]=n;var g=[],p=[],r=[];if(a&&a.datas&&a.datas.length)for(var C=a.datas[0][o[l.titlesParaphrase.obj]],n=0;n<a.datas.length;n++)g[n]=d.date2Millisecond(a.datas[n][o[l.titlesParaphrase.time]]),p[n]=[parseFloat(a.datas[n][o[l.titlesParaphrase.open]]),parseFloat(a.datas[n][o[l.titlesParaphrase.high]]),parseFloat(a.datas[n][o[l.titlesParaphrase.low]]),parseFloat(a.datas[n][o[l.titlesParaphrase.close]])],
r[n]=parseFloat(a.datas[n][o[l.titlesParaphrase.volume]]);l.current?(l.current.code=C,l.current.label=C,l.current.timeScale=l.chartParams.timeScale,l.current.ts=g,l.current.ohlc=p,l.current.vol=r,l.current.overlays=l.current.overlays,l.current.indicators=l.current.indicators,l.current.tradeTime=a.tradeTime,l.current.prevClose=a.PREV_CLOSE):l.current={code:C,label:C,timeScale:l.chartParams.timeScale,ts:g,ohlc:p,vol:r,overlays:{},indicators:[],tradeTime:a.tradeTime,prevClose:a.PREV_CLOSE}}else{g=[];
p=[];r=[];if(a&&a.datas&&a.datas.length){C=a.datas[0][0];for(n=0;n<a.datas.length;n++)g[n]=d.date2Millisecond(a.datas[n][1]),p[n]=[parseFloat(a.datas[n][2]),parseFloat(a.datas[n][3]),parseFloat(a.datas[n][4]),parseFloat(a.datas[n][5])],r[n]=parseFloat(a.datas[n][6])}l.current?(l.current.code=a.code,l.current.label=a.label,l.current.timeScale=l.chartParams.timeScale,l.current.ts=g,l.current.ohlc=p,l.current.vol=r,l.current.overlays=l.current.overlays,l.current.indicators=l.current.indicators,l.current.tradeTime=
a.tradeTime,l.current.prevClose=a.PREV_CLOSE):l.current={code:C,label:C,timeScale:l.chartParams.timeScale,ts:g,ohlc:p,vol:r,overlays:{},indicators:[],tradeTime:a.tradeTime,prevClose:a.PREV_CLOSE}}}}})})},"dojox/kline/KlineIndicatorHandle":function(){define("dojo/_base/declare,dojo/dom,dojo/dom-construct,dojo/dom-style,dojo/cssScale,dojo/_base/connect".split(","),function(E,b,k,l,d,n){function o(a,g){var b=[],d=2/(g+1);b[0]=a[0];for(var k=1;k<a.length;k++)b[k]=void 0===a[k]||null===a[k]?b[k-1]:b[k-
1]?d*a[k]+(g-1)/(g+1)*b[k-1]:a[k];return b}return E("dojox.kline.KlineIndicatorHandle",[],{constructor:function(a,g,b,d){this.options=a;this.tickerUtil=g;this.$container=b;this.klineMain=d},vol:function(){var a=this.options,g=!0,b={type:"vol",data:a.current.vol,str:"\u6210\u4ea4\u91cf"},d;for(d in a.current.indicators)if("vol"==a.current.indicators[d].type){a.current.indicators[d].data=a.current.vol;g=!1;break}g&&(a.current.indicators.push(b),a.chartParams.numindicators+=1);return g},ma:function(a){var g=
this.options,b=this.tickerUtil,d=g.current.ohlc,k=[],l=[],f="",q=[],o=0,q=[];if(a)for(var n=0;n<a.length;n++){l=[];f=parseInt(a[n]);for(i=0;i<d.length;i++)if(i<f)l[i]=void 0;else{var q=d.slice(i-f,i+1),o=0,h;for(h in q)o+=q[h][3];l[i]=o/(f+1)}q=b.minmax1d(l);k.push({prop:"ma"+f+":",data:l,min:q[0],max:q[1],period:f})}else{for(var i in d)o+=d[i][3],l[i]=o/(1*i+1);q=b.minmax1d(l);k.push({prop:"ma"+f+":",data:l,min:q[0],max:q[1],period:f})}g.current.overlays.ma={data:k};g.chartParams.numoverlays+=1},
macd:function(a,g,b,d){var k=this.options,a=a||k.current.ohlc,l,f;for(f in k.current.indicators)"macd"==k.current.indicators[f].type&&(g||(g=k.current.indicators[f].args[0]),b||(b=k.current.indicators[f].args[1]),d||(d=k.current.indicators[f].args[2]),l=f);var q="MACD("+g+","+b+","+d+")",n=[];for(f=0;f<a.length;f++)n.push(a[f][3]);a=o(n,g);n=o(n,b);for(f=0;f<a.length;f++)a[f]-=n[f];var n=o(a,d),u=[];for(f=0;f<a.length;f++)u[f]=[a[f],n[f],2*(a[f]-n[f]),q+" DIFF:"+a[f].toFixed(k.current.fixNum)+" DEA:"+
n[f].toFixed(k.current.fixNum)+" MACD:"+(2*(a[f]-n[f])).toFixed(k.current.fixNum)];f={type:"macd",data:u,str:u[u.length-1][3],args:[g,b,d]};l?k.current.indicators[l]=f:(k.current.indicators.push(f),k.chartParams.numindicators+=1)},yAxisPlot:function(a,g,b,d,k,l,f){var q=this.options,n=this.tickerUtil,o=q.leftOffset+q.plotWidth,h=d-b,i=(k-q.topSpacing)/h,v=Math.floor(q.topMargin+q.plotHeight+k*l),l=q.topMargin+q.plotHeight+k*(l-1);switch(g){case "macd":var g=Math.round((0-b)*i),g=v-g,e;for(e in q.current.indicators)if("macd"==
q.current.indicators[e].type)q.current.indicators[e].ymin=b,q.current.indicators[e].ymax=d,q.current.indicators[e].everyHeight=k-q.topSpacing,q.current.indicators[e].yAxisEnd=v,q.current.indicators[e].fixNum=f,q.current.indicators[e].yAxisRange=h,q.current.indicators[e].flag=1;e=0;b=Math.round(g+q.bglineSpace*e);d=Math.round(g-q.bglineSpace*e);do k=(q.bglineSpace*e/i).toFixed(f),b<=v&&("dashed"==q.plotCss.backgroundGrid.type?n.drawDashes(a,q.leftOffset,b,o,b,q.plotCss.backgroundGrid.color,1):n.drawline(a,
q.leftOffset,b,o,b,q.plotCss.backgroundGrid.color),n.drawText(a,-1*k,o,b,{align:"left",padding:5,color:q.plotCss.yAxisLabel.color,textBaseline:"middle"})),d>=l+q.topSpacing&&("dashed"==q.plotCss.backgroundGrid.type?n.drawDashes(a,q.leftOffset,d,o,d,q.plotCss.backgroundGrid.color,1):n.drawline(a,q.leftOffset,d,o,d,q.plotCss.backgroundGrid.color),n.drawText(a,k,o,d,{align:"left",padding:5,color:q.plotCss.yAxisLabel.color,textBaseline:"middle"})),e++,b=Math.round(g+q.bglineSpace*e),d=Math.round(g-q.bglineSpace*
e);while(b<=v||d>=l+q.topSpacing);break;case "vol":for(e in q.current.indicators)if("vol"==q.current.indicators[e].type)q.current.indicators[e].yAxisRange=h,q.current.indicators[e].ymin=0,q.current.indicators[e].ymax=d,q.current.indicators[e].fixNum=f,q.current.indicators[e].everyHeight=k-q.topSpacing,q.current.indicators[e].yAxisEnd=v,q.current.indicators[e].flag=0;e=0;f=q.bglineSpace;b=Math.round(v-f*e);v-f<l+q.topSpacing&&(f=k/3,v-2*f<l+q.topSpacing&&(f=v-l-q.topSpacing));h=1;0<f/i/100?(h=100,
d="x100"):d="x1";do k=parseInt(f*e/i/h),"dashed"==q.plotCss.backgroundGrid.type?n.drawDashes(a,q.leftOffset,b,o,b,q.plotCss.backgroundGrid.color,1):n.drawline(a,q.leftOffset,b,o,b,q.plotCss.backgroundGrid.color),0==e?(k=d,g="bottom"):(k=k?k:e,g="middle"),n.drawText(a,k,o,b,{align:"left",padding:5,color:q.plotCss.yAxisLabel.color,textBaseline:g}),e++,b=v-f*e;while(b>=l+q.topSpacing)}},addIndicatorBtn:function(a,g,p,o,C,s){var f=this.options,q=this.tickerUtil,E=this.klineMain,u=a.id+"_delIndi_"+g,h=
b.byId(u);if(h)a=h.offsetWidth,a=o.canvas.offsetLeft?d.scale(f.leftOffset+f.plotWidth-a,"x")+o.canvas.offsetLeft:d.scale(f.leftOffset+f.plotWidth-a,"x"),p=o.canvas.offsetTop?d.scale(p,"y")+o.canvas.offsetTop:d.scale(p,"y"),l.set(h,{top:p+"px",left:a+"px","-webkit-transform":"scale("+1/d.getScaleX()+","+1/d.getScaleY()+")"});else{var i=k.toDom('<div id="'+u+'" style="border-width:0px 0px 1px 1px;border-style:solid;border-color: '+f.plotCss.stroke+";text-align:center;color:"+f.plotCss.stroke+";position:absolute;z-index:"+
(f.baseZ+3)+';cursor:pointer;width:15px;height:15px;-webkit-transform-origin:left top;" ><div style="line-height:15px">x</div></div>');n.connect(i,"click",function(){for(var h=0;h<f.current.indicators.length;h++)if(f.current.indicators[h].type==g){q.removeArrByIndex(f.current.indicators,h);f.chartParams.numindicators-=1;break}h=f.height-f.topMargin-f.bottomMargin;if(0==f.chartParams.numindicators)f.subPlotHeight=0,f.plotHeight=h-f.subPlotHeight;else if(1==f.chartParams.numindicators)f.subPlotHeight=
h/3,f.plotHeight=h-f.subPlotHeight;else if(2==f.chartParams.numindicators)f.subPlotHeight=(f.subPlotHeight+f.height/10)/f.chartParams.numindicators,f.plotHeight=h-f.subPlotHeight*f.chartParams.numindicators;else if(3<=f.chartParams.numindicators)f.plotHeight=f.height/2.5,f.subPlotHeight=(h-f.plotHeight)/f.chartParams.numindicators;k.destroy(i);s.call(E,o,C)});a.appendChild(i);a=i.offsetWidth;a=o.canvas.offsetLeft?d.scale(f.leftOffset+f.plotWidth-a,"x")+o.canvas.offsetLeft:d.scale(f.leftOffset+f.plotWidth-
a,"x");p=o.canvas.offsetTop?d.scale(p,"y")+o.canvas.offsetTop:d.scale(p,"y");l.set(i,{top:p+"px",left:a+"px","-webkit-transform":"scale("+1/d.getScaleX()+","+1/d.getScaleY()+")"})}},plotIndicator:function(a,b,d,k,l,o){var f=this.options,n=this.tickerUtil,E=this.$container,u=b.data,h=b.type,b=b.str,i=f.current.begin,v=f.current.ymin,e=f.current.end,B=f.current.ymax,D=f.leftOffset,F=Math.round(f.plotWidth),w=f.topMargin+f.plotHeight+f.subPlotHeight*(d-1),G=Math.round(f.subPlotHeight),m=Math.round(f.chartParams.cwidth/
1.6);0==m%2&&(m-=1);var J=Math.round(m/2)-1;1>=m&&(m=1,J=0);switch(h){case "macd":var v=Math.floor(f.topMargin+f.plotHeight+f.subPlotHeight*d),h=n.minmax2d(u.slice(i,e)),I=h[1],h=h[0],B=I-h,I=I+0.1*B,h=h-0.1*B,B=(f.subPlotHeight-f.topSpacing)/(I-h);prevxy=[];this.yAxisPlot(a,"macd",h,I,f.subPlotHeight,d,f.current.fixNum);a.strokeStyle=f.plotCss.stroke;a.strokeRect(D,w,F,G);n.drawText(a,b,D,w+f.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53"});for(D=i;D<e;D++)if(u[D]&&
void 0!==u[D][0])b=D-i,d=Math.floor(b*f.chartParams.cwidth+f.leftOffset),b=d+J,F=Math.round((u[D][0]-h)*B),G=Math.round((u[D][1]-h)*B),I=Math.round((0-h)*B),prevxy[0]&&(n.drawline(a,prevxy[0][0],prevxy[0][1],b,v-F,f.plotCss.macd[0],1),n.drawline(a,prevxy[1][0],prevxy[1][1],b,v-G,f.plotCss.macd[1],1)),a.fillStyle=f.plotCss.stroke,0<F-G?(a.fillStyle=f.plotCss.volUpStyle.color,a.fillRect(d,v-I-2*(F-G)+1,m,2*(F-G))):(a.fillStyle=f.plotCss.volDownStyle.color,a.fillRect(d,v-I,m,2*(G-F))),prevxy=[[b,v-F],
[b,v-G]];this.addIndicatorBtn(E,"macd",w,a,l,k,o);break;case "vol":a.strokeStyle=f.plotCss.stroke;a.strokeRect(D,w,F,G);n.drawText(a,b,D,w+f.topSpacing,{align:"left",font:"10pt Arial"});J=(f.subPlotHeight-f.topSpacing-f.bottomSpacing)/(B-v);b=n.minmax1d(u.slice(i,e))[1];h=(f.subPlotHeight-f.topSpacing)/(b-0);B=Math.floor(f.topMargin+f.plotHeight+f.subPlotHeight*d);this.yAxisPlot(a,"vol",0,b,f.subPlotHeight,d,0);for(b=i;b<e;b++)Math.round((f.current.ohlc[b][0]-v)*J),Math.round((f.current.ohlc[b][1]-
v)*J),Math.round((f.current.ohlc[b][2]-v)*J),Math.round((f.current.ohlc[b][3]-v)*J),d=Math.floor((b-i)*f.chartParams.cwidth+f.leftOffset),f.current.ohlc[b][0]>f.current.ohlc[b][3]?"stroke"==f.plotCss.downStyle.candle.type?(a.strokeStyle=f.plotCss.volDownStyle.color,u[b]&&(D=Math.round(u[b]*h),n.drawRect(a,d,B-D,m-1,D,!0))):(a.fillStyle=f.plotCss.volDownStyle.color,u[b]&&(D=Math.round(u[b]*h),n.drawRect(a,d,B-D,m,D,!1))):f.current.ohlc[b][0]==f.current.ohlc[b][3]?(a.strokeStyle=f.plotCss.volFairStyle.color,
u[b]&&(D=Math.round(u[b]*h),n.drawRect(a,d,B-D,m-1,D,!0))):"stroke"==f.plotCss.upStyle.candle.type?(a.strokeStyle=f.plotCss.volUpStyle.color,u[b]&&(D=Math.round(u[b]*h),n.drawRect(a,d,B-D,m-1,D,!0))):(a.fillStyle=f.plotCss.volUpStyle.color,u[b]&&(D=Math.round(u[b]*h),n.drawRect(a,d,B-D,m,D,!1)));this.addIndicatorBtn(E,"vol",w,a,l,k,o)}}})})}}});
define("dojox/kline/Kline","dojo/_base/declare,dojo/cssScale,dojo/_base/lang,dojo/Deferred,dojo/DeferredList,dojo/dom,dojo/dom-style,dojo/dom-attr,dojo/dom-class,dojo/dom-construct,dojo/dom-prop,dojo/_base/array,dijit/_Widget,dojox/kline/DataService,dojox/kline/KlineUtil,dojox/kline/KlineDataHandle,dojox/kline/KlineIndicatorHandle".split(","),function(E,b,k,l,d,n,o,a,g,p,r,C,s,f,q,K,u){return E("dojox.kline.Kline",[s],{defaultsOptions:{plotCss:{timetrend:"#FFFFFF",timetrendFillColors:["#131313","#0073ff"],
timetrendFillAlpha:0.7,label:"#5F5E5E",copyrighttext:"#FFFFFF",stroke:"#686868",background:"#FFFFFF",backgroundGrid:{type:"dashed",color:"#CFCFCF"},xAxisLabel:{color:"#606060"},yAxisLabel:{color:"#606060"},volUpStyle:{color:"#9C0D0D"},volDownStyle:{color:"#14641E"},volFairStyle:{color:"#868686"},upStyle:{candle:{type:"stroke",color:"#CC4642"}},downStyle:{candle:{type:"fill",color:"#55710B"}},fairStyle:{candle:{type:"fill",color:"#C67413"}},overlaps:[{upStyle:{candle:{type:"stroke",color:"#5F9EA0"}},
downStyle:{candle:{type:"fill",color:"#5F9EA0"}}},{upStyle:{candle:{type:"stroke",color:"#C67413"}},downStyle:{candle:{type:"fill",color:"#C67413"}}},{upStyle:{candle:{type:"stroke",color:"#C68813"}},downStyle:{candle:{type:"fill",color:"#C69913"}}}],tooltip:{width:"auto",height:"auto",padding:"1px",border:"#3C72AE solid 1px",opacity:0.85,background:"#3C72AE",radius:"6px",textAlign:"center",lineHeight:1.6,padding:"4px",time:{cssText:"color: #FFC13B; font-size: 12px;font-family: Inconsolata,\u5b8b\u4f53"},
title:{cssText:"color: #FFFFFF; font-size: 12px;white-space: nowrap;font-family: Inconsolata,\u5b8b\u4f53"},content:{cssText:"color: #FFFFFF; font-size: 12px;font-family: Inconsolata,\u5b8b\u4f53"}},crosshair:{h_cssText:"border-top: 1px solid #3C72AE; height: 1px; padding: 2px 0; clear: both; display: block; overflow: hidden;",v_cssText:"border-left: 1px solid #3C72AE; width: 1px;  padding: 0 2px;"},crosslabels:{x:"background:#FFFFFF;color:#3C72AE;border:1px solid #3C72AE;",y:"background:#FFFFFF;color:#3C72AE;border:1px solid #3C72AE;"},
ma:"#9B9B9B,#BC6111,#835BE8,#CB2BC6,#5217DB,#18E197,#DED71F,#DE521F,#10F5B8,#A6ACE2,#DF9FB0".split(","),macd:["#9B9B9B","#BC6111","#835BE8"]},chartParams:{overlapsType:0,isDrag:0,type:1,minwidth:5,isNewTip:!0,isShowCtMenu:!1,timetrendType:"1",timetrendIsFill:!1,timeScaleFormatter:{timeline:{txt:"\u5206\u65f6\u8d70\u52bf",formatter:"%H:%M"},"1m":{txt:"1\u5206\u949fK\u7ebf\u56fe",formatter:"%H:%M"},"5m":{txt:"5\u5206\u949fK\u7ebf\u56fe",formatter:"%H:%M"},"15m":{txt:"15\u5206\u949fK\u7ebf\u56fe",formatter:"%H:%M"},
"30m":{txt:"30\u5206\u949fK\u7ebf\u56fe",formatter:"%H:%M"},"60m":{txt:"60\u5206\u949fK\u7ebf\u56fe",formatter:"%H:%M"},"1d":{txt:"\u65e5K\u7ebf\u56fe",formatter:"%Y-%m-%d"},"1w":{txt:"\u5468K\u7ebf\u56fe",formatter:"%Y-%m-%d"},"1M":{txt:"\u6708K\u7ebf\u56fe",formatter:"%Y-%m-%d"},"1q":{txt:"\u5b63\u5ea6K\u7ebf\u56fe",formatter:"%Y-%m-%d"},"2q":{txt:"\u534a\u5e74K\u7ebf\u56fe",formatter:"%Y"},"1y":{txt:"\u5e74K\u7ebf\u56fe",formatter:"%Y"}}},dateParams:{months:"\u4e00\u6708,\u4e8c\u6708,\u4e09\u6708,\u56db\u6708,\u4e94\u6708,\u516d\u6708,\u4e03\u6708,\u516b\u6708,\u4e5d\u6708,\u5341\u6708,\u5341\u4e00\u6708,\u5341\u4e8c\u6708".split(","),
weekdays:"\u65e5,\u4e00,\u4e8c,\u4e09,\u56db,\u4e94,\u516d".split(",")},titlesParaphrase:{obj:"obj",time:"time",open:"open",high:"high",low:"low",close:"close",volume:"volume",amount:"amount",tickCount:"tickCount"}},id:"",constructor:function(h){if(!h.store)throw Error("store must be provided!");var i=this.options={},h=k.mixin({},h);this.dataService=new f(h.store,h.query);i.store=h.store;i.query=k.mixin({},h.query);i.rightMargin=h.rightMargin?h.rightMargin:65;i.topMargin=h.topMargin?h.topMargin:10;
i.bottomMargin=h.bottomMargin?h.bottomMargin:20;i.leftOffset=h.leftOffset?h.leftOffset:55;i.topSpacing=h.topSpacing?h.topSpacing:20;i.bottomSpacing=h.bottomSpacing?h.bottomSpacing:15;i.baseZ=h.baseZ?h.baseZ:500;i.copyrighttext=h.copyrighttext?h.copyrighttext:"\u00a9 shihua.com.cn";i.chartParams=h.chartParams?k.mixin({},this.defaultsOptions.chartParams,h.chartParams):k.mixin({},this.defaultsOptions.chartParams);i.plotCss=h.plotCss?k.mixin({},this.defaultsOptions.plotCss,h.plotCss):k.mixin({},this.defaultsOptions.plotCss);
i.dateParams=k.mixin({},this.defaultsOptions.dateParams);i.titlesParaphrase=k.mixin({},this.defaultsOptions.titlesParaphrase);i.chartParams.numindicators=0;i.chartParams.numoverlays=0;i.overlaps=[]},postCreate:function(){this.options.width=o.get(this.domNode,"width");this.options.height=o.get(this.domNode,"height");this._initDom();this._initCanvas()},startup:function(){var h=this.options;this._getData();4!=h.chartParams.type&&5!=h.chartParams.type&&h.chartParams.isShowCtMenu&&this.initContextMenu()},
initContextMenu:function(){var h=this;require(["dijit/Menu","dijit/MenuItem","dijit/MenuSeparator","dijit/PopupMenuItem"],function(i,a,e,b){e=new i({targetNodeIds:[h.id]});e.addChild(new a({label:"toggleDrag",parentMenu:e,onClick:k.hitch(h,h.toggleDrag)}));var d=new i({parentMenu:e});d.addChild(new a({label:"k\u7ebf",onClick:k.hitch(h,h.changePlottype,1)}));d.addChild(new a({label:"\u7af9\u7ebf\u56fe",onClick:k.hitch(h,h.changePlottype,2)}));d.addChild(new a({label:"\u6536\u76d8\u7ebf\u56fe",onClick:k.hitch(h,
h.changePlottype,3)}));e.addChild(new b({label:"\u4e3b\u56fe\u5f62",popup:d}));i=new i({parentMenu:e});i.addChild(new a({label:"\u6210\u4ea4\u91cf",onClick:k.hitch(h,h.addIndicator,{value:"vol"})}));i.addChild(new a({label:"macd",onClick:k.hitch(h,h.addIndicator,{value:"macd",args:[12,26,9]})}));i.addChild(new a({label:"\u5747\u7ebf",onClick:k.hitch(h,h.toggleMainIndicator,{value:"ma",args:[5,30,60,120]})}));e.addChild(new b({label:"\u6dfb\u52a0\u6307\u6807",popup:i}));e.startup()})},_initDom:function(){var h=
this.options,i=this.domNode;o.set(i,{width:h.width+"px",height:h.height+"px",position:"relative",overflow:"hidden","z-index":h.baseZ+1});var b=p.create("div");a.set(b,"id",this.id+"_tooltip");o.set(b,{position:"absolute","z-index":h.baseZ+2,background:h.plotCss.tooltip.background,padding:h.plotCss.tooltip.padding,border:h.plotCss.tooltip.border,width:h.plotCss.tooltip.width,height:h.plotCss.tooltip.height,opacity:h.plotCss.tooltip.opacity,"border-radius":h.plotCss.tooltip.radius,display:"none",padding:h.plotCss.tooltip.padding,
"text-align":h.plotCss.tooltip.textAlign,"line-height":h.plotCss.tooltip.lineHeight});p.place(b,i);b=p.create("div");a.set(b,"id",this.id+"_newclosetip");o.set(b,{position:"absolute","z-index":h.baseZ+1,background:"#FFFFFF",border:"1px solid #587eb5",font:"10pt Arial bold","text-align":"center","vertical-align":"middle",width:h.rightMargin-2+"px",height:"16px","-webkit-transform-origin":"left top",color:"#587eb5",display:"none"});p.place(b,i);b=p.create("div");a.set(b,"id",this.id+"_crossCurve");
o.set({display:"none"});p.place(b,i);tipDiv=p.create("div");o.set(tipDiv,{position:"absolute",display:"none","z-index":9999,"float":"left",width:"auto",height:"auto","vertical-align":"middle",background:"black",font:"8pt Arial",color:"white","-webkit-transform-origin":"left top"});a.set(tipDiv,"id",this.id+"_relativeTips");p.place(tipDiv,i);this.tickerUtil=new q(h);this.dataHandle=new K(h,this.tickerUtil);this.indicatorHandle=new u(h,this.tickerUtil,i,this)},_initCanvas:function(h){var i=this.options,
d=this.domNode,e=this.canvas,B=this.ctx,g=this.canvas_temp;if(e){if(h)o.set(d,{width:h.w+"px"}),o.set(d,{height:h.h+"px"}),i.height=b.scaleMul(h.h,"y"),i.width=b.scaleMul(h.w,"x");e.height=i.height;e.width=i.width;g.width=i.width;g.height=i.height}else g=Math.round(1E6*Math.random()),i.height=b.scaleMul(o.get(d,"height"),"y"),i.width=b.scaleMul(o.get(d,"width"),"x"),d=this.id+"_canvas_"+g,e=this.canvas=p.create("canvas",null,this.domNode),a.set(e,{id:d}),e.height=i.height,e.width=i.width,e.style.position=
"absolute",e.style["-webkit-transform-origin"]="left top",d=this.id+"_canvas_temp_"+g,g=this.canvas_temp=p.create("canvas",null,this.domNode),a.set(g,{id:d}),g.height=i.height,g.width=i.width,g.style.position="absolute",g.style["-webkit-transform-origin"]="left top",g.tabIndex=0,g.style.outlineStyle="none",g.style.zIndex=i.baseZ+3,B=this.ctx=e.getContext("2d"),B.fillStyle=i.plotCss.background,B.fillRect(0,0,i.width,i.height),this.ctx_temp=g.getContext("2d"),this.removeEvents(e,g),this.bindEvents(e,
g);g.style["-webkit-transform"]="scale("+1/b.getScaleX()+","+1/b.getScaleY()+")";e.style["-webkit-transform"]="scale("+1/b.getScaleX()+","+1/b.getScaleY()+")";i.plotWidth=i.width-i.leftOffset-i.rightMargin;i.plotHeight=i.height-i.topMargin-i.bottomMargin;i.chartParams.maxxlabels=i.plotWidth/100;e=i.height-i.topMargin-i.bottomMargin;if(1==i.chartParams.numindicators)i.subPlotHeight=e/3,i.plotHeight=e-i.subPlotHeight;else if(2==i.chartParams.numindicators)i.subPlotHeight=(e/3+i.height/10)/i.chartParams.numindicators,
i.plotHeight=e-i.subPlotHeight*i.chartParams.numindicators;else if(3<=i.chartParams.numindicators)i.plotHeight=i.height/2.5,i.subPlotHeight=(e-i.plotHeight)/i.chartParams.numindicators},_getData:function(){var h=this,i=h.options,a=h.dataService,e=h.dataHandle,b=h.tickerUtil,g=h.ctx,F=[];if(!i.query.isStatic){var w=new l;F.push(w);(new f(i.store,{service:"objinfo",type:"base",field:["name","open_close_num","open_close_time"],obj:i.query.obj,his_data:1})).singleFetch(function(h){if(h&&h.length){for(var e=
0;e<h.length;e++)i.query.obj[e].name=h[e][0],i.query.obj[e].tradeTimeNum=h[e][1],i.query.obj[e].tradeTime=h[e][2];w.resolve()}else throw Error("\u5546\u54c1\u540d\u79f0\u548c\u4ea4\u6613\u65f6\u95f4\u6bb5\u6ca1\u6709\u53d6\u5230!");});if(4==i.chartParams.type||5==i.chartParams.type){var G=new l;F.push(G);(new f(i.store,{service:"quote",type:"kline",field:["close","time"],obj:i.query.obj,count:4,his_data:1})).singleFetch(function(h){if(h&&h.length)i.query.obj[0].prevClose=h,G.resolve();else throw Error("\u6628\u6536\u4ef7\u6ca1\u6709\u53d6\u5230!");
});var m=new l;F.push(m);(new f(i.store,{service:"quote",type:"kline",field:["time"],obj:i.query.obj,k_period:"1m",count:1,his_data:1})).singleFetch(function(h){if(h&&h.length)i.query.obj[0].lastdate=h[0][0],m.resolve();else throw Error("\u6700\u65b0\u65f6\u95f4\u6ca1\u6709\u53d6\u5230!");})}}var o=function(a,b,d){a.head&&a.head.length&&a.datas&&a.datas.length?(i.chartParams.timeScale=d,e.transformData4Acube(a,b),4!=i.chartParams.type&&5!=i.chartParams.type?i.current.indicators&&i.current.indicators.length?
h.initIndicator(i.current.indicators):h.initIndicator(i.chartParams.indicators):(h.timetrendUpdate=!1,h.doplot(g,0))):console.error("\u884c\u60c5\u6570\u636e(\u5386\u53f2)\u6ca1\u6709\u53d6\u5230!")},n=function(d,f){if(d.head&&d.head.length&&d.datas&&d.datas.length){if(4==i.chartParams.type||5==i.chartParams.type){if(!i.query.obj[0]||!i.query.obj[0].date||!i.query.obj[0].tradeTime||i.query.obj[0].code!=d.datas[0][0])return;var m=new Date;m.setHours(0,0,0,0);if(i.query.obj[0].date.getDate()!=(new Date).getDate()&&
b.millisecondChange(d.datas[0][1])>=m.getTime()+1E3*i.query.obj[0].tradeTime[0]){if(h.timetrendUpdate)return;h.timetrendUpdate=!0;a.unReg();h._getData();return}}m=e.transformRealData4Acube(d,f);"main"in m&&h.doplot(g,m.main.shift);h.getNewTooltips()}else console.error("\u884c\u60c5\u6570\u636e(\u5b9e\u65f6)\u6ca1\u6709\u53d6\u5230!")};(new d(F)).then(function(){if(i.query.obj[0].tradeTime&&i.query.obj[0].tradeTimeNum&&i.query.obj[0].lastdate&&(4==i.chartParams.type||5==i.chartParams.type)){a.changeTimeScale("1m");
var h=b.from5StrToHM("%h%m",i.query.obj[0].tradeTime[0]),e=b.from5StrToHM("%h%m",i.query.obj[0].tradeTime[2*i.query.obj[0].tradeTimeNum-1]),d=new Date,g=[],m=i.query.obj[0].lastdate;d.setHours(0,0,0,0);parseFloat(h)<parseFloat(e)?b.millisecondChange(m)<1*d.getTime()+1E3*i.query.obj[0].tradeTime[0]&&(d=new Date(b.millisecondChange(m))):(b.millisecondChange(m)<1*d.getTime()+1E3*i.query.obj[0].tradeTime[0]&&(d=new Date(b.millisecondChange(m)),d.setDate(d.getDate()-1)),e=k.clone(d),e.setDate(e.getDate()+
1));g.push(";time>="+d.getFullYear()+(100+d.getMonth()+1).toString().substring(1)+(100+d.getDate()).toString().substring(1)+h+"00");i.query.obj[0].date=d;h=b.millisecond2Date("%Y/%m/%d",d.getTime(),null,!0);d=0;for(e=i.query.obj[0].prevClose[0][1].datas.length;d<e;d++)if(1<e){if(b.millisecond2Date("%Y/%m/%d",i.query.obj[0].prevClose[0][1].datas[d][0])==h){h=i.query.obj[0].prevClose[0][1].datas[d-1][1];delete i.query.obj[0].prevClose;i.query.obj[0].prevClose=h;break}}else{h=i.query.obj[0].prevClose[0][1].datas[d][1];
delete i.query.obj[0].prevClose;i.query.obj[0].prevClose=h;break}a.changeTimeRange(g)}a.cycleFetch(o,n)})},initIndicator:function(h){if(h)for(var i=h.length,a=0;a<i;a++)this.addIndicator({value:h[a].type,args:h[a].args});else this.doplot(this.ctx,0)},doplot:function(h,i){var a=this,e=a.options,b=a.indicatorHandle,d=a.tickerUtil,g=a.canvas_temp;if(e.current&&e.chartParams.timeScale==e.current.timeScale){d.clearAll(h,g);var i=i||0,f=e.current.ohlc,k=e.current.vol,m=e.current.overlays,l=e.current.indicators;
if(4!=e.chartParams.type&&5!=e.chartParams.type){a.coreRange(f,m,i);var o=e.current.begin,n=e.current.ymin,p=e.current.end,q=e.leftOffset,s=(e.plotHeight-e.bottomSpacing-e.topSpacing)/(e.current.ymax-n),u=e.topMargin+e.plotHeight;h.strokeStyle=e.plotCss.stroke;h.lineWidth=1;h.strokeRect(q,e.topMargin,Math.round(e.plotWidth),Math.round(e.plotHeight));if(0==e.current.indicators.length)e.subPlotHeight=0;var q=u-e.bottomSpacing,t=Math.round(e.chartParams.cwidth/1.6);0==t%2&&(t-=1);u=Math.round(t/2)-1;
1>=t&&(t=1,u=0);for(var t=[],H,z=0,y=e.plotCss.label,A=0;A<e.query.obj.length;A++)if(H=e.query.obj[A].name+" ",!/undefined/gi.test(H)){if(A)y=e.plotCss.overlaps[A-1].downStyle.candle.color;d.drawText(h,H,e.leftOffset+z,e.topMargin+e.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:y});z+=h.measureText(H).width;t.push(H)}a.mainLabel=t.join("")+"  "+e.chartParams.timeScaleFormatter[e.chartParams.timeScale].txt;d.drawText(h,"  "+e.chartParams.timeScaleFormatter[e.chartParams.timeScale].txt,
e.leftOffset+z,e.topMargin+e.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:e.plotCss.label});d.drawText(h,e.copyrighttext,e.width-10,e.topMargin-e.topSpacing,{align:"right",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:e.plotCss.copyrighttext});H=0;var y=[],x;for(x in m)switch(x){case "ma":z=m[x].data;y=[];for(t=0;t<z.length;t++)y.push(z[t].period);b.ma(y);for(var z=m[x].data,A=a.mainLabel,r=0;r<z.length;r++){y=[];z[r].data[e.current.end-1]?
(d.drawText(h,z[r].prop+z[r].data[e.current.end-1].toFixed(2),h.measureText(A).width+e.leftOffset+e.topSpacing*(r+1),e.topMargin+e.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:e.plotCss.ma[r]}),A+=z[r].prop+z[r].data[e.current.end-1].toFixed(2)+" "):(d.drawText(h,z[r].prop+"--",h.measureText(A).width+e.leftOffset+e.topSpacing*(r+1),e.topMargin+e.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:e.plotCss.ma[r]}),A+=z[r].prop+
"-- ");for(var C=o;C<p;C++)if(t=C-o,z[r].data[C]){var E=Math.round(q-(z[r].data[C]-n)*s),K=Math.floor(t*e.chartParams.cwidth+e.leftOffset)+u;0<t&&y[0]&&d.drawline(h,y[0],y[1],K,E,e.plotCss.ma[H],1);y=[K,E]}H+=1}}a.yAxisPlot();a.xAxisPlot();m=1;for(C in l)if(o=l[C].type)b[o](),b.plotIndicator(h,l[C],m,a.doplot,i,a.changeIndicatortype),m+=1;a.candlePlotMain(f,k,i)}else{if(!e.query.obj[0].tradeTime)throw Error("\u4ea4\u6613\u65f6\u95f4\u6bb5\u4e0d\u5b58\u5728!");e.current.tradeTime=e.query.obj[0].tradeTime;
if(!e.query.obj[0].tradeTimeNum)throw Error("\u4ea4\u6613\u65f6\u95f4\u6bb5\u7684\u4e2a\u6570\u4e0d\u5b58\u5728!");e.current.tradeTimeNum=e.query.obj[0].tradeTimeNum;if(!e.query.obj[0].prevClose)throw Error("\u6628\u6536\u4ef7\u4e0d\u5b58\u5728!");e.current.prevClose=e.query.obj[0].prevClose;e.current.date=e.query.obj[0].date||new Date;f=parseFloat(e.current.tradeTime[0]);for(t=0;t<2*e.current.tradeTimeNum;t++)k=e.current.tradeTime[t],"string"==typeof k&&-1!=k.indexOf(":")&&(e.current.tradeTime[t]=
t?f<parseFloat(k)?d.fromHMTo5Str(k):d.fromHMTo5Str(k)+86400:d.fromHMTo5Str(k));e.current.overlays.ma&&delete e.current.overlays.ma;b.ma(y);f=function(){d.clearAll(h,g);h.strokeStyle=e.plotCss.stroke;h.lineWidth=1;d.drawRect(h,e.leftOffset,e.topMargin,Math.round(e.plotWidth),Math.round(e.plotHeight),!0);for(var i=[],b=0;b<e.query.obj.length;b++)i.push(e.query.obj[b].name),i.push(" ");a.mainLabel=i.join("")+"\u5206\u65f6\u8d70\u52bf";d.drawText(h,a.mainLabel,e.leftOffset,e.topMargin+e.topSpacing,{align:"left",
padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:e.plotCss.label});d.drawText(h,e.copyrighttext,e.width-10,e.topMargin-e.topSpacing,{align:"right",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:e.plotCss.copyrighttext});if(4==e.chartParams.type){i=e.height-e.topMargin-e.bottomMargin;e.subPlotHeight=i/3;e.plotHeight=i-e.subPlotHeight;var i=e.leftOffset,b=e.plotWidth,B=e.topMargin+e.plotHeight,f=e.subPlotHeight;h.strokeStyle=e.plotCss.stroke;d.drawRect(h,i,B,b,f,!0);d.drawText(h,
"\u6210\u4ea4\u91cf",i,B+e.topSpacing,{color:e.plotCss.label})}this.yAxisRange=this.ymax-this.ymin;this.yAxisScale=(e.plotHeight-e.bottomSpacing-e.topSpacing)/this.yAxisRange;this.yAxisEnd=e.topMargin+e.plotHeight;this.h=this.yAxisEnd-e.bottomSpacing;this.c=Math.round(this.getCwidth()/2);this.csize=Math.round(this.getCwidth()/1.6)};k=function(){this.width=e.plotWidth;this.prepareDistance=5;for(var h=[],i=0;i<2*e.current.tradeTimeNum;i+=2)if("0"!=e.current.tradeTime[i]&&e.current.tradeTime[i+1])for(var a=
e.current.tradeTime[i+1],b=Number(e.current.tradeTime[i]);b<=a;b+=60)h.push(b);this.totalXaxis=h;this.begin=0;this.data=e.current.ohlc;this.ts=e.current.ts;this.cwidth=(this.width-this.prepareDistance)/this.totalXaxis.length;this.candles=this.data.length;i=d.minmax2d(this.data.slice(this.begin,this.candles));h=i[0];i=i[1];Math.abs(1-i/e.current.prevClose)>=Math.abs(1-h/e.current.prevClose)?(i=1*e.current.prevClose+Math.abs((1-i/e.current.prevClose)*e.current.prevClose),h=1*e.current.prevClose-Math.abs((1-
i/e.current.prevClose)*e.current.prevClose)):(i=1*e.current.prevClose+Math.abs((1-h/e.current.prevClose)*e.current.prevClose),h=1*e.current.prevClose-Math.abs((1-h/e.current.prevClose)*e.current.prevClose));this.ymin=1*h;this.ymax=1*i;e.current.totalXaxis=this.totalXaxis;e.current.begin=this.begin;e.current.end=this.totalXaxis.length;e.current.candles=this.candles;e.chartParams.cwidth=this.cwidth;e.current.ymin=this.ymin;e.current.ymax=this.ymax;e.current.prepareDistance=this.prepareDistance};k.prototype.getTs=
function(){return this.ts};k.prototype.getData=function(){return this.data};k.prototype.getTotalXaxis=function(){return this.totalXaxis};k.prototype.getCwidth=function(){return this.cwidth};f.prototype=new k;f.prototype.constructor=f;f.prototype.plotMain=function(){for(var i={},a=0;a<e.current.ts.length;a++)i[d.millisecond2Date("%H:%M",e.current.ts[a])]={ohlc:e.current.ohlc[a],vol:e.current.vol[a]};e.current.trendTimeTsDataMapping=i;for(var b=1.1*d.minmax1d(e.current.vol.slice(this.begin,this.totalXaxis.length))[1]-
0,b=(e.subPlotHeight-e.topSpacing)/b,g=e.topMargin+e.plotHeight+e.subPlotHeight,B=[],f=[],m=this.getTotalXaxis(),a=0;a<m.length;a++)f[a]=d.from5StrToHM("%h:%m",m[a]);if(e.chartParams.timetrendIsFill){h.save();h.beginPath();h.globalAlpha=e.plotCss.timetrendFillAlpha;h.strokeStyle=e.plotCss.timetrend;h.lineWidth=2;for(var m=!1,k=e.plotHeight+e.topMargin,a=0;a<f.length;a++){var w=f[a];if(i[w]){var v=a*this.getCwidth()+e.leftOffset,v=v+Math.round(this.csize/2);Math.round((i[w].ohlc[0]-this.ymin)*this.yAxisScale);
Math.round((i[w].ohlc[1]-this.ymin)*this.yAxisScale);Math.round((i[w].ohlc[2]-this.ymin)*this.yAxisScale);w=Math.round((i[w].ohlc[3]-this.ymin)*this.yAxisScale);m?1==e.chartParams.timetrendType?h.lineTo(this.prepareDistance+v,this.h-w):2==e.chartParams.timetrendType&&(h.lineTo(this.prepareDistance+v,B[1]),h.lineTo(this.prepareDistance+v,this.h-w)):(h.moveTo(this.prepareDistance+v,e.plotHeight+e.topMargin),h.lineTo(this.prepareDistance+v,this.h-w),m=!0);k=Math.min(k,this.h-w);B=[v,this.h-w]}}h.stroke();
h.lineTo(this.prepareDistance+v,e.plotHeight+e.topMargin);h.closePath();if(1==e.plotCss.timetrendFillColors.length)h.fillStyle=e.plotCss.timetrendFillColors[0];else if(2==e.plotCss.timetrendFillColors.length)a=h.createLinearGradient(this.prepareDistance,e.plotHeight+e.topMargin,this.prepareDistance,k),a.addColorStop(0,e.plotCss.timetrendFillColors[0]),a.addColorStop(1,e.plotCss.timetrendFillColors[1]),h.fillStyle=a;h.fill();h.restore()}else for(a=0;a<f.length;a++)w=f[a],i[w]&&(v=a*this.getCwidth()+
e.leftOffset,v+=Math.round(this.csize/2),Math.round((i[w].ohlc[0]-this.ymin)*this.yAxisScale),Math.round((i[w].ohlc[1]-this.ymin)*this.yAxisScale),Math.round((i[w].ohlc[2]-this.ymin)*this.yAxisScale),w=Math.round((i[w].ohlc[3]-this.ymin)*this.yAxisScale),this.ymin==this.ymax&&(m=(e.plotHeight-e.bottomSpacing-e.topSpacing)/2,d.drawline(h,this.prepareDistance+B[0],this.h-m,this.prepareDistance+v,this.h-m,e.plotCss.timetrend,1)),1==e.chartParams.timetrendType?d.drawline(h,this.prepareDistance+B[0],B[1],
this.prepareDistance+v,this.h-w,e.plotCss.timetrend,1):2==e.chartParams.timetrendType&&(d.drawline(h,this.prepareDistance+B[0],B[1],this.prepareDistance+B[0],this.h-w,e.plotCss.timetrend,1),d.drawline(h,this.prepareDistance+B[0],this.h-w,this.prepareDistance+v,this.h-w,e.plotCss.timetrend,1)),B=[v,this.h-w]);if(4==e.chartParams.type)for(a=0;a<f.length;a++)if(w=f[a],i[w])if(v=a*this.getCwidth()+e.leftOffset,Math.round(this.csize/2),1*i[w].ohlc[0]>1*i[w].ohlc[3]){if(i[w].vol)B=i[w].vol*b,h.lineWidth=
this.csize,h.strokeStyle=e.plotCss.downStyle.candle.color,h.beginPath(),h.moveTo(this.prepareDistance+v,g-B),h.lineTo(this.prepareDistance+v,g),h.stroke(),h.closePath()}else if(1*i[w].ohlc[0]<1*i[w].ohlc[3]){if(i[w].vol)B=i[w].vol*b,h.lineWidth=this.csize,h.strokeStyle=e.plotCss.upStyle.candle.color,h.beginPath(),h.moveTo(this.prepareDistance+v,g-B),h.lineTo(this.prepareDistance+v,g),h.stroke(),h.closePath()}else if(i[w].vol)B=i[w].vol*b,h.lineWidth=1,h.strokeStyle=e.plotCss.timetrend,h.beginPath(),
h.moveTo(this.prepareDistance+v,g-B),h.lineTo(this.prepareDistance+v,g),h.stroke(),h.closePath()};f.prototype.plotYaxis=function(){var i=e.leftOffset+this.width,a=Math.floor((e.plotHeight-e.topSpacing-e.bottomSpacing)/100);1>a&&(a=1);for(var g=(e.current.prevClose-this.ymin)/a,f=[],m=0;m<=a;m++)f[m]=g*m;var a=(e.plotHeight-e.bottomSpacing-e.topSpacing)/2,w;e.chartParams.toFixNum||0==e.chartParams.toFixNum?w=e.chartParams.toFixNum:(w=3,1.0E-5>g?w=7:1.0E-4>g?w=6:0.001>g?w=5:0.01>g?w=4:0.1>g&&(w=3));
e.current.fixNum=w;e.bglineSpace=Math.abs(f[0]-f[1])*this.yAxisScale;for(m in f){var k=f[m],v=Math.round(k*this.yAxisScale),g=(f[m]+1*e.current.prevClose).toFixed(w),F=(1*e.current.prevClose-f[m]).toFixed(w),k=(100*(k/e.current.prevClose)).toFixed(2);if(0==k)g=Math.round(this.h-a),d.drawline(h,e.leftOffset,g,i,g,e.plotCss.label),d.drawText(h,(1*e.current.prevClose).toFixed(w),i,g,{align:"left",textBaseline:"middle",padding:5,color:e.plotCss.label}),d.drawText(h,"0.00%",e.leftOffset-5,g,{align:"right",
padding:5,textBaseline:"middle",color:e.plotCss.label});else{var l=Math.round(this.h-a+v),v=Math.round(this.h-a-v);"dashed"==e.plotCss.backgroundGrid.type?(d.drawDashes(h,e.leftOffset,l,i,l,e.plotCss.backgroundGrid.color,1),d.drawDashes(h,e.leftOffset,v,i,v,e.plotCss.backgroundGrid.color,1)):(d.drawline(h,e.leftOffset,l,i,l,e.plotCss.backgroundGrid.color),d.drawline(h,e.leftOffset,v,i,v,e.plotCss.backgroundGrid.color));d.drawText(h,g,i,v,{align:"left",textBaseline:"middle",padding:5,color:e.plotCss.upStyle.candle.color});
d.drawText(h,k+"%",e.leftOffset-5,v,{align:"right",padding:5,textBaseline:"middle",color:e.plotCss.upStyle.candle.color});d.drawText(h,F,i,l,{align:"left",textBaseline:"middle",padding:5,color:e.plotCss.downStyle.candle.color});d.drawText(h,k+"%",e.leftOffset-5,l,{align:"right",padding:5,textBaseline:"middle",color:e.plotCss.downStyle.candle.color})}}4==e.chartParams.type&&(i=1.1*d.minmax1d(e.current.vol.slice(this.begin,this.totalXaxis.length))[1],b.yAxisPlot(h,"vol",0,i,e.subPlotHeight,1,0))};f.prototype.plotXaxis=
function(i){for(var a=e.topMargin+(e.height-e.topMargin-e.bottomMargin),b,g=0;g<i.length;g++)b=Math.round(i[g].coord),"dashed"==e.plotCss.backgroundGrid.type&&0!=i[g].coord?d.drawDashes(h,b+e.leftOffset,a,b+e.leftOffset,e.topMargin,e.plotCss.backgroundGrid.color,1):"solid"==e.plotCss.backgroundGrid.type&&0!=i[g].coord&&d.drawline(h,b+e.leftOffset,a,b+e.leftOffset,e.topMargin,e.plotCss.backgroundGrid.color),0==g?d.drawText(h,i[g].time,b,a,{align:"left",textBaseline:"top",color:e.plotCss.xAxisLabel.color}):
d.drawText(h,i[g].time,b+e.leftOffset,a,{align:"center",textBaseline:"top",color:e.plotCss.xAxisLabel.color})};k=function(){this.xLabels=function(){for(var i=[],a,b,g=0;g<this.totalXaxis.length;g++)a=d.from5StrToHM("%h:%m",this.totalXaxis[g]),b=d.from5StrToHM("%h:%m",this.totalXaxis[g-1]),0==g?i.push({coord:this.prepareDistance+g*this.getCwidth(),time:d.millisecond2Date("%Y/%m/%d",e.current.date.getTime(),null,!0)+","+a}):0==a.substring(3,5)%30&&0!=b.substring(3,5)%30&&this.prepareDistance+g*this.getCwidth()-
i[i.length-1].coord>h.measureText(i[i.length-1].coord.time).width&&i.push({coord:this.prepareDistance+g*this.getCwidth(),time:a});return i}};k.prototype=new f;k.prototype.constructor=k;f=new k;f.plotXaxis(f.xLabels());f.plotYaxis();f.plotMain()}}},coreRange:function(h,i,a){var e=this.options,b=this.tickerUtil,d=e.plotWidth,g,f,k,m=0,m=h.length;m>d/e.chartParams.minwidth&&(m=Math.round(d/e.chartParams.minwidth));f=(e.current.end||h.length)-a;if(f>h.length)f=h.length;g=f-m;0>g&&(g=0,f=g+m);k=m;e.chartParams.cwidth=
d/k;if(40<e.chartParams.cwidth)e.chartParams.cwidth=40;m=b.minmax2d(h.slice(g,f));h=m[0];m=m[1];e.current.max_price=m;e.current.min_price=h;if(i){var l,o,n;for(n in i)if("ma"==n){o=[];for(var p=0;p<i[n].data.length;p++)o=b.minmax1d(i[n].data[p].data.slice(g,f)),l=o[1],o=o[0],l>m&&(m=l),o<h&&(h=o)}}e.current.begin=g;e.current.end=f;e.current.candles=k;e.current.firstTs=e.current.ts[e.current.begin];e.current.firstClose=e.current.ohlc[e.current.begin][3];i=e.current.ts.slice(e.current.begin,f);for(g=
0;g<e.overlaps.length;g++)if(f=e.overlaps[g],n=b.checkSameValueInArrs(i,f.ts),n[0])if(0==n[0].mainIndex&&0==n[0].overlapsIndex){k=parseInt(n[0].overlapsIndex);l=f.ohlc.length;l>d/e.chartParams.minwidth&&(l=Math.round(d/e.chartParams.minwidth));f.candles=l;overlapsEnd=(f.overlapsEnd||f.ohlc.length)-a;if(overlapsEnd>f.ohlc.length)overlapsEnd=f.ohlc.length;overlapsEnd=k+l;f.begin=k;f.end=overlapsEnd;f.firstTs=f.ts[k];f.firstClose=f.ohlc[k][3];f.percent=f.ohlc[n[0].overlapsIndex][3]/e.current.firstClose;
k=b.minmax2d(f.ohlc.slice(k,overlapsEnd));n=k[0];k=k[1];f.max_price=k;f.min_price=n;l=k-n;f.ymin=n-0.05*l;f.ymax=k+0.05*l;f.ymax/f.percent>m&&(m=f.ymax/f.percent);f.ymin/f.percent<h&&(h=f.ymin/f.percent)}else if(0!=n[0].mainIndex){k=parseInt(n[0].overlapsIndex);l=f.ohlc.length;l>d/e.chartParams.minwidth&&(l=Math.round(d/e.chartParams.minwidth));f.candles=l;overlapsEnd=(f.overlapsEnd||f.ohlc.length)-a;if(overlapsEnd>f.ohlc.length)overlapsEnd=f.ohlc.length;overlapsEnd=k+l;f.begin=k;f.end=overlapsEnd;
f.firstTs=f.ts[k];f.firstClose=f.ohlc[k][3];f.percent=f.ohlc[n[0].overlapsIndex][3]/e.current.ohlc[e.current.begin+1*n[0].mainIndex][3];k=b.minmax2d(f.ohlc.slice(k,overlapsEnd));n=k[0];k=k[1];f.max_price=k;f.min_price=n;l=k-n;f.ymin=n-0.05*l;f.ymax=k+0.05*l;f.ymax/f.percent>m&&(m=f.ymax/f.percent);f.ymin/f.percent<h&&(h=f.ymin/f.percent)}else if(0!=n[0].overlapsIndex){k=parseInt(n[0].overlapsIndex);l=f.ohlc.length;l>d/e.chartParams.minwidth&&(l=Math.round(d/e.chartParams.minwidth));f.candles=l;overlapsEnd=
(f.overlapsEnd||f.ohlc.length)-a;if(overlapsEnd>f.ohlc.length)overlapsEnd=f.ohlc.length;overlapsEnd=k+l;f.begin=k;f.end=overlapsEnd;f.firstTs=f.ts[k];f.firstClose=f.ohlc[k][3];f.percent=f.ohlc[n[0].overlapsIndex][3]/e.current.firstClose;k=b.minmax2d(f.ohlc.slice(k,overlapsEnd));n=k[0];k=k[1];f.max_price=k;f.min_price=n;l=k-n;f.ymin=n-0.05*l;f.ymax=k+0.05*l;f.ymax/f.percent>m&&(m=f.ymax/f.percent);f.ymin/f.percent<h&&(h=f.ymin/f.percent)}a=m-h;e.current.ymin=h-0.05*a;e.current.ymax=m+0.05*a},candlePlotMain:function(h,
i,a){var i=this.options,e=this.tickerUtil,b=this.ctx,d=i.current.begin,f=i.current.ymin,g=i.current.end,k=(i.plotHeight-i.bottomSpacing-i.topSpacing)/(i.current.ymax-f),m=Math.round(i.topMargin+i.plotHeight)-i.bottomSpacing,l=Math.round(i.chartParams.cwidth/1.6);0==l%2&&(l-=1);var n=Math.round(l/2)-1;1>=l&&(l=1,n=0);for(var o=[],p=!1,q=!1,s={prevxyOverlaps:[],OHLC:null,count:-1},r=d;r<g;r++){var t=Math.round((h[r][0]-f)*k),u=Math.round((h[r][1]-f)*k),z=Math.round((h[r][2]-f)*k),y=Math.round((h[r][3]-
f)*k),A=Math.floor((r-d)*i.chartParams.cwidth+i.leftOffset),x=A+n;b.textAlign="center";if(h[r][1]==i.current.max_price&&!p)b.fillStyle=i.plotCss.upStyle.candle.color,75>A-i.leftOffset?(e.drawLineWithArrow(b,A+7,m-u-5,A+37,m-u-5,b.fillStyle,1,"left"),b.fillText(h[r][1].toFixed(i.current.fixNum),A+67,m-u)):(e.drawLineWithArrow(b,A-30,m-u-5,A,m-u-5,b.fillStyle,1,"right"),b.fillText(h[r][1].toFixed(i.current.fixNum),A-60,m-u)),p=!0;if(h[r][2]==i.current.min_price&&!q)b.fillStyle=i.plotCss.downStyle.candle.color,
75>A-i.leftOffset?(e.drawLineWithArrow(b,A+7,m-z+10,A+37,m-z+10,b.fillStyle,1,"left"),b.fillText(h[r][2].toFixed(i.current.fixNum),A+67,m-z+15)):(e.drawLineWithArrow(b,A-30,m-z+10,A,m-z+10,b.fillStyle,1,"right"),b.fillText(h[r][2].toFixed(i.current.fixNum),A-60,m-z+15)),q=!0;h[r][0]>h[r][3]?"stroke"==i.plotCss.downStyle.candle.type?(b.strokeStyle=i.plotCss.downStyle.candle.color,1==i.chartParams.type?(e.drawRect(b,A,m-t,l-1,t-y,!0),t-y||e.drawRect(b,A,m-t,l-1,1,!0),e.drawline(b,x,m-u,x,m-t,b.strokeStyle,
1),e.drawline(b,x,m-t+t-y,x,m-z,b.strokeStyle,1)):2==i.chartParams.type?(e.drawline(b,x,m-u,x,m-z,b.strokeStyle,1),e.drawline(b,A,m-t,x,m-t,b.strokeStyle,1),e.drawline(b,x,m-y,x+n,m-y,b.strokeStyle,1)):(0<r-d&&e.drawline(b,o[0],o[1],x,m-y,b.strokeStyle,2),o=[x,m-y])):(b.fillStyle=i.plotCss.downStyle.candle.color,1==i.chartParams.type?(e.drawRect(b,A,m-t,l,t-y,!1),t-y||e.drawRect(b,A,m-t,l,1,!1),e.drawline(b,x,m-u,x,m-z,b.fillStyle,1)):2==i.chartParams.type?(e.drawline(b,x,m-u,x,m-z,b.fillStyle,1),
e.drawline(b,A,m-t,x,m-t,b.fillStyle,1),e.drawline(b,x,m-y,x+n,m-y,b.fillStyle,1)):(0<r-d&&e.drawline(b,o[0],o[1],x,m-y,b.fillStyle,2),o=[x,m-y])):h[r][0]==h[r][3]?(b.fillStyle=i.plotCss.fairStyle.candle.color,1==i.chartParams.type?(e.drawline(b,x,m-u,x,m-z,b.fillStyle,1),e.drawline(b,A,m-t,A+l-1,m-t,b.fillStyle,1)):2==i.chartParams.type?(e.drawline(b,x,m-u,x,m-z,b.fillStyle,1),e.drawline(b,A,m-t,x,m-t,b.fillStyle,1),e.drawline(b,x,m-y,x+n,m-y,b.fillStyle,1)):(0<r-d&&e.drawline(b,o[0],o[1],x,m-y,
b.fillStyle,2),o=[x,m-y])):"stroke"==i.plotCss.upStyle.candle.type?(b.strokeStyle=i.plotCss.upStyle.candle.color,1==i.chartParams.type?(e.drawRect(b,A,m-t,l-1,t-y,!0),t-y||e.drawRect(b,A,m-t,l-1,1,!0),e.drawline(b,x,m-u,x,m-y,b.strokeStyle,1),e.drawline(b,x,m-y+y-t,x,m-z,b.strokeStyle,1)):2==i.chartParams.type?(e.drawline(b,x,m-u,x,m-z,b.strokeStyle,1),e.drawline(b,A,m-t,x,m-t,b.strokeStyle,1),e.drawline(b,x,m-y,x+n,m-y,b.strokeStyle,1)):(0<r-d&&e.drawline(b,o[0],o[1],x,m-y,b.strokeStyle,2),o=[x,
m-y])):(b.fillStyle=i.plotCss.upStyle.candle.color,1==i.chartParams.type?(e.drawRect(b,A,m-t,l,t-y,!1),t-y||e.drawRect(b,A,m-t,l,1,!1),e.drawline(b,x,m-u,x,m-z,b.fillStyle,1)):2==i.chartParams.type?(e.drawline(b,x,m-u,x,m-z,b.fillStyle,1),e.drawline(b,A,m-t,x,m-t,b.fillStyle,1),e.drawline(b,x,m-y,x+n,m-y,b.fillStyle,1)):(0<r-d&&e.drawline(b,o[0],o[1],x,m-y,b.fillStyle,2),o=[x,m-y]));s=this.candlePlotOverlaps(i.current.ts[r],a,A,x,l,k,m,s.prevxyOverlaps,s.OHLC,s.count)}},candlePlotOverlaps:function(h,
i,a,e,b,d,f,g,k,m){var i=this.options,l=this.tickerUtil,n=this.ctx,o,p,q,r,u=0;k||(k=[]);for(var t=0;t<i.overlaps.length;t++){for(var s=i.overlaps[t],z=u=0;z<s.ts.length&&!(s.ts[z]==h&&(o=Math.round((s.ohlc[z][0]/s.percent-i.current.ymin)*d),p=Math.round((s.ohlc[z][1]/s.percent-i.current.ymin)*d),q=Math.round((s.ohlc[z][2]/s.percent-i.current.ymin)*d),r=Math.round((s.ohlc[z][3]/s.percent-i.current.ymin)*d),u=1,m=z),u);z++);!u&&k&&k[t]&&(o=k[t],p=k[t],q=k[t],r=k[t],u=1,m+=1);if(u)o>q?"stroke"==i.plotCss.overlaps[t].downStyle.candle.type?
(n.strokeStyle=i.plotCss.overlaps[t].downStyle.candle.color,1==i.chartParams.type?(l.drawRect(n,a,f-o,b-1,o-r,!0),o-r||l.drawRect(n,a,f-o,b-1,1,!0),l.drawline(n,e,f-p,e,f-o,n.strokeStyle,1),l.drawline(n,e,f-o+o-r,e,f-q,n.strokeStyle,1)):2==i.chartParams.type?(l.drawline(n,e,f-p,e,f-q,n.strokeStyle,1),l.drawline(n,a,f-o,e,f-o,n.strokeStyle,1),l.drawline(n,e,f-r,e+e-a,f-r,n.strokeStyle,1)):(0<m-s.begin&&l.drawline(n,g[t][0],g[t][1],e,f-r,n.strokeStyle,2),g[t]=[e,f-r])):(n.fillStyle=i.plotCss.overlaps[t].downStyle.candle.color,
1==i.chartParams.type?(l.drawRect(n,a,f-o,b,o-r,!1),o-r||l.drawRect(n,a,f-o,b,1,!1),l.drawline(n,e,f-p,e,f-q,n.fillStyle,1)):2==i.chartParams.type?(l.drawline(n,e,f-p,e,f-q,n.fillStyle,1),l.drawline(n,a,f-o,e,f-o,n.fillStyle,1),l.drawline(n,e,f-r,e+e-a,f-r,n.fillStyle,1)):(0<m-s.begin&&l.drawline(n,g[t][0],g[t][1],e,f-r,n.fillStyle,2),g[t]=[e,f-r])):"stroke"==i.plotCss.overlaps[t].upStyle.candle.type?(n.strokeStyle=i.plotCss.overlaps[t].upStyle.candle.color,1==i.chartParams.type?(l.drawRect(n,a,f-
o,b-1,o-r,!0),o-r||l.drawRect(n,a,f-o,b-1,1,!0),l.drawline(n,e,f-p,e,f-r,n.strokeStyle,1),l.drawline(n,e,f-r+r-o,e,f-q,n.strokeStyle,1)):2==i.chartParams.type?(l.drawline(n,e,f-p,e,f-q,n.strokeStyle,1),l.drawline(n,a,f-o,e,f-o,n.strokeStyle,1),l.drawline(n,e,f-r,e+e-a,f-r,n.strokeStyle,1)):(0<m-s.begin&&l.drawline(n,g[t][0],g[t][1],e,f-r,n.strokeStyle,2),g[t]=[e,f-r])):(n.fillStyle=i.plotCss.overlaps[t].upStyle.candle.color,1==i.chartParams.type?(l.drawRect(n,a,f-o,b,o-r,!1),o-r||l.drawRect(n,a,f-
o,b,1,!1),l.drawline(n,e,f-p,e,f-q,n.fillStyle,1)):2==i.chartParams.type?(l.drawline(n,e,f-p,e,f-q,n.fillStyle,1),l.drawline(n,a,f-o,e,f-o,n.fillStyle,1),l.drawline(n,e,f-r,e+e-a,f-r,n.fillStyle,1)):(0<m-s.begin&&l.drawline(n,g[t][0],g[t][1],e,f-r,n.fillStyle,2),g[t]=[e,f-r])),k[t]=q}return{prevxyOverlaps:g,OHLC:k,count:m}},xAxisPlot:function(){var h=this.options,a=this.tickerUtil,b=this.ctx,e=h.current.begin,d=h.current.end,f=h.topMargin+(h.height-h.topMargin-h.bottomMargin),g=Math.round(h.chartParams.cwidth/
1.6);0==g%2&&(g-=1);var k=Math.round(g/2)-1;1>=g&&(k=0);g=Math.floor((d-e)/h.chartParams.maxxlabels);b.fillStyle=h.plotCss.xAxisLabel.color;b.textAlign="center";for(var l=e;l<d;l++)if(1==l%g){var m=a.millisecond2Date(h.chartParams.timeScaleFormatter[h.chartParams.timeScale].formatter,h.current.ts[l]),n=Math.floor((l-e)*h.chartParams.cwidth+h.leftOffset),o=n+k;n>h.leftOffset&&("dashed"==h.plotCss.backgroundGrid.type?a.drawDashes(b,o,f,o,h.topMargin,h.plotCss.backgroundGrid.color,1):"solid"==h.plotCss.backgroundGrid.type&&
a.drawline(b,o,f,o,h.topMargin,h.plotCss.backgroundGrid.color),a.drawText(b,m,o,f,{align:"center",textBaseline:"top"}))}},yAxisPlot:function(){var h=this.options,a=n.byId(this.id+"_newclosetip"),d=this.tickerUtil,e=this.ctx,f=this.canvas_temp,g=h.current.ymin,k=h.current.ymax,l=h.leftOffset,p=l+h.plotWidth,m=(h.plotHeight-h.bottomSpacing-h.topSpacing)/(k-g),q=h.topMargin+h.plotHeight-h.bottomSpacing,r=this.ygrid(g,k,Math.floor(h.plotHeight/30));h.current.ohlc[h.current.ohlc.length-1][3]>=g&&h.current.ohlc[h.current.ohlc.length-
1][3]<=k?(k=f.offsetTop?b.scale(q-(h.current.ohlc[h.current.ohlc.length-1][3]-g)*m-8,"y")+f.offsetTop:b.scale(q-(h.current.ohlc[h.current.ohlc.length-1][3]-g)*m-8,"y"),f=f.offsetLeft?b.scale(h.plotWidth+h.leftOffset,"x")+f.offsetLeft:b.scale(h.plotWidth+h.leftOffset,"x"),o.set(a,{left:f+"px",top:k+"px","-webkit-transform":"scale("+1/b.getScaleX()+","+1/b.getScaleY()+")"}),!0==h.chartParams.isNewTip?o.set(a,{display:""}):o.set(a,{display:"none"}),a.innerHTML=h.current.ohlc[h.current.ohlc.length-1][3].toFixed(h.current.fixNum)):
o.set(a,{display:"none"});h.bglineSpace=Math.abs((r[0]-r[1])*m);if(h.overlaps&&h.overlaps.length)for(var s in r)a=r[s],f=Math.round(q-(a-g)*m),label=r[s].toFixed(h.current.fixNum),"dashed"==h.plotCss.backgroundGrid.type?d.drawDashes(e,l,f,p,f,h.plotCss.backgroundGrid.color,1):d.drawline(e,l,f,p,f,h.plotCss.backgroundGrid.color),d.drawText(e,label,p,f,{align:"left",padding:5,color:h.plotCss.yAxisLabel.color,textBaseline:"middle"}),a=(100*((label-h.current.ohlc[h.current.begin][3])/h.current.ohlc[h.current.begin][3])).toFixed(2),
0>a?d.drawText(e,Math.abs(a)+"%",h.leftOffset-5,f,{color:h.plotCss.downStyle.candle.color,textBaseline:"middle",align:"right"}):d.drawText(e,Math.abs(a)+"%",h.leftOffset-5,f,{color:h.plotCss.upStyle.candle.color,textBaseline:"middle",align:"right"});else for(s in r)a=r[s],f=Math.round(q-(a-g)*m),label=r[s].toFixed(h.current.fixNum),"dashed"==h.plotCss.backgroundGrid.type?d.drawDashes(e,l,f,p,f,h.plotCss.backgroundGrid.color,1):"solid"==h.plotCss.backgroundGrid.type&&d.drawline(e,l,f,p,f,h.plotCss.backgroundGrid.color),
d.drawText(e,label,p,f,{align:"left",padding:5,color:h.plotCss.yAxisLabel.color,textBaseline:"middle"})},ygrid:function(h,a,b){var e=this.options,d=b-1;0==d&&(d=1);var f=[],a=(a-h)/d;e.chartParams.toFixNum||0==e.chartParams.toFixNum?d=e.chartParams.toFixNum:(d=3,1.0E-5>a?d=7:1.0E-4>a?d=6:0.001>a?d=5:0.01>a?d=4:0.1>a&&(d=3));e.current.fixNum=d;for(e=0;e<b;e++)f[e]=parseFloat(h+a*e);return f},showNewCloseTip:function(){var h=this.options;h.chartParams.isNewTip=h.chartParams.isNewTip?!1:!0;this.doplot(this.ctx,
0)},toggleMainIndicator:function(h){var a=this.options,b=this.indicatorHandle,e=this.ctx,d=h.args;switch(h.value){case "ma":a.current.overlays.ma?delete a.current.overlays.ma:b.ma(d)}this.doplot(e,0)},addIndicator:function(h){var a=this.options,b=this.indicatorHandle,e=this.ctx,d=h.value,h=h.args||[],f;for(f in a.current.indicators)if(d==a.current.indicators[f].type){d=void 0;break}switch(d){case "macd":d=parseInt(h[0]);f=parseInt(h[1]);var g=parseInt(h[2]);d>f&&(d=f,f=parseInt(h[0]));b.macd(a.current.ohlc,
d,f,g);break;case "vol":b.vol(e)}this._initCanvas();this.doplot(e,0)},changePlottype:function(h){var a=this.ctx;this.options.chartParams.type=h;this.doplot(a,0)},changeIndicatortype:function(h){var a=this.options,b=this.tickerUtil;if(a.current.indicators.length){var e=h.value1||this.value1,d=h.vlaue2||this.value2,h=h.args||this.args||[];if(a.current.indicators){var f=!0,g,k;for(k in a.current.indicators)a.current.indicators[k].type==d&&(f=!1),a.current.indicators[k].type==e&&(g=k);f&&(b.removeArrByIndex(a.current.indicators,
g),a.chartParams.numindicators-=1,h={value:d,args:h},this.addIndicator(h))}}},toggleTooltip:function(){var h=n.byId(this.id+"_tooltip"),a=this.canvas_temp;"none"==o.get(h,"display")?(o.set(h,{display:""}),a.style.cursor="crosshair"):(o.set(h,{display:"none"}),a.style.cursor="default")},toggleDrag:function(){var h=this.options,a=this.canvas_temp;h.chartParams.isDrag?(h.chartParams.isDrag=0,a.removeEventListener("mousedown",k.hitch(this,this.beginPanning),!1),a.removeEventListener("mousemove",k.hitch(this,
this.doPanning),!1),a.removeEventListener("mouseup",k.hitch(this,this.endPanning),!1)):(h.chartParams.isDrag=1,a.addEventListener("mousedown",k.hitch(this,this.beginPanning),!1),a.addEventListener("mousemove",k.hitch(this,this.doPanning),!1),a.addEventListener("mouseup",k.hitch(this,this.endPanning),!1))},drawPicture:function(h){var a=this.ctx,b=this.ctx_temp,e=this.canvas_temp;"0"==h&&options.chartParams.isDrag?(e.addEventListener("mousedown",k.hitch(this,this.beginPanning),!1),e.addEventListener("mousemove",
k.hitch(this,this.doPanning),!1),e.addEventListener("mouseup",k.hitch(this,this.endPanning),!1),this.drawTools.reset(e)):(e.removeEventListener("mousedown",k.hitch(this,this.beginPanning),!1),e.removeEventListener("mousemove",k.hitch(this,this.doPanning),!1),e.removeEventListener("mouseup",k.hitch(this,this.endPanning),!1),this.drawTools[h](a,e,b))},removeEvents:function(h,a){a.removeEventListener("mousedown",k.hitch(this,this.beginPanning),!1);a.removeEventListener("mousemove",k.hitch(this,this.doPanning),
!1);a.removeEventListener("mouseup",k.hitch(this,this.endPanning),!1);a.removeEventListener("keydown",k.hitch(this,this.keyActions),!1);a.removeEventListener("mousemove",k.hitch(this,this.crossCurve),!1);a.removeEventListener("mousemove",k.hitch(this,this.relativeTip),!1);a.removeEventListener("contextmenu",k.hitch(this,this.handleContextMenu),!1);a.removeEventListener("dblclick",k.hitch(this,this.handleDbClick),!1)},relativeTip:function(h){var a=this.options,d=n.byId(this.id+"_tooltip"),e=this.tickerUtil;
if(!(4==a.chartParams.type||5==a.chartParams.type)){var f=h.offsetX,g=h.offsetY,k=a.topMargin+a.plotHeight;h.target.style.cursor="none"==o.get(d,"display")?"default":"crosshair";d="";if(a.current&&f>a.leftOffset&&f<a.width-a.rightMargin&&g>a.topMargin&&g<a.height-a.bottomMargin){var l=e.getXaxisPosData(f),p=e.getXaxisPosIndi(f),m=e.getXaxisPosMa(f,g),e={};if(l&&l.length&&l[2])e.vol=l[2];if(p&&p[0])for(l=0;l<p.length;l++)if(p[l]&&p[l][0])for(var q=p[l][p[l].length-1].split(" "),l=1;l<q.length;l++){var r=
q[l].split(":");e[r[0]]=r[1]}o.set(tipDiv,{top:b.scale(g+20,"y")+"px",left:b.scale(f+20,"x")+"px","-webkit-transform":"scale("+1/b.getScaleX()+","+1/b.getScaleY()+")"});if(g<k){if(k=(a.plotHeight-a.bottomSpacing-a.topSpacing)/(a.current.ymax-a.current.ymin),m&&m.length)for(var s=0;s<m.length;s++)if(m[s]&&(f=(a.current.ymax-m[s].data)*k+a.topSpacing+a.topMargin,5>=Math.abs(f-g))){h.target.style.cursor="pointer";d+=m[s].prop+Number(m[s].data).toFixed(a.current.fixNum);tipDiv.innerHTML=d;break}}else{for(l=
0;l<a.current.indicators.length;l++){var m=a.current.indicators[l].type,p=a.current.indicators[l].ymax,q=a.current.indicators[l].ymin,r=a.current.indicators[l].everyHeight,u=a.current.indicators[l].yAxisEnd;for(s in e)if(k=r/(p-q),f=u-(e[s]-q)*k,"vol"==m){if(0<=g-f&&0>=g-u){d+=s+":"+e[s];h.target.style.cursor="pointer";break}}else if("macd"==m&&"MACD"==s)if(k=u-(0-q)*k,0<=g-f&&0>=g-k){d+=s+":"+Number(e[s]).toFixed(a.current.fixNum);h.target.style.cursor="pointer";break}else{if(0>=g-f&&0<=g-k){d+=
s+":"+Number(e[s]).toFixed(a.current.fixNum);h.target.style.cursor="pointer";break}}else if(0<f&&5>=Math.abs(f-g)){d+=s+":"+Number(e[s]).toFixed(a.current.fixNum);h.target.style.cursor="pointer";break}}tipDiv.innerHTML=d}""!=d?o.set(tipDiv,{display:"block"}):o.set(tipDiv,{display:"none"})}else o.set(tipDiv,{display:"none"})}},bindEvents:function(a,b){var d=this.options;4!=d.chartParams.type&&5!=d.chartParams.type&&(b.addEventListener("keydown",k.hitch(this,this.keyActions),!1),b.addEventListener("contextmenu",
k.hitch(this,this.handleContextMenu),!1));b.addEventListener("mousemove",k.hitch(this,this.relativeTip),!1);b.addEventListener("mousemove",k.hitch(this,this.crossCurve),!1);b.addEventListener("dblclick",k.hitch(this,this.handleDbClick),!1)},handleDbClick:function(a){this.toggleTooltip();a.stopPropagation();a.preventDefault();return!1},handleContextMenu:function(a){if(this.onContextMenu)return k.isFunction(this.onContextMenu)&&this.onContextMenu.call(event.target),a.stopPropagation(),a.preventDefault(),
!1},beginPanning:function(a){var b=this.tickerUtil,d=this.ctx_temp;a.target.style.cursor="move";d.begin_x=b.canvasOffsetX(a.pageX,a.target);d.begin_y=b.canvasOffsetY(a.pageY,a.target);d.start=!0},doPanning:function(a){var b=this.options,d=this.tickerUtil,e=this.ctx,f=this.ctx_temp,g=d.canvasOffsetX(a.pageX,a.target),d=d.canvasOffsetY(a.pageY,a.target),k=g-f.begin_x;if(f.start&&(a.target.style.cursor="move",Math.abs(k)>b.chartParams.minwidth))size=Math.floor(k/b.chartParams.minwidth),this.doplot(e,
size),f.begin_x=g,f.begin_y=d},endPanning:function(a){var b=n.byId(this.id+"_tooltip");this.ctx_temp.start=!1;a.target.style.cursor="none"==o.get(b,"display")?"default":"crosshair"},getNewTooltips:function(){var a=n.byId(this.id+"_crossCurve");this.crossCurve(r.get(a,"event"))},keyActions:function(a){var b=this.ctx;38===a.keyCode?(this.zoom(1),this.getNewTooltips(),a.preventDefault()):40===a.keyCode?(this.zoom(0),this.getNewTooltips(),a.preventDefault()):37===a.keyCode?(this.doplot(b,1),this.getNewTooltips(),
a.preventDefault()):39===a.keyCode&&(this.doplot(b,-1),this.getNewTooltips(),a.preventDefault())},zoom:function(a){var b=this.options,d=this.ctx;if(a){if(b.chartParams.minwidth+=2,30<b.chartParams.minwidth)b.chartParams.minwidth=30}else if(b.chartParams.minwidth-=2,1>b.chartParams.minwidth)b.chartParams.minwidth=1;this.doplot(d,0)},crossCurve:function(a){var b=this.options,d=n.byId(this.id+"_crossCurve"),e=n.byId(this.id+"_tooltip"),f=this.tickerUtil;if(b.current&&a){r.set(d,"event",a);var d=a.offsetX,
g=a.offsetY;this.drawCrossCurve(a,d,g);f.ElemPageOffsetX(a.target);f.ElemPageOffsetY(a.target);var k=f.getXaxisPosData(d),l=f.getXaxisPosIndi(d),f=f.getXaxisPosMa(d,g);d>b.leftOffset&&d<b.leftOffset+b.plotWidth&&"none"!=o.get(e,"display")&&this.tooltips(k,l,f,a)}},tooltips:function(a,d,f,e){var g=this.options,l=this.mainLabel,p=n.byId(this.id+"_tooltip"),q=this.tickerUtil,r=this.ctx,m=this.canvas_temp;e.offsetX-g.leftOffset>g.plotWidth/2?(o.set(p,{right:""}),e={left:(m.offsetLeft?b.scale(g.leftOffset,
"x")+m.offsetLeft:b.scale(g.leftOffset,"x"))+"px","-webkit-transform-origin":"left top"}):(o.set(p,{left:""}),e={right:(m.offsetRight?b.scale(g.rightMargin,"x")+m.offsetRight:b.scale(g.rightMargin,"x"))+"px","-webkit-transform-origin":"right top"});m=m.offsetTop?b.scale(g.topMargin+g.topSpacing,"y")+m.offsetTop:b.scale(g.topMargin+g.topSpacing,"y");k.mixin(e,{top:m+"px","-webkit-transform":"scale("+1/b.getScaleX()+","+1/b.getScaleY()+")"});o.set(p,e);m="";e=g.chartParams.toFixNum?g.chartParams.toFixNum:
2;if(4!=g.chartParams.type&&5!=g.chartParams.type){a&&a.length&&(a[0]&&(m+="<span style='"+g.plotCss.tooltip.time.cssText+"';>"+q.millisecond2Date("%Y-%m-%d %H:%M %a",a[0])+"</span><br/>"),a[1]&&a[1].length&&(m+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u5f00\u76d8\u4ef7</span>:<span style='"+g.plotCss.tooltip.content.cssText+"';>"+a[1][0].toFixed(e)+"</span><br/>",m+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u6700\u9ad8\u4ef7</span>:<span style='"+g.plotCss.tooltip.content.cssText+
"';>"+a[1][1].toFixed(e)+"</span><br/>",m+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u6700\u4f4e\u4ef7</span>:<span style='"+g.plotCss.tooltip.content.cssText+"';>"+a[1][2].toFixed(e)+"</span><br/>",m+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u6536\u76d8\u4ef7</span>:<span style='"+g.plotCss.tooltip.content.cssText+"';>"+a[1][3].toFixed(e)+"</span><br/>"),m=a[2]?m+("<span style='"+g.plotCss.tooltip.title.cssText+"';>\u6210\u4ea4\u91cf</span>:<span style='"+g.plotCss.tooltip.content.cssText+
"';>"+a[2]+"</span><br/>"):m+("<span style='"+g.plotCss.tooltip.title.cssText+"';>\u6210\u4ea4\u91cf</span>:<span style='"+g.plotCss.tooltip.content.cssText+"';>--</span><br/>"));for(var s=0,a=0;a<g.current.indicators.length;a++)if("macd"==g.current.indicators[a].type){s=a;break}if(d&&d.length)for(a=0;a<d.length;a++)e=0,e=g.topMargin+g.plotHeight+g.subPlotHeight*s,q.drawText(r,d[a][3],g.leftOffset,e+g.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53"});if(f&&f.length)for(d=
0;d<f.length;d++)f[d]&&(f[d].data?(q.drawText(r,f[d].prop+f[d].data.toFixed(2),r.measureText(l).width+g.leftOffset+g.topSpacing*(d+1),g.topMargin+g.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:g.plotCss.ma[d]}),l+=f[d].prop+f[d].data.toFixed(2)+" "):(q.drawText(r,f[d].prop+"--",r.measureText(l).width+g.leftOffset+g.topSpacing*(d+1),g.topMargin+g.topSpacing,{align:"left",padding:5,font:"10pt Consolas Inconsolata \u5b8b\u4f53",color:g.plotCss.ma[d]}),l+=f[d].prop+
"-- "))}else{a&&a.length&&(s="",a[0]&&(m+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u65f6&nbsp;&nbsp;\u95f4</span>:<span style='"+g.plotCss.tooltip.time.cssText+"';>"+q.millisecond2Date("%H:%M",a[0])+"</span><br/>"),a[1]&&a[1].length&&(m+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u4ef7&nbsp;&nbsp;\u683c</span>:<span style='"+g.plotCss.tooltip.content.cssText+"';>"+a[1][3].toFixed(e)+"</span><br/>"),a[2]?s+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u6210\u4ea4\u91cf</span>:<span style='"+
g.plotCss.tooltip.content.cssText+"';>"+a[2]+"</span><br/>":m+="<span style='"+g.plotCss.tooltip.title.cssText+"';>\u6210\u4ea4\u91cf</span>:<span style='"+g.plotCss.tooltip.content.cssText+"';>--</span><br/>");if(f&&f.length)for(d=0;d<f.length;d++)f[d]&&(m=f[d].data?m+("<span style='"+g.plotCss.tooltip.title.cssText+"';>\u5747&nbsp;&nbsp;\u4ef7</span>:<span style='"+g.plotCss.tooltip.content.cssText+"';>"+f[d].data.toFixed(e)+"</span><br/>"):m+("<span style='"+g.plotCss.tooltip.title.cssText+"';>\u5747&nbsp;&nbsp;\u4ef7</span>:<span style='"+
g.plotCss.tooltip.content.cssText+"';>--</span><br/>"));m+=s}if(""!=m&&"undefined"!=m)p.innerHTML=m},yAxisData:function(a,b,d,e,f,g){var k=this.options,l="",n=a-k.topMargin-k.topSpacing,m=(k.plotHeight-k.topSpacing-k.bottomSpacing)/(b-d);0==g?(n=a-Math.round(k.topMargin+k.plotHeight+k.subPlotHeight*e+k.topSpacing),m=Math.round(k.subPlotHeight-k.topSpacing)/(b-d)):1==g&&(n=a-Math.round(k.topMargin+k.plotHeight+k.subPlotHeight*e+k.topSpacing),m=Math.round(k.subPlotHeight-k.topSpacing)/(b-d));a=b-n/
m;a<=b&&a>=d&&(l=a.toFixed(f));return l},drawCrossCurve:function(a,d,f){var a=this.options,e=n.byId(this.id+"_crossCurve"),g=n.byId(this.id+"_tooltip"),k=this.tickerUtil,l=this.canvas_temp,p=this.yAxisData(f,a.current.ymax,a.current.ymin,0,a.current.fixNum);if(""==p)for(var q=0;q<a.current.indicators.length&&!(p=this.yAxisData(f,a.current.indicators[q].ymax,a.current.indicators[q].ymin,q,a.current.indicators[q].fixNum,a.current.indicators[q].flag),""!==p);q++);var q="",m,r;f>a.topMargin&&f<a.height-
a.bottomMargin&&d>=a.leftOffset&&d<=a.plotWidth+a.leftOffset&&("none"!=o.get(g,"display")&&(r=l.offsetLeft?b.scale(a.leftOffset,"x")+l.offsetLeft:b.scale(a.leftOffset,"x"),m=l.offsetTop?b.scale(f,"y")+l.offsetTop:b.scale(f,"y"),q+='<div style="position: absolute; z-index: '+(a.baseZ+2)+"; left:"+r+"px;top:"+m+"px; width:"+b.scale(a.plotWidth,"x")+"px;"+a.plotCss.crosshair.h_cssText+'">',q+="</div>"),""!=p&&d<=a.plotWidth+a.leftOffset&&d>=a.leftOffset&&4!=a.chartParams.type&&5!=a.chartParams.type&&
(r=l.offsetLeft?b.scale(a.plotWidth+a.leftOffset,"x")+l.offsetLeft:b.scale(a.plotWidth+a.leftOffset,"x"),m=l.offsetTop?b.scale(f-8,"y")+l.offsetTop:b.scale(f-8,"y"),q+="<div style='position: absolute; background: #FFFFFF; text-align:center;vertical-align:middle;font:10pt Arial bold; color: #3C72AE; border: 1px solid #3C72AE;width:"+(a.rightMargin-2)+"px; left:"+(r+6)+"px; top: "+m+"px; z-index: "+(a.baseZ+2)+";-webkit-transform-origin:left top;-webkit-transform:scale("+1/b.getScaleX()+","+1/b.getScaleY()+
");"+a.plotCss.crosslabels.y+"'>"+p+"<div style='position:absolute;top:5px;left:-4px;width:5px;height:5px;border-top:#587eb5 1px solid;border-left:#587eb5 1px solid;-webkit-transform:rotate(-32deg) skew(28deg, 0deg);background:#ffffff;border-radius:1px;'></div></div>"),"none"!=o.get(g,"display")&&(r=l.offsetLeft?b.scale(d,"x")+l.offsetLeft:b.scale(d,"x"),m=l.offsetTop?b.scale(a.topMargin,"y")+l.offsetTop:b.scale(a.topMargin,"y"),q+='<div style="position: absolute; z-index: '+(a.baseZ+2)+"; top:"+
m+"px; left:"+r+"px; height:"+b.scale(a.height-a.bottomMargin-a.topMargin,"y")+"px;"+a.plotCss.crosshair.v_cssText+'">',q+="</div>"),k.getXaxisPosData(d)&&f>a.topMargin&&f<a.height+a.bottomMargin&&4!=a.chartParams.type&&5!=a.chartParams.type&&(r=l.offsetLeft?b.scale(d-40,"x")+l.offsetLeft:b.scale(d-40,"x"),m=l.offsetTop?b.scale(a.height-a.bottomMargin,"y")+l.offsetTop:b.scale(a.height-a.bottomMargin,"y"),q+="<div style='position: absolute; text-align:center; width:80px;  font: 11pt Arial bold; "+
a.plotCss.crosslabels.x+" z-index: "+(a.baseZ+2)+"; left:"+r+"px; top:"+(m+5)+"px;-webkit-transform-origin:left top;-webkit-transform:scale("+1/b.getScaleX()+","+1/b.getScaleY()+")'>"+k.millisecond2Date(a.chartParams.timeScaleFormatter[a.chartParams.timeScale].formatter,k.getXaxisPosData(d)[0])+"<div style='position:absolute;top:-5px;left:45%;width:5px;height:5px;border-top:#587eb5 1px solid;border-left:#587eb5 1px solid;-webkit-transform:rotate(58deg) skew(28deg, 0deg);background:#ffffff;border-radius:1px;'></div></div>"));
e.innerHTML=q;o.set(e,{display:"block"})},resize:function(a){this._initCanvas(a);this.doplot(this.ctx,0);this.getNewTooltips()},changeCode:function(a){var b=this.options,d=this.dataService;b.current&&b.current.end&&delete b.current.end;b.query.obj=a instanceof Array?a:[a];d.changeObj(b.query.obj);b.overlaps=[];d.unReg();this._getData()},changeTimeScale:function(a){var b=this.options,d=this.dataService;b.current&&b.current.end&&delete b.current.end;d.changeTimeScale(a);d.unReg();this._getData()},toggleChuQuan:function(){var a=
this.options,b=this.dataService;a.current&&a.current.end&&delete a.current.end;b.toggleQuan();b.unReg();this._getData()},addOverlaps:function(a,b){var d=this.options,e=this.dataService;d.current&&d.current.end&&delete d.current.end;e.addOverlapsObj(a,b);e.unReg();this._getData()},delOverlaps:function(){var a=this.options,b=this.dataService;a.current&&a.current.end&&delete a.current.end;b.delOverlapsObj();a.overlaps.pop();b.unReg();this._getData()},delAllOverlaps:function(){var a=this.options,b=this.dataService;
a.current&&a.current.end&&delete a.current.end;b.delAllOverlapsObj();a.overlaps=[];b.unReg();this._getData()},changeTimeRange:function(a){var b=this.options,d=this.dataService;b.current&&b.current.end&&delete b.current.end;d.changeTimeRange(a);d.unReg();this._getData()},showCloseData:function(){var a=this.options;a.current&&a.current.end&&delete a.current.end;this.doplot(this.ctx,0)}})});