/*
	Copyright (c) 2012-2013,   To get sources and documentation, please visit:

		http://dms.gw.com.cn
*/

//>>built
require({cache:{"commodity/specialTopic/public/js/_darwProperty":function(){define("commodity/specialTopic/public/js/_darwProperty",["dojo/_base/declare"],function(g){return g("commodity.specialTopic.public.js._darwProperty",null,{constructor:function(){this._chart={margins:{l:5,t:5,r:5,b:5},titlePos:"top",titleOrientation:"axis",titleGap:5,titleFont:"normal normal normal 9pt Arial",titleFontColor:"orange"};this._default={type:"Default",gap:0};this._default2={type:"Columns",gap:0.3,vAxis:"y2"};this._grid=
{type:"Grid",lineDashed:!0,hAxis:"x",vAxis:"y"};this._x={labels:"",font:"normal normal normal 9pt Arial",majorTick:{width:2},titleOrientation:"away",titlePos:"top",titleGap:15,titleFont:"normal normal normal 9pt \u9ed1\u4f53",titleFontColor:"orange",natural:!1,leftBottom:!0,includeZero:!1,minorTicks:!1,minorLabels:!0,majorTickStep:5};this._y={vertical:!0,natural:!1,minorTicks:!0,majorTickStep:2,font:"normal normal normal 9pt Arial",title:"\u767e\u4e07\u7f8e\u5143/\u5343\u5428",titleOrientation:"axis",
rotation:0,titlePos:"right",titleGap:5,titleFont:"normal normal normal 12pt \u9ed1\u4f53",titleFontColor:"white",nature:!0,max:0,min:0};this._y2={vertical:!0,includeZero:!1,minorTicks:!0,majorTickStep:2,font:"normal normal normal 9pt Arial",title:"\u7f8e\u5143/\u5428",leftBottom:!1,titleOrientation:"axis",rotation:0,titlePos:"right",titleGap:5,titleFont:"normal normal normal 12pt \u9ed1\u4f53",titleFontColor:"white",nature:!0,max:0,min:0};this._legend={type:"legend",font:"normal normal normal 9pt Arial",
isShow:!0,maxWidthScale:0.9,position:"top"};this._comments={type:"comments",footnotes:"\u811a\u6ce8",footnotesFont:"normal normal normal 6pt Arial",footnotesFontColor:"red",writer:"",writerFont:"normal normal normal 6pt Arial",writerFontColor:"red",sources:"\u4e16\u534e\u8d22\u8baf",sourcesFont:"normal normal normal 6pt Arial",sourcesFontColor:"red"};this._special={plot:"default2"};this._param={url:"",arg:"",id:"",legendName:"",isDoubleAxis:-1,isDoubleDrawStyle:-1,exportId:"",ratio:0,uint_f:"",uint_s:"",
valueRatio_f:1,valueRatio_s:1,step_y_f:3,step_y_s:3,step_x:3};this._export={label:"\u5bfc\u51fa\u56fe\u5f62"}}})})},"commodity/specialTopic/public/js/_toDraw":function(){define("commodity/specialTopic/public/js/_toDraw","dojo/_base/declare,dojo/request/script,commodity/specialTopic/public/js/_util,dojox/charting/widget/exportChart,dojox/charting/widget/Chart,dojox/charting/action2d/Tooltip,dojox/charting/action2d/Magnify,dojox/charting/action2d/Highlight,dojox/charting/plot2d/Default,dojox/charting/plot2d/Columns,dojox/charting/plot2d/Grid,dojox/charting/axis2d/Default,dojox/charting/axis2d/legend,dojox/charting/axis2d/comments,dojox/charting/themes/CustomColor,dojox/charting/plot2d/Areas".split(","),
function(g,c,b,k,y,p,d,u,j,h,s,l,q,f,r){return g("commodity.specialTopic.public.js._toDraw",null,{getDateByMySelf:function(a,d){c.get(a,{jsonp:"callback"}).then(d,function(){})},toDraw:function(a,e,f,b,j){var c=[],h=f[0].length;a._y.title=a._param.uint_f;for(var l=0;l<h;l++){var q=0,w;for(w in f)isNaN(f[w][0])&&q++;if(q==f.length){for(var g in f)f[g].shift();e.shift()}else break}var h=0,t;for(t in e){var l="",s;for(s in e[t])l=e[t][s];c.push({value:h,text:l});h++}c.splice(0,1,{text:"",value:0});j=
void 0==j?a._param.id:j;e=new y(a._chart,j);e.addPlot("default",a._default);(-1!=a._param.isDoubleAxis||-1!=a._param.isDoubleDrawStyle)&&e.addPlot("default2",a._default2);e.addPlot("Grid",a._grid);a._x.labels=c;a._y.majorTickStep=(a._y.max-a._y.min)/a._param.step_y_f;a._x.majorTickStep=30>=c.length?1:10;a._x.majorTickStep=Math.floor(c.length/a._param.step_x);e.addAxis("x",a._x);e.addAxis("y",a._y);if(-1!=a._param.isDoubleAxis)a._y2.majorTickStep=(a._y2.max-a._y2.min)/a._param.step_y_s,a._y2.title=
a._param.uint_s,e.addAxis("y2",a._y2);e.addAxis("legend",a._legend);e.setTheme(r);var j=0,C;for(C in f)t=parseInt(C),-1==a._param.isDoubleAxis&&-1==a._param.isDoubleDrawStyle?e.addSeries(b[t],f[t]):a._param.isDoubleAxis===t+1||a._param.isDoubleDrawStyle===t+1||1==j?(e.addSeries(b[t],f[t],a._special),j=1):e.addSeries(b[t],f[t]);new d(e.chart,"default",{scale:3});new p(e.chart,"default",{text:function(a){var d=a.run&&a.run.data&&a.run.data[a.index],d=Math.round(100*d)/100;return'<table cellpadding="1" cellspacing="0" border="0" style="font-size:0.9em;"><tr><td>\u503c:</td><td align="left"><strong>'+
d+'</strong></td></tr><tr><td>\u65f6\u95f4:</td><td align="left"><strong>'+c[a.index+1].text+"</strong></td></tr></table>"}});new u(e.chart,"default");if(-1!=a._param.isDoubleAxis||-1!=a._param.isDoubleDrawStyle)new u(e.chart,"default2"),new p(e.chart,"default2",{text:function(a){var d=a.run&&a.run.data&&a.run.data[a.index],d=Math.round(100*d)/100;return'<table cellpadding="1" cellspacing="0" border="0" style="font-size:0.9em;"><tr><td>\u503c:</td><td align="left"><strong>'+d+'</strong></td></tr><tr><td>\u65f6\u95f4:</td><td align="left"><strong>'+
c[a.index+1].text+"</strong></td></tr></table>"}});e.render();""!=a._param.exportId&&new k({chart:e.chart,label:"\u5bfc\u51fa\u56fe\u5f62"},a._param.exportId)}})})},"commodity/specialTopic/public/js/_util":function(){define("commodity/specialTopic/public/js/_util",["dojo/_base/declare"],function(g){return g("commodity.specialTopic.public.js._util",null,{_subStr:function(c){for(var b=[],k=0;k<c.length;k++)b[k]=c.charAt(k).match(/[\u0391-\uFFE5]/)?22:11;return b},_arrayMax:function(c){var b=c[0];for(i=
0;i<c.length;i++)null==b||isNaN(b)?null!=c[i]&&(b=c[i]):null!=c[i]&&c[i]>b&&(b=c[i]);return b},_arrayMin:function(c){var b=c[0];for(i=0;i<c.length;i++)null==b||isNaN(b)?null!=c[i]&&(b=c[i]):null!=c[i]&&c[i]<b&&(b=c[i]);return b},_keySort:function(c,b){var k=[],g=[],p=[],d=[],u="",j=[],h;for(h in c)g.push(parseInt(h)),d.push(c[h]);for(var s in b)for(var l in b[s])p.push(b[s][l]);for(var q in p)for(var f in g)p[q]==g[f]&&j.push(f);p=0;for(s in b)for(var r in b[s])b[s][r]=j[p],p++;for(q in g)u=q<g.length-
1?u+(g[q]+","):u+g[q];k.push(u);k.push(d);k.push(b);k.push(j);return k},shutVaule:function(c,b){for(i=0;i<b.length-1;i++)b[i].indexOf(".")}})})},"commodity/specialTopic/public/js/_ajax":function(){define("commodity/specialTopic/public/js/_ajax","dojo/_base/lang,dojo/_base/declare,dojo/request,commodity/specialTopic/public/js/_util,commodity/specialTopic/public/js/_toDraw,commodity/specialTopic/public/js/_darwProperty".split(","),function(g,c,b,k,y){function p(d,b,j,c){-1==j._param.isDoubleAxis||j._param.isDoubleAxis==
c?(j._y.max=1.05*d,j._y.min=b-b/10):(j._y2.max=1.05*d,j._y2.min=b-b/10)}return c("commodity.specialTopic.public.js._ajax",null,{getDateByMySelf:function(d,b){script.get(d,{jsonp:"callback"}).then(b,function(){})},getDateAutoByone:function(d,c){debugger;b(d._param.url,{jsonp:"callback",query:d._param.arg}).then(g.hitch(d,c.changeData))},getDateByMore:function(d,c){b(d._param.url,{jsonp:"callback",query:d._param.arg}).then(g.hitch(d,c.changeMoreData))},changeData:function(d){var b=-1E15,c=1E15;if(!(1>
d.length||d==[]||null==d||void 0==d)){var h=this._param.legendName,g=new k,l=new y,q=[],f=[],r=[],a;for(a in d)for(var e in d[a])if("date"==e){var o;0==a&&(o={value:0,text:""},q.push(o));o={value:parseInt(a)+1,text:d[a][e].toString()};q.push(o)}else o=e.substring(5,5+(e.length-5))-1,0==a&&(f[o]="",""==h?r.push(e):r.push(h[o])),f[o]=a<d.length-1?f[o]+(""==d[a][e]?"NaN,":d[a][e]+","):f[o]+(""==d[a][e]?NaN:d[a][e]);var d=2,m;for(m in f){h=f[m].split(",");for(a=0;a<h.length;a++)h[a]=this._param.isDoubleAxis==
d?parseFloat(h[a])*this._param.valueRatio_s:parseFloat(h[a])*this._param.valueRatio_f;a=g._arrayMax(h);e=g._arrayMin(h);isNaN(a)||(b=b>a?b:a);isNaN(e)||(c=c<e?c:e);this._param.isDoubleAxis==d&&(p(b,c,this,d),b=-1E15,c=1E15);f[m]=h;d++}p(b,c,this,d);l.toDraw(this,q,f,r)}},changeMoreData:function(d){var b=-1E15,c=1E15;if(!(1>d.length||d==[]||null==d||void 0==d)){var g=new k,s=new y,l=this._param.id,q="",f;for(f in l){for(var r=[],a=[],e=[],b=-1E15,c=1E15,o=this._param.legendName,m=0;m<d.length;m++)for(var v in d[m])if("date"==
v){var n;0==m&&(n={value:0,text:""},r.push(n));n={value:parseInt(m)+1,text:d[m][v].toString()};r.push(n)}else for(var z in l[f])if(n=v.substring(5,5+(v.length-5))-1,l[f][z]-1==n){0==m&&(q=f,a[n]="",e.push(o[n]));a[n]=m<d.length-1?a[n]+(""==d[m][v]?"NaN,":d[m][v]+","):a[n]+(""==d[m][v]?NaN:d[m][v]);break}o=0;m=[];n=2;for(var A in a){for(var x=a[A].split(","),w=0;w<x.length;w++)x[w]=parseFloat(x[w]);var w=g._arrayMax(x),B=g._arrayMin(x);isNaN(w)||(b=b>w?b:w);isNaN(B)||(c=c<B?c:B);this._param.isDoubleAxis==
n&&(p(b,c,this,n),b=-1E15,c=1E15);m[o]=x;o++;n++}p(b,c,this,n);s.toDraw(this,r,m,e,q)}}}})})},"commodity/specialTopic/public/js/_publicParam":function(){define("commodity/specialTopic/public/js/_publicParam",["dojo/_base/declare"],function(g){return g("commodity.specialTopic.public.js._publicParam",null,{constructor:function(){this.url="http://10.15.107.157:8080/specialTopic/";this.indexUrl=/^http:\/\/10.15.107.157/}})})},"commodity/specialTopic/public/view/dialog":function(){require({cache:{"url:commodity/specialTopic/public/view/dialog.html":'<div data-dojo-attach-point="containerNode" class="spacer">\r\n\t<div data-dojo-id="dialogConfirm" data-dojo-attach-point="dialogConfirm" data-dojo-type="dijit/Dialog"  data-dojo-props="title:\'\u63d0\u793a\u4fe1\u606f\'" style="display:none;width:400px;">\r\n\t\t<div class="vbox" style="height: 100px">\r\n\t\t\t<div data-dojo-attach-point="tipInfo" class="spacerx" style="text-align: center; line-height:50px;"></div>\r\n\t\t\t<div class="spacerx" style="text-align: center; line-height:50px;">\r\n\t\t\t\t<button data-dojo-type="dijit/form/Button" type="button" onclick="dialogConfirm.onCancel()">\u5173\u95ed</button>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>'}});
define("commodity/specialTopic/public/view/dialog","dojo/_base/declare,dijit/_WidgetBase,dijit/_TemplatedMixin,dijit/_WidgetsInTemplateMixin,dijit/layout/_ContentPaneResizeMixin,dojo/dom,dijit/registry,dojo/text!./dialog.html".split(","),function(g,c,b,k,y,p,d,u){return g("commodity.specialTopic.public.view.dialog",[c,b,k,y],{templateString:u,postMixInProperties:function(){},postCreate:function(){},showDialog:function(d){this.tipInfo.innerHTML=d;this.dialogConfirm.show()}})})},"url:commodity/specialTopic/public/view/dialog.html":'<div data-dojo-attach-point="containerNode" class="spacer">\r\n\t<div data-dojo-id="dialogConfirm" data-dojo-attach-point="dialogConfirm" data-dojo-type="dijit/Dialog"  data-dojo-props="title:\'\u63d0\u793a\u4fe1\u606f\'" style="display:none;width:400px;">\r\n\t\t<div class="vbox" style="height: 100px">\r\n\t\t\t<div data-dojo-attach-point="tipInfo" class="spacerx" style="text-align: center; line-height:50px;"></div>\r\n\t\t\t<div class="spacerx" style="text-align: center; line-height:50px;">\r\n\t\t\t\t<button data-dojo-type="dijit/form/Button" type="button" onclick="dialogConfirm.onCancel()">\u5173\u95ed</button>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>'}});
define("commodity/trendMagnify/src","dojox/charting/widget/Chart,dojox/charting/axis2d/Default,dojox/charting/axis2d/comments,dojox/charting/axis2d/legend,dojox/charting/plot2d/StackedAreas,dojox/charting/plot2d/Grid,dojox/charting/themes/CustomColor,dojo/parser,dojo/store/Memory,dojo/request,dojox/slickgrid/slickgrid,dojo/dom,dojo/on,dijit/registry,dojo/dom-attr,dojo/dom-style,commodity/specialTopic/public/js/_darwProperty,commodity/specialTopic/public/js/_toDraw,commodity/specialTopic/public/js/_ajax,commodity/specialTopic/public/js/_publicParam,dojox/charting/widget/exportChart,dojo/request/script,commodity/specialTopic/public/view/dialog".split(","),
function(g,c,b,k,y,p,d,u,j,h,s,l,q,f,r,a,e,o,m,v,n,z,A){var x=new v;return function(){function d(a,c){f.remove("areaGraph");var b=new e,g=new m;b._param.url=n;b._param.arg="commTag="+param.id+"&startDate="+a+"&endDate="+c+"&period="+param.period;b._param.id="areaGraph";b._param.legendName=p;b._param.exportId="exportGraph";b._default.type="Areas";g.getDateAutoByone(b,g)}function b(a,d,c){var f=[];if(c){mstore=new j({data:f});columns=[{id:"date",name:"\u65e5\u671f",field:"date",width:100,sortable:!0}];
c=param.desc.split(",");for(f=0;f<c.length;f++){var e={};e.id="price"+f;e.field="price"+(f+1);e.name=c[f];e.width=150;columns.push(e)}options={enableColumnReorder:!1,forceFitColumns:!0};k=new s({store:mstore,columns:columns,options:options},"tableData");k.startup()}h(n,{jsonp:"callback",query:"commTag="+param.id+"&startDate="+a+"&endDate="+d+"&period="+param.period}).then(function(a){k.set("store",new j({data:a}));k.refresh(a)},function(){})}function c(a){var e;if("y"==a){if(2>o){o++;return}a=f.byId("yFrom").get("value")+
"";e=f.byId("yTo").get("value")+""}else a=f.byId("dmFrom").get("displayedValue"),e=f.byId("dmTo").get("displayedValue");if(""!=a&&""!=e){a=a.replace(RegExp("-","g"),"");e=e.replace(RegExp("-","g"),"");if(a>e)return(new A).showDialog("\u5f00\u59cb\u65f6\u95f4\u5e94\u5c0f\u4e8e\u7ed3\u675f\u65f6\u95f4"),!1;d(a,e);b(a,e,!1)}}var g=(new v).indexUrl;h.register(g,z);var k,n=x.url+param.url,p=param.desc.split(","),o=0;u.parse().then(function(){param.unit&&""!=param.unit?(l.byId("unit").innerHTML=param.unit,
a.set("unitDesc","display","block")):a.set("unitDesc","display","none");l.byId("period").innerHTML=param.pdesc;f.byId("dmFrom").on("change",function(){c("dm")});f.byId("dmTo").on("change",function(){c("dm")});f.byId("yFrom").on("change",function(){c("y")});f.byId("yTo").on("change",function(){c("y")});for(var e=(new Date).getFullYear(),g=e;1970<=g;g--){var h=g+"";f.byId("yFrom").addOption({label:h,value:h});f.byId("yTo").addOption({label:h,value:h})}g=param.from+"";h=param.to+"";4<g.length&&(g=g.substring(0,
4)+"-"+g.substring(4,6)+"-"+g.substring(6),h=h.substring(0,4)+"-"+h.substring(4,6)+"-"+h.substring(6));var e=(new Date).getFullYear(),j=param.period,e={m:{pattern:"yyyy-MM",start:e+"-01",end:e+"-12"},d:{pattern:"yyyy-MM-dd",start:e+"-01-01",end:e+"-12-31"}};"m"==j||"d"==j?(f.byId("dmFrom").constraints.datePattern=e[j].pattern,f.byId("dmTo").constraints.datePattern=e[j].pattern,r.set("dmFrom","value",g),r.set("dmTo","value",h),l.byId("dayMonth").style.display="block",l.byId("year").style.display="none"):
(l.byId("dayMonth").style.display="none",l.byId("year").style.display="block",f.byId("yFrom").set("value",g),f.byId("yTo").set("value",h));g=g.replace(RegExp("-","g"),"");h=h.replace(RegExp("-","g"),"");d(g,h);b(g,h,!0);q(l.byId("exportTable"),"click",function(){var a=param.unit,b=param.period,c=param.desc.split(","),d="",e="";"none"==l.byId("dayMonth").style.display?(d=f.byId("yFrom").get("value"),e=f.byId("yTo").get("value")):(d=f.byId("dmFrom").get("value"),e=f.byId("dmTo").get("value"));k.saveAsExcel("\u5927\u667a\u6167\u6570\u636e\u8868\u683c",
"<tr>"+("<td colspan='3' algin='center'>\u6307\u6807\u540d\u79f0\uff1a"+c+"</td>")+"</tr><tr>"+("<td>\u5355\u4f4d\uff1a"+a+"</td>")+("<td>\u9891\u7387\uff1a"+b+"</td>")+("<td>\u65f6\u95f4\u533a\u95f4\uff1a"+d+" \u81f3 "+e+"</td>")+"</tr>","\u5927\u667a\u6167\u6570\u636e")})})}});