/*
	Copyright (c) 2012-2013,   To get sources and documentation, please visit:

		http://dms.gw.com.cn
*/

//>>built
require({cache:{"dts/tradepolicy/view/common":function(){define(["dojo/date/locale"],function(){return{$:function(a){return document.getElementById&&document.getElementById(a)?document.getElementById(a):document.all&&document.all(a)?document.all(a):document.layers&&document.layers[a]?document.layers[a]:!1},Class:function(a){for(var d=[],e=document.getElementsByTagName("*"),g=0;g<e.length;g++)e[g].className==a&&(d[d.length]=e[g]);return d},sortB2S:function(a){return a.sort(function(a,e){return a<e?
1:-1})},sortS2B:function(a){return a.sort(function(a,e){return a>e?1:-1})},del_html_tags:function(a){var d="";return d=a.replace(/<[^>]+>/g,"")},trim:function(a,d){var e;e=a.replace(/(^\s+)|(\s+$)/g,"");"g"==d.toLowerCase()&&(e=e.replace(/\s/g,""));return e},addClass:function(a,d){if(a.className){var e=a.className;a.className=e+" "+d}else a.className=d},removeClass:function(a,d){if(hasClass(a,d))a.className=a.className.replace(RegExp("(\\s|^)"+d+"(\\s|$)")," ")},hasClass:function(a,d){return a.className.match(RegExp("(\\s|^)"+
d+"(\\s|$)"))}}})}}});
define("dts/tradepolicy/src","dijit/dijit,dojo/parser,dts/tradepolicy/view/common,dts/tradepolicy/view/socket,dojox/charting/widget/Chart,dojox/charting/axis2d/Default,dojox/charting/axis2d/comments,dojox/charting/axis2d/legend,dojox/charting/plot2d/Areas,dojox/charting/plot2d/Grid,dojox/charting/themes/WhiteCustom,dojox/charting/widget/exportChart,dijit/layout/BorderContainer,dijit/layout/ContentPane,dojox/charting/action2d/Tooltip,dojox/charting/action2d/Magnify,dojox/charting/action2d/Highlight,dojox/store/WebSocket".split(","),function(a,
d,e,g,m,s,t,u,n,v,o,w,x,y,p,z,q,r){return function(){function a(e){var b=[];for(i=0;i<k;i++)b.push(parseFloat(e[0][5]));return b}var d=window.location.href.split("?id=")[1]?window.location.href.split("?id=")[1]:"002",g=new r({}),j=new m({margins:{l:0,t:10,r:10,b:10}},"area"),k=0;g.query({service:"rpc",so:"javadataproxy.jar","function":"gw/UIMain",paraencode:"base64",parameter:btoa("/gweb/getTradeStrageList?id="+d+""),response_times:1,response_mode:0},{}).then(function(d){var b=d[0].result.datas;k=
d[0].result.datas.length;var d=a(b),h=[];h.push(b[0][15]);h.push(b[b.length-1][15]);var g=k,l=[],f=parseInt(g/10);if(1>f)for(i=0;i<g;i++)l.push({value:i,text:b[i][15]});else{for(i=0;i<g;i++)0==i%f&&l.push({value:i,text:b[i][15]});l.push({value:11*f,text:""})}x_l=parseInt(k/10);var g=e.sortS2B(a(b))[0]-200,b=b[b.length-1],f="",c=e.$("myTopBar"),f='<span class="fn-left">'+b[0]+"</span>",f=f+('<span class="fn-right">\u6295\u987e:'+b[3]+"</span>");c.innerHTML=f;e.$("policy-title").innerText=b[2];f="";
c=e.$("date-time");f+=" \u8d77\u59cb:"+h[0].split("-").join("/")+"&nbsp;\u622a\u6b62:"+h[1].split("-").join("/")+"";c.innerHTML=f;f=e.$("myTab");c="";c='<table><tr class="grey"><td class="bdbtm" colspan="2">\u6536\u76ca</td></tr>'+('<tr><td>\u4eca\u65e5\u6536\u76ca</td><td class="txtR">'+parseFloat(b[4]).toFixed(2)+"</td></tr>");c+='<tr><td>\u7d2f\u79ef\u6536\u76ca</td><td class="txtR">'+parseFloat(b[5]).toFixed(2)+"</td></tr>";c+='<tr><td>\u8d85\u989d\u6536\u76ca</td><td class="txtR">'+parseFloat(b[6]).toFixed(2)+
"</td></tr>";c=c+'<tr class="grey"><td class="bdbtm" colspan="2">\u98ce\u9669</td></tr>'+('<tr><td>\u6700\u5927\u56de\u64a4</td><td class="txtR">'+parseFloat(b[7]).toFixed(2)+"</td></tr>");c+='<tr><td>\u590f\u666e\u6bd4\u7387</td><td class="txtR">'+parseFloat(b[8]).toFixed(2)+"</td></tr>";c+='<tr><td>\u03b2\u7cfb\u6570</td><td class="txtR">'+parseFloat(b[9]).toFixed(2)+"</td></tr>";c=c+'<tr class="grey"><td class="bdbtm" colspan="2">\u4ea4\u6613\u89c4\u5219</td></tr>'+('<tr><td>\u6700\u4f4e\u5f00\u4ed3</td><td class="txtR">'+
parseFloat(b[10]).toFixed(2)+"</td></tr>");c+='<tr><td>\u5f00\u4ed3</td><td class="txtR">'+b[11]+"</td></tr>";c+='<tr><td>\u6301\u4ed3</td><td class="txtR">'+b[12]+"</td></tr>";c+='<tr><td>\u6b62\u76c8\u6b62\u635f</td><td class="txtR">'+b[13]+"</td></tr>";f.innerHTML=c+"</table>";b="";f=e.$("begin-time");b="\u8d77\u6b62\u65f6\u95f4:"+h[0].split("-")[0]+"\u5e74"+h[0].split("-")[1]+"\u6708"+h[0].split("-")[2]+"\u65e5\u81f3"+h[1].split("-")[0]+"\u5e74"+h[1].split("-")[1]+"\u6708"+h[1].split("-")[2]+
"\u65e5";f.innerHTML=b;h=x_l;j.addPlot("default",{type:n,globalAlpha:0.7});j.addPlot("Grid",{type:"Grid",lineDashed:!0,hAxis:"x",vAxis:"y",show:!0});j.addAxis("x",{font:"12px",majorTick:{},title:"",titleOrientation:"away",titleGap:10,titleFont:"12px",minorTicks:!1,titleFontColor:"#000",fixLower:"major",fixUpper:"major",labels:l,majorTickStep:h,rotation:270});j.addAxis("y",{vertical:!0,leftBottom:!0,includeZero:!1,font:"12px",fixLower:"major",fixUpper:"major",natural:!0,min:g,titleOrientation:"axis",
rotation:0});j.setTheme(o);j.addSeries("Series 1",d,{fill:["#0073ff","#131313"],stroke:"red"});new p(j.chart,"default");new q(j.chart,"default");j.render()})}});