//>>built
require({cache:{"url:dojox/slickgrid/templates/pager.html":'<div tabindex="0" hidefocus="" class="slick-pager">\r\n\t<span class="prompt_text" data-dojo-attach-point="prompt_text"></span>\r\n\t<span class="slick-pager-nav" data-dojo-attach-event="onclick:_btnProxy">\r\n\t\t<button data-dojo-type="dijit/form/Button" data-dojo-props="name:\'First\'">\u9996\u9875</button>\r\n\t\t<button data-dojo-type="dijit/form/Button" data-dojo-props="name:\'Prev\'">\u4e0a\u4e00\u9875</button>\r\n\t\t<input  data-dojo-type="dijit/form/NumberTextBox" data-dojo-props="\'class\':\'pageInput\'" data-dojo-attach-point="pageInputNode" />/<span data-dojo-attach-point="totalPageNode"></span>\r\n\t\t<button data-dojo-type="dijit/form/Button" data-dojo-props="name:\'Next\'">\u4e0b\u4e00\u9875</button>\r\n\t\t<button data-dojo-type="dijit/form/Button" data-dojo-props="name:\'Last\'">\u5c3e\u9875</button>\r\n\t</span>\r\n</div>'}});
define("dojox/slickgrid/controls/pager","dijit/_WidgetBase,dijit/_TemplatedMixin,dijit/_WidgetsInTemplateMixin,dijit/registry,dojo/dom-geometry,dojo/_base/declare,dojo/_base/lang,dojo/on,dojo/text!../templates/pager.html,dojo/query,dojo/NodeList-traverse,dojo/NodeList-manipulate".split(","),function(e,f,g,k,h,i,b,l,j){return i("dojox.grid.pager",[e,f,g],{templateString:j,grid:null,goFirstOnStart:!1,postMixInProperties:function(){this.inherited(arguments)},postCreate:function(){this.store=this.grid.get("store");
this.pageNum=this.pageNum||1;this.pageSize=Number(this.pageSize||25);if(this.store.data&&this.store.data.length)this.totalPages=Math.ceil(this.store.data.length/this.pageSize);this.pageInputNode.on("keyup",b.hitch(this,this._gotoSpecifiedPage));this.inherited(arguments);this.isMemory="dojo.store.Memory"==this.grid.store.declaredClass?!0:!1;this.isSoStore="dojox.store.GridSOStore"==this.grid.store.declaredClass?!0:!1},startup:function(){this.inherited(arguments);this.updatePager();this.goFirstOnStart&&
this._gotoFirst()},resize:function(a){a&&h.setMarginBox(this.domNode,{w:a.w});this.inherited(arguments)},boforePageChangeFunc:function(){return!1},_btnProxy:function(a){a=a.target.name;if(a in{First:1,Last:1,Prev:1,Next:1})this["_goto"+a]()},_gotoFirst:function(){if(1<=this.pageNum)this.oldPageNum=this.pageNum,this.pageNum=1,this.grid.scrollTo(0),this.grid.invalidateAllRows(),this.isMemory||this.isSoStore?(b.mixin(this.grid.get("queryOptions"),{start:0,count:this.pageSize}),this.grid.renderQuery()):
this.boforePageChangeFunc(this.oldPageNum,this.pageNum,"first")?this.grid.renderQuery({}):this.grid.renderQuery(),this.updatePager()},_gotoLast:function(){if(this.pageNum<this.totalPages)this.oldPageNum=this.pageNum,this.pageNum=this.totalPages,this.grid.scrollTo(0),this.grid.invalidateAllRows(),this.isMemory||this.isSoStore?(b.mixin(this.grid.get("queryOptions"),{start:(this.pageNum-1)*this.pageSize,count:this.pageSize}),this.grid.renderQuery()):this.boforePageChangeFunc(this.oldPageNum,this.pageNum,
"last")?this.grid.renderQuery({}):this.grid.renderQuery(),this.updatePager()},_gotoPrev:function(){if(1<this.pageNum)this.oldPageNum=this.pageNum,this.pageNum-=1,this.grid.scrollTo(0),this.grid.invalidateAllRows(),this.isMemory||this.isSoStore?(b.mixin(this.grid.get("queryOptions"),{start:(this.pageNum-1)*this.pageSize,count:this.pageSize}),this.grid.renderQuery()):this.boforePageChangeFunc(this.oldPageNum,this.pageNum,"prev")?this.grid.renderQuery({}):this.grid.renderQuery(),this.updatePager()},
_gotoNext:function(){if(this.pageNum<this.totalPages)this.oldPageNum=this.pageNum,this.pageNum+=1,this.grid.scrollTo(0),this.grid.invalidateAllRows(),this.isMemory||this.isSoStore?(b.mixin(this.grid.get("queryOptions"),{start:(this.pageNum-1)*this.pageSize,count:this.pageSize}),this.grid.renderQuery()):this.boforePageChangeFunc(this.oldPageNum,this.pageNum,"next")?this.grid.renderQuery({}):this.grid.renderQuery(),this.updatePager()},_gotoSpecifiedPage:function(a){if(13==a.keyCode&&(a=this.pageInputNode.getValue(),
a<=this.totalPages&&1<=a))this.oldPageNum=this.pageNum,this.pageNum=a,this.grid.scrollTo(0),this.grid.invalidateAllRows(),this.isMemory||this.isSoStore?(b.mixin(this.grid.get("queryOptions"),{start:(this.pageNum-1)*this.pageSize,count:this.pageSize}),this.grid.renderQuery()):this.boforePageChangeFunc(this.oldPageNum,this.pageNum,"specified")?this.grid.renderQuery({}):this.grid.renderQuery(),this.updatePager()},refresh:function(a,c,d){isNaN(parseInt(c))||(this.pageNum=parseInt(c));isNaN(parseInt(a))?
a.then(b.hitch(this,function(a){this.totalPages=a;this.updatePager()})):(this.totalPages=parseInt(a),this.updatePager());"undefined"!=typeof d&&this.update_prompt_text(d)},update_prompt_text:function(a){this.prompt_text.style.display="block";this.prompt_text.innerHTML="<span class='pagePrompt'></span>"+a},clear_prompt_text:function(){this.prompt_text.style.display="none";this.prompt_text.innerHTML=""},updatePager:function(){this.totalPageNode.innerHTML=this.totalPages||"";this.pageInputNode.set("value",
this.pageNum)}})});